package radius

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/rett/tacctl/internal/cidr"
	"github.com/rett/tacctl/internal/conf"
	"github.com/rett/tacctl/internal/model"
	"github.com/rett/tacctl/internal/names"
	"github.com/rett/tacctl/internal/store"
	"github.com/rett/tacctl/internal/yamlpy"
)

const (
	// header opens the conf and users files (RADIUS_HEADER).
	header = "# GENERATED by tacctl from /etc/tacctl/store.yaml and tacctl.yaml. Edits here are overwritten,\n" +
		"# and there is no way to adopt one: change users, groups, scopes and listeners with tacctl.\n"
	// ridPlaceholder stands for the render id until all three files exist.
	ridPlaceholder = "@TACCTL_RENDER_ID@"
)

// internalAttrs are tacctl's own attributes: a users entry carries the
// group's values in them (control list), the policy turns them into vendor
// attributes. Numbered at the top of the range FreeRADIUS reserves for
// site-local attributes that never go into a packet (3000-3999).
var internalAttrs = []struct {
	name   string
	number int
	kind   string
}{
	{"Tacctl-Priv-Lvl", 3990, "integer"},
	{"Tacctl-Juniper-Class", 3991, "string"},
	{"Tacctl-WTI-Super", 3992, "integer"},
}

// vendorReply is VENDOR_REPLY: per vendor, the attribute an Access-Accept
// gets, the control attribute that must be there and the value as unlang
// writes it.
var vendorReply = map[string]struct{ attr, control, value string }{
	"cisco":   {"Cisco-AVPair", "Tacctl-Priv-Lvl", `"shell:priv-lvl=%{control:Tacctl-Priv-Lvl}"`},
	"juniper": {"Juniper-Local-User-Name", "Tacctl-Juniper-Class", "&control:Tacctl-Juniper-Class"},
	"wti":     {"WTI-Super", "Tacctl-WTI-Super", "&control:Tacctl-WTI-Super"},
}

// Output is a rendered state: the three files and what goes with them.
type Output struct {
	Conf       string // <raddb>/tacctl-radius.conf
	Users      string // <raddb>/tacctl-radius.users
	Dictionary string // <raddb>/tacctl-radius-dictionary/dictionary
	// RenderID is the first 16 hex digits of the SHA-256 of the three texts
	// (with the id's placeholder in place); it is in conf and users.
	RenderID string
	// Notes are what the rendered state means for an operator (Notes).
	Notes []Note
}

// WriteDir writes conf, users and dictionary into dir (which must exist),
// mode 0600, as 'render-live' stages them.
func (o *Output) WriteDir(dir string) error {
	for _, f := range []struct{ name, text string }{
		{"conf", o.Conf}, {"users", o.Users}, {"dictionary", o.Dictionary},
	} {
		if err := os.WriteFile(filepath.Join(dir, f.name), []byte(f.text), 0o600); err != nil {
			return err
		}
	}
	return nil
}

// ConfView is radius_conf_view: the merged tacctl.yaml view the renderer
// takes, refused when the file does not parse or is not a mapping (the view
// would silently be the defaults). The messages are 0.1.16's: yaml_problem's
// "<path>: <problem> (line L, column C)" or "<path>: not a YAML mapping",
// then " -- fix it before rendering" (conf.RenderProblem).
func ConfView(c *conf.Config) (*yamlpy.Map, error) {
	if msg, fixIt := conf.RenderProblem(c.Path); msg != "" {
		if fixIt {
			msg += " -- fix it before rendering"
		}
		return nil, errorf("%s", msg)
	}
	return c.Merged(), nil
}

// RenderStore is render_radius for a store: the store must validate
// (store_validate, with its messages), then Render.
func RenderStore(s *store.Store, merged *yamlpy.Map, p Params) (*Output, error) {
	if errs := store.Validate(s.Doc()); len(errs) > 0 {
		return nil, errorf("cannot render an invalid model:\n  - %s", strings.Join(errs, "\n  - "))
	}
	return Render(model.FromStore(s), merged, p)
}

// Render is render_radius: the model and the merged tacctl.yaml view (what
// conf.Config.Merged returns) become the three files. The model is taken as
// validated (RenderStore validates a store first); a dangling reference is
// an *Error rather than a crash.
func Render(m *model.Model, merged *yamlpy.Map, p Params) (*Output, error) {
	confText, err := renderConf(m, merged, p)
	if err != nil {
		return nil, err
	}
	usersText, err := renderUsers(m)
	if err != nil {
		return nil, err
	}
	dictText := renderDictionary(p)
	sum := sha256.Sum256([]byte(confText + "\x00" + usersText + "\x00" + dictText))
	rid := hex.EncodeToString(sum[:])[:16]
	return &Output{
		Conf:       strings.ReplaceAll(confText, ridPlaceholder, rid),
		Users:      strings.ReplaceAll(usersText, ridPlaceholder, rid),
		Dictionary: dictText,
		RenderID:   rid,
		Notes:      Notes(m, merged),
	}, nil
}

// servedScopes is radius_scopes: the scopes this backend serves (no
// protocols filter, or one naming radius), by name.
func servedScopes(m *model.Model) []*model.Scope {
	var out []*model.Scope
	for _, s := range m.Scopes {
		if s.ServedBy("radius") {
			out = append(out, s)
		}
	}
	return out
}

// served is one user the backend can authenticate and the scopes of the user
// that it serves, in the user's order.
type served struct {
	user   *model.User
	scopes []string
}

// servedUsers is radius_users: enabled users with a hash that are not the
// accounting sink, in a scope RADIUS serves, by name.
func servedUsers(m *model.Model) []served {
	scopes := map[string]bool{}
	for _, s := range servedScopes(m) {
		scopes[s.Name] = true
	}
	users := slices.Clone(m.Users)
	sort.Slice(users, func(i, j int) bool { return users[i].Name < users[j].Name })
	var out []served
	for _, u := range users {
		if u.IsDisabled() {
			continue
		}
		var mine []string
		for _, s := range u.Scopes {
			if scopes[s] {
				mine = append(mine, s)
			}
		}
		if len(mine) > 0 {
			out = append(out, served{u, mine})
		}
	}
	return out
}

// groupOf is the group of u, or an *Error for a user the model has no group
// for (only an unvalidated model has one).
func groupOf(m *model.Model, u *model.User) (*model.Group, int, error) {
	g := m.Group(u.Group)
	if g == nil {
		return nil, 0, errorf("user '%s' is in nonexistent group '%s'", u.Name, u.Group)
	}
	if g.PrivLvl == nil {
		return nil, 0, errorf("group '%s' has no integer priv_lvl", g.Name)
	}
	return g, *g.PrivLvl, nil
}

// renderUsers is render_users_text: one entry per (user, scope).
func renderUsers(m *model.Model) (string, error) {
	var w strings.Builder
	w.WriteString(header)
	w.WriteString("#\n" +
		"# One entry per user and scope. Tmp-String-0 is set by the policy in tacctl-radius.conf to\n" +
		"# '<render id>/<scope of the client>': a user matches only from a client of a scope they are in.\n" +
		"# Disabled users and the accounting sink have no entry.\n" +
		"# The Tacctl-* items go to the control list, never into a packet: the policy makes a vendor's\n" +
		"# attribute from them for a client whose scope or tag asks for it. The reply is Service-Type.\n")
	for _, e := range servedUsers(m) {
		u := e.user
		if strings.HasPrefix(u.Name, "DEFAULT") {
			return "", errorf("user '%s' cannot be served over RADIUS: FreeRADIUS reads a users entry whose "+
				"name starts with DEFAULT as a default for everyone. Rename the user, or keep its "+
				"scopes TACACS+-only ('tacctl scope protocols <scope> set tacacs').", u.Name)
		}
		raw, err := HashRaw(u.Hash)
		if err != nil {
			return "", err
		}
		g, lvl, err := groupOf(m, u)
		if err != nil {
			return "", err
		}
		serviceType := "NAS-Prompt-User"
		if lvl == 15 {
			serviceType = "Administrative-User"
		}
		wti, _ := WTISuper(lvl)
		control := fmt.Sprintf(", Tacctl-Priv-Lvl := %d, Tacctl-Juniper-Class := %s, Tacctl-WTI-Super := %d",
			lvl, frDQ(g.JuniperClass), wti)
		for _, scope := range e.scopes {
			fmt.Fprintf(&w, "\n%s\tTmp-String-0 == \"%s/%s\", Crypt-Password := %s%s\n",
				u.Name, ridPlaceholder, scope, frDQ(raw), control)
			w.WriteString("\tService-Type = " + serviceType + ",\n\tFall-Through = No\n")
		}
	}
	return w.String(), nil
}

// netOf parses a CIDR the store holds; an unparsable one is an *Error
// (a validated model has none).
func netOf(c string) (cidr.Network, error) {
	n, err := cidr.Parse(c)
	if err != nil {
		return n, errorf("%s", err.Error())
	}
	return n, nil
}

// srcIn is _src_in: the policy test for a source address inside a network.
func srcIn(n cidr.Network) string {
	attr := "&Packet-Src-IP-Address"
	if n.IsIPv6() {
		attr = "&Packet-Src-IPv6-Address"
	}
	return fmt.Sprintf("(%s && (%s <= %s))", attr, attr, n.String())
}

// sortedNets parses list and orders it as sorted(list, key=cidr_key): by
// (version, broadcast, network), stable.
func sortedNets(list []string) ([]cidr.Network, error) {
	nets := make([]cidr.Network, 0, len(list))
	for _, c := range list {
		n, err := netOf(c)
		if err != nil {
			return nil, err
		}
		nets = append(nets, n)
	}
	sort.SliceStable(nets, func(i, j int) bool { return nets[i].SortKey().Less(nets[j].SortKey()) })
	return nets, nil
}

// filterPolicy is render_filter_policy: the body of 'policy { tacctl_filter
// { ... } }' for filters.deny/allow, or "" when there are none. A filtered
// packet gets no answer.
func filterPolicy(f model.Filters) (string, error) {
	const drop = "\t\t\tupdate control {\n" +
		"\t\t\t\t&Response-Packet-Type := Do-Not-Respond\n" +
		"\t\t\t}\n" +
		"\t\t\ttacctl_drop\n"
	deny, err := sortedNets(f.Deny)
	if err != nil {
		return "", err
	}
	allow, err := sortedNets(f.Allow)
	if err != nil {
		return "", err
	}
	tests := func(nets []cidr.Network) string {
		parts := make([]string, len(nets))
		for i, n := range nets {
			parts[i] = srcIn(n)
		}
		return strings.Join(parts, " || ")
	}
	var w strings.Builder
	if len(deny) > 0 {
		w.WriteString("\t\t# filters.deny\n\t\tif (" + tests(deny) + ") {\n" + drop + "\t\t}\n")
	}
	if len(allow) > 0 {
		w.WriteString("\t\t# filters.allow\n\t\tif (!(" + tests(allow) + ")) {\n" + drop + "\t\t}\n")
	}
	return w.String(), nil
}

// listener is one listen{} section: radius_listeners' tuple.
type listener struct {
	name, role, key, host string
	port                  int
}

// listeners is radius_listeners: listeners.radius in effect.
func listeners(merged *yamlpy.Map) ([]listener, error) {
	if problems := conf.ListenersProblems(merged, "", false); len(problems) > 0 {
		return nil, errorf("tacctl.yaml: %s", strings.Join(problems, "; "))
	}
	var out []listener
	for _, l := range conf.ListenersEffective(merged, "radius") {
		host, port, _ := conf.SplitListenAddress(l.Address)
		key := "ipaddr"
		if l.Network == "udp6" {
			key = "ipv6addr"
			if host == "" {
				host = "::"
			}
		} else if host == "" {
			host = "*"
		}
		out = append(out, listener{l.Name, l.Role, key, host, port})
	}
	return out, nil
}

// client is one client{} section: radius_clients' tuple.
type client struct {
	net    cidr.Network
	scope  string
	device string   // "generic" or the vendor the address is tagged with
	send   []string // vendors whose attribute this client gets
}

// clients is radius_clients: one per prefix of a scope RADIUS serves
// ('generic': what the scope enables) and one per tagged address (its own
// vendor alone), most specific first (then by scope). A tagged CIDR that is
// also a prefix of its scope is one client, the tagged one.
func clients(scopes []*model.Scope) ([]client, error) {
	byNet := map[string]client{}
	for _, s := range scopes {
		var enabled []string
		for _, v := range names.KnownVendors {
			if slices.Contains(s.VendorAttrs, v) {
				enabled = append(enabled, v)
			}
		}
		for _, c := range s.Prefixes {
			n, err := netOf(c)
			if err != nil {
				return nil, err
			}
			byNet[n.String()] = client{n, s.Name, "generic", enabled}
		}
	}
	for _, s := range scopes {
		devices := slices.Clone(s.Devices)
		sort.Slice(devices, func(i, j int) bool { return devices[i].CIDR < devices[j].CIDR })
		for _, d := range devices {
			n, err := netOf(d.CIDR)
			if err != nil {
				return nil, err
			}
			byNet[n.String()] = client{n, s.Name, d.Vendor, []string{d.Vendor}}
		}
	}
	out := make([]client, 0, len(byNet))
	for _, c := range byNet {
		out = append(out, c)
	}
	sort.Slice(out, func(i, j int) bool {
		ki, kj := out[i].net.SortKey(), out[j].net.SortKey()
		if ki != kj {
			return ki.Less(kj)
		}
		return out[i].scope < out[j].scope
	})
	return out, nil
}

// renderConf is render_conf_text: main settings, module instances, server
// tacctl.
func renderConf(m *model.Model, merged *yamlpy.Map, p Params) (string, error) {
	scopes := servedScopes(m)
	filt, err := filterPolicy(m.Filters)
	if err != nil {
		return "", err
	}
	var w strings.Builder
	w.WriteString(header)
	w.WriteString("#\n" +
		"# FreeRADIUS main configuration of tacctl's own instance: the unit starts the daemon with\n" +
		"# '-n " + p.Name + "', so the package's radiusd.conf, clients.conf, sites-enabled/ and mods-enabled/\n" +
		"# are not read. PAP only, against the bcrypt hashes of the store.\n" +
		"# render id: " + ridPlaceholder + "\n" +
		"\n" +
		"# The daemon's built-in defaults refer to prefix and localstatedir (without them it passes\n" +
		"# its own check and then fails to start); libdir is where the package keeps the modules.\n" +
		"prefix = /usr\n" +
		"localstatedir = /var\n" +
		"libdir = " + p.LibDir + "\n" +
		"logdir = " + p.LogDir + "\n" +
		"pidfile = " + p.PIDFile + "\n" +
		"max_request_time = 30\n" +
		"cleanup_delay = 5\n" +
		"max_requests = 16384\n" +
		"hostname_lookups = no\n" +
		"proxy_requests = no\n" +
		"\n" +
		"log {\n" +
		"\tdestination = files\n" +
		"\tfile = ${logdir}/tacctl-radius.log\n" +
		"\tauth = no\n" +
		"}\n" +
		"\n" +
		"security {\n" +
		"\tuser = " + p.User + "\n" +
		"\tgroup = " + p.Group + "\n" +
		"\tallow_core_dumps = no\n" +
		"\tmax_attributes = 200\n" +
		"\treject_delay = 1\n" +
		"\tstatus_server = no\n" +
		"}\n" +
		"\n" +
		"thread pool {\n" +
		"\tstart_servers = 5\n" +
		"\tmax_servers = 32\n" +
		"\tmin_spare_servers = 3\n" +
		"\tmax_spare_servers = 10\n" +
		"\tmax_requests_per_server = 0\n" +
		"}\n" +
		"\n" +
		"modules {\n" +
		"\tfiles tacctl_users {\n" +
		"\t\tfilename = ${confdir}/" + p.Name + ".users\n" +
		"\t}\n" +
		"\tpap tacctl_pap {\n" +
		"\t\tnormalise = no\n" +
		"\t}\n" +
		"\talways tacctl_reject {\n" +
		"\t\trcode = reject\n" +
		"\t}\n" +
		"\talways tacctl_drop {\n" +
		"\t\trcode = handled\n" +
		"\t}\n" +
		"\tdetail tacctl_acct {\n" +
		"\t\tfilename = ${logdir}/tacctl-accounting.log\n" +
		"\t\tpermissions = 0640\n" +
		"\t\theader = \"%t\"\n" +
		"\t}\n" +
		"\tlinelog tacctl_auth {\n" +
		"\t\tfilename = ${logdir}/tacctl-auth.log\n" +
		"\t\tpermissions = 0640\n" +
		"\t\tformat = \"%S %{reply:Packet-Type} scope=%{client:tacctl_scope} device=%{client:tacctl_device} " +
		"client=%{%{Packet-Src-IP-Address}:-%{Packet-Src-IPv6-Address}} " +
		"nas=%{%{NAS-Identifier}:-%{%{NAS-IP-Address}:--}} " +
		"reason='%{%{Tmp-String-1}:-%{%{Module-Failure-Message}:--}}' user=%{User-Name}\"\n" +
		"\t}\n" +
		"}\n")
	if filt != "" {
		w.WriteString("\n" +
			"# Connection filters ('tacctl config allow|deny'): no answer for a filtered address.\n" +
			"policy {\n" +
			"\ttacctl_filter {\n" + filt + "\t}\n" +
			"}\n")
	}
	w.WriteString("\nserver tacctl {\n")
	ls, err := listeners(merged)
	if err != nil {
		return "", err
	}
	for _, l := range ls {
		fmt.Fprintf(&w, "\t# listeners.radius.%s\n"+
			"\tlisten {\n"+
			"\t\ttype = %s\n"+
			"\t\t%s = %s\n"+
			"\t\tport = %d\n"+
			"\t}\n", l.name, l.role, l.key, l.host, l.port)
	}
	w.WriteString("\n" +
		"\t# One client per prefix of every scope RADIUS serves, and one per tagged address of a\n" +
		"\t# scope ('tacctl scope devices'). An address in two of them is the client of the longer\n" +
		"\t# prefix (the more specific scope, the tagged address), as with TACACS+.\n" +
		"\t# tacctl_device is 'generic' or the vendor an address is tagged with; tacctl_send_<vendor>\n" +
		"\t# says whether post-auth adds that vendor's attribute for this client.\n")
	secrets := map[string]string{}
	for _, s := range scopes {
		secrets[s.Name] = s.Secret
	}
	cs, err := clients(scopes)
	if err != nil {
		return "", err
	}
	counter := map[string]int{}
	for _, c := range cs {
		secret, ok := FRSecret(secrets[c.scope])
		if !ok {
			return "", errorf("scope '%s': its secret holds both a backslash and a dollar sign, which no FreeRADIUS "+
				"config string can carry unchanged. Set another ('tacctl scope secret %s generate'), or "+
				"keep the scope TACACS+-only ('tacctl scope protocols %s set tacacs').", c.scope, c.scope, c.scope)
		}
		label := c.scope
		if c.device != "generic" {
			label = c.scope + "." + c.device
		}
		counter[label]++
		key := "ipaddr"
		if c.net.IsIPv6() {
			key = "ipv6addr"
		}
		fmt.Fprintf(&w, "\tclient %s.%d {\n"+
			"\t\t%s = %s\n"+
			"\t\tsecret = %s\n"+
			"\t\ttacctl_scope = \"%s\"\n"+
			"\t\ttacctl_device = \"%s\"\n",
			label, counter[label], key, c.net.String(), secret, c.scope, c.device)
		for _, v := range names.KnownVendors {
			yes := "no"
			if slices.Contains(c.send, v) {
				yes = "yes"
			}
			fmt.Fprintf(&w, "\t\ttacctl_send_%s = \"%s\"\n", v, yes)
		}
		w.WriteString("\t}\n")
	}
	// A vendor's attribute is added for a client that says yes, and for no
	// other: no match, no attribute.
	var vendorPolicy strings.Builder
	for _, v := range names.KnownVendors {
		r := vendorReply[v]
		fmt.Fprintf(&vendorPolicy, "\t\t\tif ((\"%%{client:tacctl_send_%s}\" == \"yes\") && &control:%s) {\n"+
			"\t\t\t\tupdate reply {\n"+
			"\t\t\t\t\t&%s := %s\n"+
			"\t\t\t\t}\n"+
			"\t\t\t}\n", v, r.control, r.attr, r.value)
	}
	useFilter := ""
	if filt != "" {
		useFilter = "\t\ttacctl_filter\n"
	}
	w.WriteString("\n" +
		"\tauthorize {\n" + useFilter +
		"\t\tupdate request {\n" +
		"\t\t\t&Tmp-String-0 := \"" + ridPlaceholder + "/%{client:tacctl_scope}\"\n" +
		"\t\t}\n" +
		"\t\ttacctl_users\n" +
		"\t\tif (!ok) {\n" +
		"\t\t\tupdate request {\n" +
		"\t\t\t\t&Tmp-String-1 := \"not an enabled user of this scope\"\n" +
		"\t\t\t}\n" +
		"\t\t\ttacctl_reject\n" +
		"\t\t}\n" +
		"\t\ttacctl_pap\n" +
		"\t}\n" +
		"\tauthenticate {\n" +
		"\t\ttacctl_pap\n" +
		"\t}\n" +
		"\tpost-auth {\n" +
		"\t\t# A filtered packet (tacctl_filter) gets no answer and no line in the auth log.\n" +
		"\t\tif (!&control:Response-Packet-Type) {\n" +
		"\t\t\t# Vendor attributes: only for a client whose scope enables the vendor\n" +
		"\t\t\t# ('tacctl scope vendor-attrs') or whose address is tagged with it\n" +
		"\t\t\t# ('tacctl scope devices'). The values come from the control list.\n" +
		vendorPolicy.String() +
		"\t\t\ttacctl_auth\n" +
		"\t\t}\n" +
		"\t\tPost-Auth-Type REJECT {\n" +
		"\t\t\tupdate reply {\n" +
		"\t\t\t\t&Service-Type !* ANY\n" +
		"\t\t\t\t&Cisco-AVPair !* ANY\n" +
		"\t\t\t\t&Juniper-Local-User-Name !* ANY\n" +
		"\t\t\t\t&WTI-Super !* ANY\n" +
		"\t\t\t}\n" +
		"\t\t\ttacctl_auth\n" +
		"\t\t}\n" +
		"\t}\n" +
		"\tpreacct {\n" + useFilter +
		"\t}\n" +
		"\taccounting {\n" +
		"\t\ttacctl_acct\n" +
		"\t}\n" +
		"}\n")
	return w.String(), nil
}

// renderDictionary is render_dictionary_text: the package's main
// dictionary, the WTI vendor, tacctl's internal attributes. It depends on
// the machine only (where the package keeps its dictionary), not on the
// model.
func renderDictionary(p Params) string {
	width := 0
	for _, a := range internalAttrs {
		width = max(width, len(a.name))
	}
	var w strings.Builder
	w.WriteString("# GENERATED by tacctl. Edits here are overwritten, and there is no way to adopt one.\n" +
		"#\n" +
		"# The main dictionary of tacctl's FreeRADIUS instance: the unit starts the daemon with\n" +
		"# '-D <this directory>', which makes it read this file in place of the package's main\n" +
		"# dictionary. That one is included first, unchanged; no file of the package is edited.\n" +
		"\n" +
		"$INCLUDE " + p.SystemDict + "\n" +
		"\n" +
		"# WTI (Western Telematic Inc.) console servers and power units: the access level of a login.\n" +
		"# Written by tacctl from the numbers WTI publishes; not a copy of WTI's file, which also has\n" +
		"# attributes tacctl does not send and carries no licence statement:\n" +
		"#   https://ftp.wti.com/InfoCenter/rsa/dictionary/dictionary.wti\n" +
		"# The value names are those of the WTI user's guide (the published file has none).\n" +
		"VENDOR\t\tWTI\t\t\t24496\n" +
		"BEGIN-VENDOR\tWTI\n" +
		"ATTRIBUTE\tWTI-Super\t\t41\tinteger\n")
	for i := len(wtiSuperBands) - 1; i >= 0; i-- {
		b := wtiSuperBands[i]
		fmt.Fprintf(&w, "VALUE\t\tWTI-Super\t\t%s\t%d\n", b.label, b.value)
	}
	w.WriteString("END-VENDOR\tWTI\n" +
		"\n" +
		"# tacctl's own attributes. A users entry sets them in the control list and the policy in\n" +
		"# tacctl-radius.conf makes the vendor attributes of a reply from them. They are numbered in\n" +
		"# the range FreeRADIUS reserves for site-local attributes (3000-3999), which it never puts\n" +
		"# into a RADIUS packet.\n")
	for _, a := range internalAttrs {
		fmt.Fprintf(&w, "ATTRIBUTE\t%-*s\t%d\t%s\n", width, a.name, a.number, a.kind)
	}
	return w.String()
}
