package lifecycle_test

// tests/integration/upgrade_store_flip.bats, the upgrade half: the move
// of a legacy install into the store, in the order an upgrade runs it
// (StateMigrate, ConfigSyncExisting, UpgradeStoreFlip). The rollback half
// ('tacctl store rollback') is internal/cli's store_rollback_test.go. The
// gate needs the daemon binary for its load-smoke, so tests that expect a
// flip install a stand-in for it. A stop must leave tacquito.yaml byte for
// byte as it was, create no store, and never restart the daemon.

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/rett/tacctl/internal/backend"
	"github.com/rett/tacctl/internal/lifecycle"
	"github.com/rett/tacctl/internal/model"
	"github.com/rett/tacctl/internal/rendered"
	"github.com/rett/tacctl/internal/store"
	"github.com/rett/tacctl/internal/ui"
)

// assertStopped: the install is in legacy read-only mode and the daemon was
// left alone; before is the sha256 tacquito.yaml had before the gate ran.
func (e *tenv) assertStopped(r lifecycle.FlipResult, before string) {
	e.t.Helper()
	out := e.output()
	if r != lifecycle.FlipStopped || r.Code() != 20 || r.String() != "stopped" {
		e.t.Fatalf("result %v\n%s", r, out)
	}
	has(e.t, out, "Store migration stopped")
	has(e.t, out, "legacy read-only mode")
	if sha(e.t, e.p.Config) != before {
		e.t.Error("tacquito.yaml changed")
	}
	if exists(e.p.StoreFile) || exists(e.p.Rendered) {
		e.t.Error("a store or render record was left")
	}
	if len(e.preStoreFiles()) != 0 {
		e.t.Error("a pre-store copy was left")
	}
	if e.systemctlCalled() {
		e.t.Error("systemctl was called")
	}
}

// --- the gate passes ---

func TestFlipALegacyInstallMovesIntoTheStore(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("serve")
	e.write(e.p.Config, fixture(t, "legacy.fresh-install.yaml"), 0o640)
	e.upgradeSync()
	before := sha(t, e.p.Config)
	r := e.flip()
	out := e.output()
	if r != lifecycle.Flipped || r.Code() != 0 || r.String() != "flipped" {
		t.Fatalf("result %v\n%s", r, out)
	}
	for _, s := range []string{"[INFO] Store migration: " + e.p.StoreFile + " does not exist yet.",
		"    EQUIVALENT", "daemon load-smoke:   OK", "[INFO] Gate passed: writing the store and rendering " + e.p.Config + " from it...",
		"Store migration complete", "tacctl store rollback"} {
		has(t, out, s)
	}
	// The import's own lines are not repeated by the second, quiet import.
	if strings.Count(out, "Store written to") != 0 {
		t.Error("the import after the check was not quiet")
	}
	if mode(t, e.p.StoreFile) != 0o600 || mode(t, e.p.Config) != 0o640 {
		t.Error("modes")
	}
	if !strings.Contains(strings.SplitN(e.read(e.p.Config), "\n", 2)[0], "GENERATED by tacctl") {
		t.Error("not rendered")
	}
	if w, _ := rendered.Check(e.p.Rendered, e.p.Config); w != rendered.OK {
		t.Errorf("rendered check %q", w)
	}
	// Exactly one copy of the pre-flip file, byte-identical, 0600, named as
	// the plan says, and no second 'drift' copy from the forced render.
	pre := e.preStoreFiles()
	if len(pre) != 1 || !regexp.MustCompile(`/tacquito\.yaml\.pre-store\.[0-9]{8}_[0-9]{6}$`).MatchString(pre[0]) {
		t.Fatalf("pre-store copies %v", pre)
	}
	if sha(t, pre[0]) != before || mode(t, pre[0]) != 0o600 || len(e.legacyFiles()) != 1 {
		t.Error("pre-store copy")
	}
	// What the daemon is given is equivalent to what it had.
	var b bytes.Buffer
	if eq, err := model.EquivCheck(pre[0], e.p.Config, &b); err != nil || !eq || strings.TrimSpace(b.String()) != "EQUIVALENT" {
		t.Errorf("%v %v %q", eq, err, b.String())
	}
	// The gate does not restart; the upgrade does, once, after it.
	if e.systemctlCalled() {
		t.Error("systemctl was called")
	}
}

func TestFlipAfterwardsTheInstallIsFullyWorking(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("serve")
	e.write(e.p.Config, fixture(t, "legacy.fresh-install.yaml"), 0o640)
	e.upgradeSync()
	if r := e.flip(); r != lifecycle.Flipped {
		t.Fatal(r)
	}
	if lines := e.set.DriftLines(backend.DriftSelection{}); len(lines) != 0 {
		t.Error(lines)
	}
	e.reset()
	e.userAdd("alice")
	// Nothing left to adopt: the flip already rendered and recorded the file.
	hasNot(t, e.output(), "Previous")
	if !strings.Contains(e.read(e.p.Config), "name: alice") || !e.run.Called("systemctl", "restart", "tacquito") {
		t.Error("the mutation did not apply")
	}
}

func TestFlipTheGateJudgesTheFileAsTheMigrationsLeaveIt(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("serve")
	e.placeFixture("tacquito.legacy-exec.yaml")
	// As it stands the file does not pass: it names the Cisco service
	// 'exec' and carries no command rules.
	if r := e.flip(); r != lifecycle.FlipStopped {
		t.Fatal(r)
	}
	has(t, e.output(), "the check above did not pass")
	e.upgradeSync()
	if r := e.flip(); r != lifecycle.Flipped {
		t.Fatalf("%v\n%s", r, e.output())
	}
	// The kept file is the migrated one, i.e. what the daemon was running.
	if pre := e.preStoreFiles(); len(pre) != 1 || !strings.Contains(e.read(pre[0]), "name: shell") {
		t.Error(pre)
	}
}

// --- the gate stops ---

func TestFlipStopsOnContentTheStoreCannotRepresent(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("serve")
	e.placeFixture("legacy.unrepresentable.yaml")
	e.upgradeSync()
	before := sha(t, e.p.Config)
	e.assertStopped(e.flip(), before)
	out := e.output()
	has(t, out, "Cannot be represented in the store")
	has(t, out, "the check above did not pass")
	has(t, out, "tacctl store import --check")
	hasNot(t, out, "Dropped (--force)")
	// The whole report, as 0.1.16 words it.
	has(t, out, "\n[WARN] Store migration stopped: the check above did not pass.\n"+
		"[WARN] "+e.p.Config+" and the running daemon were left as they are.\n"+
		"[WARN] tacctl stays in legacy read-only mode: read commands work; commands that change users, groups, scopes or filters are refused.\n"+
		"[WARN] To proceed: 'tacctl store import --check' prints the report again. Fix what it lists in "+e.p.Config+" and run 'tacctl upgrade' again,\n"+
		"[WARN] or accept the difference yourself: 'tacctl store import' (--force drops what the store cannot hold), then 'tacctl config render --force'.\n\n")
	// Reads still work from the legacy file.
	_, m, mode, err := model.Load(model.Paths{Store: e.p.StoreFile, Config: e.p.Config})
	if err != nil || mode != "legacy" {
		t.Fatal(mode, err)
	}
	found := false
	for _, u := range m.Users {
		found = found || u.Name == "mallory"
	}
	if !found {
		t.Error("mallory not read")
	}
}

func TestFlipStopsOnACleanImportThatIsNotEquivalent(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("serve")
	e.placeFixture("tacquito.multiscope.yaml")
	e.upgradeSync()
	before := sha(t, e.p.Config)
	e.assertStopped(e.flip(), before)
	out := e.output()
	has(t, out, "import + validate:   OK")
	has(t, out, "NOT EQUIVALENT")
	has(t, out, "the check above did not pass")
}

func TestFlipStopsWhenTheDaemonDoesNotLoadTheRender(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("fatal")
	e.write(e.p.Config, fixture(t, "legacy.fresh-install.yaml"), 0o640)
	e.upgradeSync()
	before := sha(t, e.p.Config)
	e.assertStopped(e.flip(), before)
	has(t, e.output(), "    EQUIVALENT")
	has(t, e.output(), "daemon load-smoke:   FAILED")
}

func TestFlipStopsWithoutTheDaemonBinary(t *testing.T) {
	e := newTenv(t)
	e.write(e.p.Config, fixture(t, "legacy.fresh-install.yaml"), 0o640)
	e.upgradeSync()
	before := sha(t, e.p.Config)
	e.assertStopped(e.flip(), before)
	has(t, e.output(), "Store migration stopped: the daemon load-smoke cannot run ("+filepath.Join(e.p.Bin, "tacquito")+
		" or 'timeout' is missing), so the rendered config cannot be proven to load.")
	if len(e.run.Calls()) != 0 {
		t.Error(e.run.Argvs())
	}
}

func TestFlipStopsWhenEquivalenceIsNotProven(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("serve")
	e.write(e.p.Config, fixture(t, "legacy.fresh-install.yaml"), 0o640)
	e.upgradeSync()
	before := sha(t, e.p.Config)
	e.env.ImportRender = func(*store.Store) ([]byte, error) { return nil, store.ErrNoRenderer }
	e.assertStopped(e.flip(), before)
	has(t, e.output(), "the import is clean but its equivalence with "+e.p.Config+" was not proven")
}

func TestFlipStopsWithoutATacquitoYAML(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("serve")
	e.upgradeSync()
	if r := e.flip(); r != lifecycle.FlipStopped {
		t.Fatal(r)
	}
	if exists(e.p.StoreFile) || exists(e.p.Config) {
		t.Error("files made")
	}
	has(t, e.output(), "there is no "+e.p.Config+" to import")
}

func TestFlipARenderThatFailsTakesTheStoreAwayAgain(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("serve")
	e.write(e.p.Config, fixture(t, "legacy.fresh-install.yaml"), 0o640)
	e.upgradeSync()
	before := sha(t, e.p.Config)
	e.env.RenderApply = func(context.Context, bool) (bool, error) { return false, backend.ErrFailed }
	r := e.flip()
	if r != lifecycle.FlipStopped || sha(t, e.p.Config) != before || exists(e.p.StoreFile) || exists(e.p.Rendered) {
		t.Fatalf("%v\n%s", r, e.output())
	}
	has(t, e.output(), "could not be rendered from the store (the store was removed again)")
	if e.systemctlCalled() {
		t.Error("systemctl")
	}
}

func TestFlipARenderThatIsNotEquivalentPutsTheOldFileBack(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("serve")
	e.write(e.p.Config, fixture(t, "legacy.fresh-install.yaml"), 0o640)
	e.upgradeSync()
	before := sha(t, e.p.Config)
	// A render that installs something else (the daemon would see other users).
	e.env.RenderApply = func(context.Context, bool) (bool, error) {
		return true, os.WriteFile(e.p.Config, []byte(fixture(t, "tacquito.minimal.yaml")), 0o640)
	}
	r := e.flip()
	if r != lifecycle.FlipStopped || sha(t, e.p.Config) != before || exists(e.p.StoreFile) {
		t.Fatalf("%v\n%s", r, e.output())
	}
	has(t, e.output(), "the rendered "+e.p.Config+" was not equivalent to the file it replaced (that file is back and the store was removed again)")
	if mode(t, e.p.Config) != 0o640 || exists(e.p.Config+".tacctl-new") {
		t.Error("the file put back")
	}
}

// --- re-runs ---

func TestFlipAStoreThatExistsIsNeverReimported(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("serve")
	e.loadFixture("tacquito.minimal.yaml")
	e.userAdd("alice")
	e.reset()
	storeBefore, configBefore := sha(t, e.p.StoreFile), sha(t, e.p.Config)
	if e.upgradeSync() {
		t.Error("sync asked for a restart")
	}
	if r := e.flip(); r != lifecycle.StorePresent || r.Code() != 10 || r.String() != "present" {
		t.Fatal(r)
	}
	if e.output() != "" {
		t.Errorf("output %q", e.output())
	}
	if sha(t, e.p.StoreFile) != storeBefore || sha(t, e.p.Config) != configBefore || len(e.preStoreFiles()) != 0 {
		t.Error("changed")
	}
}

// treeSums is every file under etc and state with its sha256 (the lock
// file left out).
func (e *tenv) treeSums() string {
	var b strings.Builder
	for _, root := range []string{e.p.Etc, e.p.StateDir} {
		_ = filepath.Walk(root, func(p string, fi os.FileInfo, err error) error {
			if err == nil && fi.Mode().IsRegular() && fi.Name() != ".store.lock" {
				b.WriteString(p + " " + sha(e.t, p) + "\n")
			}
			return nil
		})
	}
	return b.String()
}

func TestFlipASecondUpgradeAfterAFlipChangesNothing(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("serve")
	e.write(e.p.Config, fixture(t, "legacy.fresh-install.yaml"), 0o640)
	e.upgradeSync()
	if r := e.flip(); r != lifecycle.Flipped {
		t.Fatal(r)
	}
	before := e.treeSums()
	e.reset()
	if e.upgradeSync() || e.output() != "" {
		t.Errorf("sync: %q", e.output())
	}
	if r := e.flip(); r != lifecycle.StorePresent {
		t.Fatal(r)
	}
	if e.treeSums() != before {
		t.Error("tree changed")
	}
}

func TestFlipAStoppedUpgradeStopsAgainAndPassesOnceTheCauseIsGone(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("fatal")
	e.write(e.p.Config, fixture(t, "legacy.fresh-install.yaml"), 0o640)
	e.upgradeSync()
	before := sha(t, e.p.Config)
	if r := e.flip(); r != lifecycle.FlipStopped {
		t.Fatal(r)
	}
	e.upgradeSync()
	e.assertStopped(e.flip(), before)
	e.fakeTacquito("serve") // a later rule wins
	e.upgradeSync()
	if r := e.flip(); r != lifecycle.Flipped {
		t.Fatalf("%v\n%s", r, e.output())
	}
	if pre := e.preStoreFiles(); len(pre) != 1 || sha(t, pre[0]) != before {
		t.Error(pre)
	}
}

func TestFlipAnInterruptedUpgradeIsFinishedByTheNextOne(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("serve")
	e.write(e.p.Config, fixture(t, "legacy.fresh-install.yaml"), 0o640)
	e.upgradeSync()
	before := sha(t, e.p.Config)
	// The state such an interruption leaves (also what a manual 'tacctl
	// store import' leaves): store written, legacy file still live.
	e.storeImport()
	if !exists(e.p.StoreFile) || exists(e.p.Rendered) || sha(t, e.p.Config) != before {
		t.Fatal("setup")
	}
	e.reset()
	changed, err := lifecycle.ConfigSyncExisting(ctx, e.env, lifecycle.SyncOptions{})
	if err != nil || !changed {
		t.Fatal(changed, err)
	}
	has(t, e.output(), "[INFO] "+e.p.Config+" is equivalent to what the store renders; replacing it with the rendered file.")
	hasNot(t, e.output(), "ERROR")
	// The first sync that renders asks for a restart; the next does not.
	if changed, _ := lifecycle.ConfigSyncExisting(ctx, e.env, lifecycle.SyncOptions{}); changed {
		t.Error("second sync changed")
	}
	if w, _ := rendered.Check(e.p.Rendered, e.p.Config); w != rendered.OK {
		t.Error(w)
	}
	if !strings.Contains(strings.SplitN(e.read(e.p.Config), "\n", 2)[0], "GENERATED by tacctl") {
		t.Error("not rendered")
	}
	// The interrupted run's pre-store copy is the only copy.
	if pre := e.preStoreFiles(); len(pre) != 1 || sha(t, pre[0]) != before || len(e.legacyFiles()) != 1 {
		t.Error(e.legacyFiles())
	}
	if r := e.flip(); r != lifecycle.StorePresent {
		t.Fatal(r)
	}
}

func TestFlipALegacyMigrationThatChangesTheFileAsksForARestart(t *testing.T) {
	e := newTenv(t)
	e.placeFixture("tacquito.legacy-exec.yaml")
	if !e.upgradeSync() {
		t.Error("first sync did not ask for a restart")
	}
	if e.upgradeSync() {
		t.Error("second sync asked for a restart")
	}
}

func TestFlipTheExecServiceNameMigrationAloneAsksForARestart(t *testing.T) {
	e := newTenv(t)
	e.placeFixture("tacquito.legacy-exec.yaml")
	e.upgradeSync()
	// The commands: blocks are current now; only the service name goes back.
	back := regexp.MustCompile(`(?m)^(exec_\w+: &exec_\w+\n  name: )shell$`).ReplaceAllString(e.read(e.p.Config), "${1}exec")
	e.write(e.p.Config, back, 0o640)
	if !regexp.MustCompile(`(?m)^  name: exec$`).MatchString(e.read(e.p.Config)) {
		t.Fatal("setup")
	}
	if !e.upgradeSync() {
		t.Error("no restart asked")
	}
	if regexp.MustCompile(`(?m)^  name: exec$`).MatchString(e.read(e.p.Config)) {
		t.Error("not migrated")
	}
	if e.upgradeSync() {
		t.Error("second sync asked for a restart")
	}
}

func TestFlipAStoreBesideADifferentNeverRenderedConfigLeavesItAlone(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("serve")
	e.placeFixture("tacquito.multiscope.yaml")
	e.upgradeSync()
	// Operator's own decision: import although the check does not pass.
	e.storeImport()
	before := sha(t, e.p.Config)
	e.reset()
	if changed, err := lifecycle.ConfigSyncExisting(ctx, e.env, lifecycle.SyncOptions{}); changed || err != nil {
		t.Fatal(changed, err)
	}
	has(t, e.output(), "[WARN] "+e.p.Config+" was not rendered by tacctl, and what the store renders is not proven equivalent to it; it was left as it is.\n"+
		"[WARN] To keep what the file says: 'tacctl store import --replace', then 'tacctl config render --force'.\n"+
		"[WARN] To replace it with the store's content: 'tacctl config render --force'.\n")
	if sha(t, e.p.Config) != before || exists(e.p.Rendered) {
		t.Error("changed")
	}
}

func TestFlipAnEquivalentNeverRenderedConfigIsNotAdoptedWhileTheDaemonCannotLoadIt(t *testing.T) {
	e := newTenv(t)
	e.write(e.p.Config, fixture(t, "legacy.fresh-install.yaml"), 0o640)
	e.upgradeSync()
	e.storeImport()
	before := sha(t, e.p.Config)
	e.reset()
	// No daemon binary: the load-smoke cannot run.
	_, _ = lifecycle.ConfigSyncExisting(ctx, e.env, lifecycle.SyncOptions{})
	has(t, e.output(), "it was left as it is")
	e.fakeTacquito("fatal")
	e.reset()
	_, _ = lifecycle.ConfigSyncExisting(ctx, e.env, lifecycle.SyncOptions{})
	has(t, e.output(), "it was left as it is")
	has(t, e.output(), "Load-smoke: tacquito could not parse the config.")
	if sha(t, e.p.Config) != before || exists(e.p.Rendered) {
		t.Error("changed")
	}
}

func TestFlipAHandEditedRenderedConfigIsReportedAndLeftAlone(t *testing.T) {
	e := newTenv(t)
	e.fakeTacquito("serve")
	e.write(e.p.Config, fixture(t, "legacy.fresh-install.yaml"), 0o640)
	e.upgradeSync()
	if r := e.flip(); r != lifecycle.Flipped {
		t.Fatal(r)
	}
	f, _ := os.OpenFile(e.p.Config, os.O_APPEND|os.O_WRONLY, 0)
	_, _ = f.WriteString("# hand edit\n")
	_ = f.Close()
	before := sha(t, e.p.Config)
	e.reset()
	if changed, err := lifecycle.ConfigSyncExisting(ctx, e.env, lifecycle.SyncOptions{}); changed || err != nil {
		t.Fatal(changed, err)
	}
	has(t, e.output(), "was edited since tacctl rendered it")
	has(t, e.output(), "[WARN] tacquito.yaml was not re-rendered; run 'tacctl config render' once the problem above is fixed.")
	if sha(t, e.p.Config) != before {
		t.Error("overwritten")
	}
}

// --- the pieces ---

func TestFlipHintOnlyAfterAFlip(t *testing.T) {
	var b bytes.Buffer
	out := ui.Output{Stdout: &b, Stderr: &b}
	lifecycle.FlipHint(out, "/etc/tacquito/tacquito.yaml", lifecycle.StorePresent)
	lifecycle.FlipHint(out, "/etc/tacquito/tacquito.yaml", lifecycle.FlipStopped)
	if b.Len() != 0 {
		t.Error(b.String())
	}
	lifecycle.FlipHint(out, "/etc/tacquito/tacquito.yaml", lifecycle.Flipped)
	if plain(b.String()) != "[ERROR] This upgrade moved the configuration into the store. If the rendered /etc/tacquito/tacquito.yaml is the cause, 'tacctl store rollback' restores the previous file.\n" {
		t.Errorf("%q", b.String())
	}
}

func TestStoreUnflipPutsThePreStoreFileBackAndRemovesTheStore(t *testing.T) {
	e := newTenv(t)
	e.loadFixture("tacquito.minimal.yaml")
	pre := filepath.Join(e.p.BackupDir, "legacy", "tacquito.yaml.pre-store.20200101_000000")
	e.write(pre, fixture(t, "legacy.fresh-install.yaml"), 0o600)
	e.write(e.p.Rendered, "{}\n", 0o600)
	if err := lifecycle.StoreUnflip(e.env, pre); err != nil {
		t.Fatal(err)
	}
	if sha(t, e.p.Config) != sha(t, pre) || mode(t, e.p.Config) != 0o640 || exists(e.p.StoreFile) || exists(e.p.Rendered) ||
		exists(e.p.Config+".tacctl-new") {
		t.Error("state after unflip")
	}
	// Already the same bytes: the file is left as it is (same inode).
	st1, _ := os.Stat(e.p.Config)
	e.write(e.p.StoreFile, "x\n", 0o600)
	if err := lifecycle.StoreUnflip(e.env, pre); err != nil {
		t.Fatal(err)
	}
	st2, _ := os.Stat(e.p.Config)
	if !os.SameFile(st1, st2) || exists(e.p.StoreFile) {
		t.Error("rewritten")
	}
	// A pre-store file that cannot be read: nothing is removed.
	e.write(e.p.StoreFile, "x\n", 0o600)
	if err := lifecycle.StoreUnflip(e.env, filepath.Join(e.w, "missing")); err == nil || !exists(e.p.StoreFile) {
		t.Error("store removed although the config was not replaced")
	}
}

func TestConfigServiceAccessOnlyAsRoot(t *testing.T) {
	e := newTenv(t)
	e.write(e.p.Config, "x\n", 0o600)
	if err := lifecycle.ConfigServiceAccess(e.env); err != nil || mode(t, e.p.Config) != 0o600 {
		t.Error("touched when not root")
	}
}
