package lifecycle_test

// tests/e2e/install_seed.bats, the seeding half: what 'tacctl install'
// does to the configuration (InstallSeed). The README and uninstall tests
// of that file are the orchestration's (WP3.3d).

import (
	"bytes"
	"encoding/hex"
	"errors"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/rett/tacctl/internal/backend"
	"github.com/rett/tacctl/internal/lifecycle"
	"github.com/rett/tacctl/internal/model"
)

const secret = "0123456789abcdef0123456789abcdef"

// newSeedEnv is install_seed.bats' setup: a fresh machine (no state
// directory, an empty config directory), the random source answering
// $SECRET as 'openssl rand -hex 16' did.
func newSeedEnv(t *testing.T) *tenv {
	t.Helper()
	e := newTenv(t)
	if err := os.RemoveAll(e.p.StateDir); err != nil {
		t.Fatal(err)
	}
	raw, _ := hex.DecodeString(secret)
	e.env.Rand = bytes.NewReader(raw)
	return e
}

// freshInstall is what cmd_install runs, in its order, up to the point
// the service starts: StateMigrate, then InstallSeed.
func (e *tenv) freshInstall() (lifecycle.SeedResult, error) {
	e.t.Helper()
	if err := lifecycle.StateMigrate(lifecycle.StateOptionsFrom(e.p, e.be.Out, nil, false)); err != nil {
		e.t.Fatal(err)
	}
	e.be.Conf.Reload()
	return lifecycle.InstallSeed(ctx, e.env)
}

func (e *tenv) mustFreshInstall() lifecycle.SeedResult {
	e.t.Helper()
	r, err := e.freshInstall()
	if err != nil {
		e.t.Fatalf("install: %v\n%s", err, e.output())
	}
	return r
}

func TestSeedAFreshInstallSeedsTheStoreAndRendersTacquitoYAML(t *testing.T) {
	e := newSeedEnv(t)
	r := e.mustFreshInstall()
	out := e.output()
	has(t, out, "[INFO] Seeding the store at "+e.p.StoreFile+"...\n")
	has(t, out, "[INFO] Default scope seeded: lab (new users land here unless --scopes given)\n")
	has(t, out, "[INFO] Writing configuration to "+e.p.Config+", "+filepath.Join(e.p.OverrideDir, "tacctl.conf")+"...\n")
	has(t, out, "[INFO] Built-in users seeded (disabled — set a password to activate):\n"+
		"[INFO]   engineer (superuser) — disabled\n"+
		"[INFO]   operator (operator)  — disabled\n"+
		"[INFO]   viewer   (readonly)  — disabled\n"+
		"[INFO]   root     (readonly)  — disabled (accounting sink for Junos internal daemons)\n")
	// The secret is shown once, by the summary, not by the progress lines.
	hasNot(t, out, secret)
	// ...and is handed to the caller with the mode.
	if r.Mode != lifecycle.SeedFresh || r.Secret != secret {
		t.Errorf("%+v", r)
	}
	for p, m := range map[string]os.FileMode{e.p.StateDir: 0o700, e.p.StoreFile: 0o600, e.p.Config: 0o640,
		e.p.Rendered: 0o600, e.p.BackupDir: 0o750, e.p.PWDatesDir: 0o750, filepath.Join(e.p.BackupDir, "disabled"): 0o700} {
		if got := mode(t, p); got != m {
			t.Errorf("%s: %v, want %v", p, got, m)
		}
	}
	if !strings.Contains(strings.SplitN(e.read(e.p.Config), "\n", 2)[0], "GENERATED by tacctl") {
		t.Error("not rendered")
	}
	// Nothing to adopt and nothing displaced on a fresh machine.
	if exists(filepath.Join(e.p.BackupDir, "legacy")) || exists(e.p.Overrides) {
		t.Error("legacy dir or tacctl.yaml made")
	}
	if e.systemctlCalled() {
		t.Error("systemctl")
	}
}

func TestSeedTheStoreHoldsTheBuiltinsTheSeedUsersAndScopeLab(t *testing.T) {
	e := newSeedEnv(t)
	e.mustFreshInstall()
	_, m, err := model.LoadStore(e.p.StoreFile)
	if err != nil {
		t.Fatal(err)
	}
	groups := map[string]string{}
	for _, g := range m.Groups {
		groups[g.Name] = g.JuniperClass
		if !g.Builtin || g.PrivLvl == nil {
			t.Errorf("group %+v", g)
		}
	}
	if len(groups) != 3 || groups["readonly"] != "RO-CLASS" || groups["operator"] != "OP-CLASS" || groups["superuser"] != "RW-CLASS" {
		t.Error(groups)
	}
	want := map[string]string{"engineer": "superuser", "operator": "operator", "viewer": "readonly", "root": "readonly"}
	if len(m.Users) != len(want) {
		t.Error(len(m.Users))
	}
	for _, u := range m.Users {
		if want[u.Name] != u.Group || strings.Join(u.Scopes, ",") != "lab" || u.Hash != "" || !u.Disabled ||
			u.AccountingSink != (u.Name == "root") {
			t.Errorf("user %+v", u)
		}
	}
	if len(m.Scopes) != 1 || m.Scopes[0].Name != "lab" || m.Scopes[0].Secret != secret ||
		strings.Join(m.Scopes[0].Prefixes, ",") != lifecycle.InstallScopePrefixes {
		t.Errorf("scopes %+v", m.Scopes[0])
	}
	if len(m.Filters.Allow)+len(m.Filters.Deny) != 0 {
		t.Error(m.Filters)
	}
	if v, _ := e.be.Conf.Get("scope.default", ""); v != lifecycle.DefaultScopeFresh {
		t.Error(v)
	}
}

// section is sed -n '/^# --- <name> ---/,/^# --- /p'.
func section(text, name string) string {
	re := regexp.MustCompile(`(?ms)^# --- ` + regexp.QuoteMeta(name) + ` ---\n.*?^# --- [^\n]*\n`)
	return re.FindString(text)
}

func TestSeedTheOldInstallersOutputStillMatchesTheShippedTemplate(t *testing.T) {
	tmpl, err := os.ReadFile(filepath.Join("..", "..", "config", "backends", "tacacs", "tacquito.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	fx := fixture(t, "legacy.fresh-install.yaml")
	for _, s := range []string{"Type constants", "Accounting", "Services"} {
		if a, b := section(string(tmpl), s), section(fx, s); a == "" || a != b {
			t.Errorf("section %s differs", s)
		}
	}
}

func TestSeedWhatTheDaemonLoadsIsEquivalentToTheOldTemplatePath(t *testing.T) {
	e := newSeedEnv(t)
	e.mustFreshInstall()
	var b bytes.Buffer
	eq, err := model.EquivCheck(filepath.Join(fixDir, "legacy.fresh-install.yaml"), e.p.Config, &b)
	if err != nil || !eq || strings.TrimSpace(b.String()) != "EQUIVALENT" {
		t.Errorf("%v %v %q", eq, err, b.String())
	}
}

func TestSeedTheSeededStoreIsWhatImportingTheOldFileGives(t *testing.T) {
	e := newSeedEnv(t)
	e.mustFreshInstall()
	seeded, rendered := e.read(e.p.StoreFile), e.read(e.p.Config)
	_ = os.Remove(e.p.StoreFile)
	_ = os.Remove(e.p.Rendered)
	e.write(e.p.Config, fixture(t, "legacy.fresh-install.yaml"), 0o640)
	// The old file passes the upgrade gate as it stands, imports to the same
	// store, and renders to the same file.
	e.fakeTacquito("serve")
	if r := e.flip(); r != lifecycle.Flipped {
		t.Fatalf("%v\n%s", r, e.output())
	}
	has(t, e.output(), "    EQUIVALENT")
	if e.read(e.p.StoreFile) != seeded || e.read(e.p.Config) != rendered {
		t.Error("not the same store or render")
	}
}

func TestSeedAFreshInstallIsFullyWorking(t *testing.T) {
	e := newSeedEnv(t)
	e.mustFreshInstall()
	if lines := e.set.DriftLines(backend.DriftSelection{}); len(lines) != 0 {
		t.Error(lines)
	}
	if w, err := e.b.RenderCheck(ctx); err != nil || w != "current" {
		t.Errorf("render check %q %v", w, err)
	}
	// First mutation: nothing to adopt, nothing refused, the daemon restarts.
	e.reset()
	e.userAdd("alice")
	hasNot(t, e.output(), "Previous")
	if !e.run.Called("systemctl", "restart", "tacquito") {
		t.Error("no restart")
	}
	if w, _ := e.b.RenderCheck(ctx); w != "current" {
		t.Error(w)
	}
}

func TestSeedTheSecretIsTheOneTheRenderedConfigCarries(t *testing.T) {
	e := newSeedEnv(t)
	e.mustFreshInstall()
	cfg := e.read(e.p.Config)
	keys := regexp.MustCompile(`(?m)^      key: "([^"]*)"$`).FindAllStringSubmatch(cfg, -1)
	if len(keys) != 3 {
		t.Fatal(keys)
	}
	for _, k := range keys {
		if k[1] != secret {
			t.Error(k[1])
		}
	}
	for _, p := range strings.Split(lifecycle.InstallScopePrefixes, ",") {
		has(t, cfg, `"`+p+`"`)
	}
}

type failReader struct{}

func (failReader) Read([]byte) (int, error) { return 0, errors.New("no entropy") }

func TestSeedASecretThatCannotBeGeneratedStopsBeforeAnythingIsWritten(t *testing.T) {
	e := newSeedEnv(t)
	e.env.Rand = failReader{}
	if _, err := e.freshInstall(); err == nil {
		t.Fatal("no error")
	}
	has(t, e.output(), "[ERROR] Could not generate a shared secret (openssl rand failed).")
	if exists(e.p.StoreFile) || exists(e.p.Config) {
		t.Error("written")
	}
}

func TestSeedAnExistingStoreIsKept(t *testing.T) {
	e := newSeedEnv(t)
	e.mustFreshInstall()
	e.userAdd("alice")
	storeBefore, configBefore := sha(t, e.p.StoreFile), sha(t, e.p.Config)
	e.reset()
	e.wired.phases = nil
	r := e.mustFreshInstall()
	has(t, e.output(), "[INFO] Existing store found at "+e.p.StoreFile+": its users, groups and scopes are kept (no new shared secret).")
	if r.Mode != lifecycle.SeedStore || r.Secret != "" {
		t.Errorf("%+v", r)
	}
	if sha(t, e.p.StoreFile) != storeBefore || sha(t, e.p.Config) != configBefore {
		t.Error("changed")
	}
	// The enabled backends' 'upgrade config' phase ran (and found nothing to do).
	if len(e.wired.phases) != 1 || e.wired.phases[0] != backend.PhaseConfig || e.wired.synced {
		t.Error(e.wired.phases, e.wired.synced)
	}
}

func TestSeedAnExistingStoreWhoseRenderedConfigIsGoneGetsItBack(t *testing.T) {
	e := newSeedEnv(t)
	e.mustFreshInstall()
	before := sha(t, e.p.Config)
	_ = os.Remove(e.p.Config)
	if r := e.mustFreshInstall(); r.Mode != lifecycle.SeedStore {
		t.Error(r)
	}
	if sha(t, e.p.Config) != before || !e.wired.synced {
		t.Error("not rendered again")
	}
}

func TestSeedAnExistingLegacyConfigGoesThroughTheUpgradeGate(t *testing.T) {
	e := newSeedEnv(t)
	e.fakeTacquito("serve")
	e.write(e.p.Config, fixture(t, filepath.Join("golden", "tacquito.multiscope.rendered.yaml")), 0o640)
	r := e.mustFreshInstall()
	has(t, e.output(), "[INFO] Existing "+e.p.Config+" found: it is kept, not replaced by a fresh configuration.")
	has(t, e.output(), "Store migration complete")
	if r.Mode != lifecycle.SeedFlipped || r.Secret != "" {
		t.Errorf("%+v", r)
	}
	// The users of the existing install, not the seed users.
	_, m, err := model.LoadStore(e.p.StoreFile)
	if err != nil {
		t.Fatal(err)
	}
	var names []string
	for _, u := range m.Users {
		names = append(names, u.Name)
	}
	if j := strings.Join(names, " "); !strings.Contains(j, "alice") || strings.Contains(j, "engineer") {
		t.Error(j)
	}
}

func TestSeedAnExistingLegacyConfigTheGateStopsOnIsLeftAsItIs(t *testing.T) {
	e := newSeedEnv(t)
	e.fakeTacquito("serve")
	e.placeFixture("legacy.unrepresentable.yaml")
	r := e.mustFreshInstall()
	if r.Mode != lifecycle.SeedLegacy || r.Secret != "" || exists(e.p.StoreFile) {
		t.Errorf("%+v", r)
	}
	// Byte-identical to the file after the legacy migrations alone.
	after := sha(t, e.p.Config)
	if _, err := lifecycle.ConfigSyncExisting(ctx, e.env, lifecycle.SyncOptions{}); err != nil {
		t.Fatal(err)
	}
	if sha(t, e.p.Config) != after || !strings.Contains(e.read(e.p.Config), "custom_setting") {
		t.Error("changed")
	}
}

func TestSeedARenderThatFailsStopsTheInstall(t *testing.T) {
	e := newSeedEnv(t)
	// A tacctl.yaml adopted from elsewhere enables a backend this tacctl
	// does not have: the store is seeded, the render refuses.
	e.write(e.p.Overrides, "backends:\n  enabled: [ldap]\n", 0o640)
	if _, err := e.freshInstall(); err == nil {
		t.Fatal("no error")
	}
	has(t, e.output(), "tacctl.yaml: backends.enabled names 'ldap'")
	has(t, e.output(), "[ERROR] Could not render  from the store.")
	if !exists(e.p.StoreFile) || exists(e.p.Config) {
		t.Error("files")
	}
}
