#!/usr/bin/env bash
# usage-goldens.sh [--against <tag>] [<out dir>]
#
# Writes the usage blocks of the bash implementation, as the CLI prints them,
# into <out dir> (default internal/cli/testdata/usage): one <name>.out per
# block (stdout, byte for byte) and a cases.tsv of name, exit code and argv.
# internal/cli/help_test.go compares the Go copies of these blocks
# (internal/cli/help.go) with the files.
#
# The bash side is always a tag (default 0.1.16, the parity baseline), taken
# with 'git archive' into a temp dir, so the result does not depend on the
# working tree. It runs with the test harness's sandboxed TACCTL_* paths and
# the minimal fixture; nothing outside the temp dir is touched. The temp state
# directory is written as /etc/tacctl in the output. Needs what the bash
# implementation needs (python3 with yaml and bcrypt).
set -euo pipefail

tag="0.1.16"
if [[ "${1:-}" == "--against" ]]; then
    tag="${2:?--against needs a tag}"
    shift 2
fi
src="$(cd "$(dirname "$(readlink -f "$0")")/../.." && pwd)"
out="${1:-${src}/internal/cli/testdata/usage}"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
mkdir -p "$work/tree"
git -C "$src" archive "$tag" | tar -x -C "$work/tree"
bash_impl="$work/tree/bin/tacctl.sh"

t="$work/state-root"
export TACCTL_ETC="$t/etc" TACCTL_STATE_DIR="$t/state" TACCTL_LOG="$t/log"
export TACCTL_BIN="$t/bin" TACCTL_CONFIG="$t/etc/tacquito.yaml"
export TACCTL_OVERRIDE_DIR="$t/systemd-dropin" TACCTL_SYSTEMD_DIR="$t"
export TACCTL_SUDOERS_FILE="$t/sudoers.d/tacctl" TACCTL_TIER_SUDOERS_FILE="$t/sudoers.d/tacctl-tiers"
export TACCTL_RADIUS_DIR="$t/raddb" TACCTL_RADIUS_LOG="$t/radius-log"
export TACCTL_RADIUS_BIN="$t/radius-bin/radiusd" TACCTL_RADIUS_DICT="$t/radius-share/dictionary"
export TACCTL_LOGROTATE_DIR="$t/logrotate.d" TACCTL_LINUX_DIR="$t/linux"
export TACCTL_SKIP_SUDO=1 TACCTL_SETTLE_SECONDS=0
mkdir -p "$t/etc" "$t/log" "$t/bin" "$t/state/backups/password-dates" "$t/radius-share"
: > "$TACCTL_RADIUS_DICT"
"$bash_impl" store import "$src/tests/fixtures/tacquito.minimal.yaml" > /dev/null
"$bash_impl" config render > /dev/null

# name|argv (words split on spaces; the empty argv is the top-level usage)
cases=(
    "top|"
    "user|user"
    "group|group"
    "group-commands|group commands"
    "group-privilege|group privilege"
    "scope|scope"
    "scope-prefixes|scope prefixes lab help"
    "scope-secret|scope secret lab help"
    "scope-mgmt-acl|scope mgmt-acl lab help"
    "config|config"
    "config-allow|config allow help"
    "config-deny|config deny help"
    "config-mgmt-acl|config mgmt-acl help"
    "config-linux|config linux"
    "host|host"
    "backend|backend"
    "store|store"
    "log|log"
    "backup|backup"
    "hash|hash"
)

mkdir -p "$out"
rm -f "$out"/*.out "$out/cases.tsv"
printf '# name\texit\targv (generated by tests/tools/usage-goldens.sh from tag %s)\n' "$tag" > "$out/cases.tsv"
for c in "${cases[@]}"; do
    name="${c%%|*}"
    read -ra argv <<< "${c#*|}"
    rc=0
    "$bash_impl" "${argv[@]}" < /dev/null > "$work/stdout" 2> /dev/null || rc=$?
    # The temp state dir appears in some blocks: write the production path.
    sed "s#${TACCTL_STATE_DIR}/#/etc/tacctl/#g" "$work/stdout" > "$out/$name.out"
    printf '%s\t%s\t%s\n' "$name" "$rc" "${c#*|}" >> "$out/cases.tsv"
done
echo "wrote $(( ${#cases[@]} )) usage blocks from tag ${tag} to ${out}"
