#!/usr/bin/env bats
# What 'tacctl install' does to the configuration, and what 'tacctl uninstall'
# removes beyond the directories -- the parts of the two commands that are
# functions (lib/lifecycle.sh, lib/backends/tacacs.sh). The commands themselves shell out to git, go,
# apt, useradd and systemd and are not driven here.
#
#   install_seed_config      fresh install: seed the store, render tacquito.yaml
#   install_readme           README.md into the config directory, world-readable
#   uninstall_remove_access  sudoers drop-ins and Linux host build data
#
# Every external command is stubbed. The suite runs unprivileged, so the chown
# calls only prove they are made; real ownership needs a root run.

load ../helpers/setup
load ../helpers/tmpenv
load ../helpers/mocks
load ../helpers/fixtures

FIX="${BATS_TEST_DIRNAME}/../fixtures"
SECRET="0123456789abcdef0123456789abcdef"
HASH="24326224313024616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161"

setup() {
    tacctl_tmpenv_init
    tacctl_mocks_init
    # uninstall_remove_access removes these paths: keep them in the sandbox.
    export TACCTL_TIER_SUDOERS_FILE="${BATS_TEST_TMPDIR}/sudoers.d/tacctl-tiers"
    export TACCTL_LINUX_DIR="${BATS_TEST_TMPDIR}/var-lib-tacctl/linux"
    stub_cmd chown
    stub_cmd systemctl
    stub_cmd logger
    stub_cmd openssl "echo ${SECRET}"
    # A fresh machine: no state directory yet, an empty config directory.
    rm -rf "$TACCTL_STATE_DIR"
    tacctl_source_lib
}

# What cmd_install runs, in its order, up to the point the service starts.
fresh_install() {
    state_migrate
    install_seed_config
}

sha() { sha256sum "$1" | cut -d' ' -f1; }

fake_tacquito_serve() {
    cat > "${TACCTL_BIN}/tacquito" <<'SH'
#!/usr/bin/env bash
echo "INFO: main.go:135: serve on 127.0.0.1:40001" >&2
echo "INFO: loader.go:241: updated all providers from config source" >&2
exec sleep 30
SH
    chmod +x "${TACCTL_BIN}/tacquito"
}

# --- fresh install ---

@test "install: a fresh install seeds the store and renders tacquito.yaml from it" {
    run fresh_install
    assert_success
    assert_output --partial "Seeding the store at ${STORE_FILE}"
    assert_output --partial "Writing configuration to ${CONFIG}"
    assert_output --partial "engineer (superuser) — disabled"
    assert_output --partial "root     (readonly)  — disabled (accounting sink"
    # The secret is shown once, by the summary, not by the progress lines.
    refute_output --partial "$SECRET"

    [[ "$(stat -c %a "$TACCTL_STATE_DIR")" == "700" ]]
    [[ "$(stat -c %a "$STORE_FILE")" == "600" ]]
    [[ "$(stat -c %a "$CONFIG")" == "640" ]]
    [[ "$(stat -c %a "$RENDERED_FILE")" == "600" ]]
    run head -1 "$CONFIG"
    assert_output --partial "GENERATED by tacctl"
    stub_called "^chown tacquito:tacquito .*tacquito\.yaml"
    # Nothing to adopt and nothing displaced on a fresh machine.
    [[ ! -e "${BACKUP_DIR}/legacy" ]]
    [[ ! -e "$TACCTL_OVERRIDES_FILE" ]]
    run stub_called '^systemctl'
    assert_failure
}

@test "install: the mode and the generated secret are handed to the caller, not printed" {
    fresh_install > /dev/null
    [[ "$INSTALL_CONFIG_MODE" == "fresh" ]]
    [[ "$INSTALL_SHARED_SECRET" == "$SECRET" ]]
    stub_called '^openssl rand -hex 16$'
    # ...and never reaches a command line.
    run grep -F "$SECRET" "$CALLS_LOG"
    assert_failure
}

@test "install: the store holds the built-in groups, the seed users disabled, the root sink, and scope lab" {
    fresh_install > /dev/null
    run python3 - "$STORE_FILE" "$SECRET" <<'PY'
import sys, yaml
s = yaml.safe_load(open(sys.argv[1]))
assert s['groups'] == {
    'readonly':  {'priv_lvl': 1,  'juniper_class': 'RO-CLASS', 'builtin': True},
    'operator':  {'priv_lvl': 7,  'juniper_class': 'OP-CLASS', 'builtin': True},
    'superuser': {'priv_lvl': 15, 'juniper_class': 'RW-CLASS', 'builtin': True},
}, s['groups']
want = {'engineer': 'superuser', 'operator': 'operator', 'viewer': 'readonly', 'root': 'readonly'}
assert set(s['users']) == set(want), s['users']
for name, group in want.items():
    u = s['users'][name]
    assert u['group'] == group and u['scopes'] == ['lab'], (name, u)
    assert u['hash'] is None and u['disabled'] is True, (name, u)
    assert u.get('accounting_sink', False) is (name == 'root'), (name, u)
assert s['scopes'] == {'lab': {
    'prefixes': ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16'], 'secret': sys.argv[2]}}, s['scopes']
assert s['filters'] == {'allow': [], 'deny': []}
print('OK')
PY
    assert_output "OK"
    [[ "$(conf_get scope.default)" == "lab" ]]
}

# tests/fixtures/legacy.fresh-install.yaml is what the template-editing
# installer wrote (config/backends/tacacs/tacquito.yaml with the secret substituted,
# secrets flattened and sorted, command rules spliced in, the four users appended),
# captured from the last commit that had it, with $SECRET as the secret.

@test "install: the fixture of the old installer's output still matches the shipped template" {
    # Everything the template fixed -- constants, accounter, services -- is in
    # the fixture verbatim; only users, command rules and secrets were edited in.
    local section
    for section in 'Type constants' 'Accounting' 'Services'; do
        diff <(sed -n "/^# --- ${section} ---/,/^# --- /p" "${TACCTL_SRC}/config/backends/tacacs/tacquito.yaml") \
             <(sed -n "/^# --- ${section} ---/,/^# --- /p" "${FIX}/legacy.fresh-install.yaml")
    done
}

@test "install: what the daemon loads is equivalent to what the old template path produced" {
    fresh_install > /dev/null
    run store_equiv_check "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    assert_success
    assert_output "EQUIVALENT"
    # No latent difference either (groups or scopes without users).
    refute_output --partial "note:"
}

@test "install: the seeded store is byte for byte what importing the old installer's file gives" {
    fresh_install > /dev/null
    local seeded="${BATS_TEST_TMPDIR}/seeded.yaml" rendered="${BATS_TEST_TMPDIR}/seeded.tacquito.yaml"
    cp "$STORE_FILE" "$seeded"
    cp "$CONFIG" "$rendered"
    rm -f "$STORE_FILE" "$RENDERED_FILE"
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    _model_invalidate
    # The old file passes the upgrade gate's check as it stands...
    run store_import --check
    assert_success
    assert_output --partial "    EQUIVALENT"
    # ...imports to the same store...
    store_import > /dev/null
    cmp "$STORE_FILE" "$seeded"
    # ...and renders to the same file.
    tacacs_render_apply --force > /dev/null
    cmp "$CONFIG" "$rendered"
}

@test "install: a fresh install is fully working: valid, no drift, mutations allowed" {
    fresh_install > /dev/null
    run "$TACCTL_BIN_SCRIPT" config validate
    assert_success
    assert_line --regexp 'Store:.* valid$'
    assert_line --regexp 'Rendered config:.* up to date$'
    assert_output --partial "Configuration is valid."
    refute_output --partial "DRIFT"
    refute_output --partial "not initialised"
    run backends_check_drift
    assert_success
    assert_output ""

    run "$TACCTL_BIN_SCRIPT" user list
    assert_success
    assert_output --partial "engineer"
    assert_output --partial "viewer"

    # First mutation: nothing to adopt, nothing refused, the daemon restarts.
    run "$TACCTL_BIN_SCRIPT" user add alice superuser --hash "$HASH"
    assert_success
    assert_output --partial "with scopes: lab"
    refute_output --partial "Previous"
    stub_called 'systemctl restart tacquito'
    run "$TACCTL_BIN_SCRIPT" scope add prod --prefixes 10.20.0.0/16 --secret "prod-secret-0123456789abcdef"
    assert_success
    run "$TACCTL_BIN_SCRIPT" config validate
    assert_success
    assert_line --regexp 'Rendered config:.* up to date$'
}

@test "install: the seeded secret is the one 'scope secret lab show' and the rendered config carry" {
    fresh_install > /dev/null
    run "$TACCTL_BIN_SCRIPT" scope secret lab show
    assert_success
    assert_output --partial "$SECRET"
    run python3 - "$CONFIG" <<'PY'
import sys, yaml
d = yaml.safe_load(open(sys.argv[1]))
print(sorted({s['secret']['key'] for s in d['secrets']}))
print([s['options']['prefixes'].split('"')[1] for s in d['secrets']])
PY
    assert_line "['${SECRET}']"
    assert_line "['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16']"
}

@test "install: a secret that cannot be generated stops the install before anything is written" {
    stub_cmd openssl 'exit 1'
    run fresh_install
    assert_failure
    assert_output --partial "Could not generate a shared secret"
    [[ ! -e "$STORE_FILE" && ! -e "$CONFIG" ]]
}

# --- install over existing data ---

@test "install: an existing store is kept -- no reseed, no new secret" {
    fresh_install > /dev/null
    "$TACCTL_BIN_SCRIPT" user add alice superuser --hash "$HASH" > /dev/null
    local store_before config_before
    store_before=$(sha "$STORE_FILE")
    config_before=$(sha "$CONFIG")
    : > "$CALLS_LOG"
    run fresh_install
    assert_success
    assert_output --partial "Existing store found at ${STORE_FILE}"
    fresh_install > /dev/null
    [[ "$INSTALL_CONFIG_MODE" == "store" && -z "$INSTALL_SHARED_SECRET" ]]
    [[ "$(sha "$STORE_FILE")" == "$store_before" ]]
    [[ "$(sha "$CONFIG")" == "$config_before" ]]
    run stub_called '^openssl'
    assert_failure
}

@test "install: an existing store whose rendered config is gone gets it back" {
    fresh_install > /dev/null
    local config_before
    config_before=$(sha "$CONFIG")
    rm -f "$CONFIG"
    fresh_install > /dev/null
    [[ "$INSTALL_CONFIG_MODE" == "store" ]]
    [[ "$(sha "$CONFIG")" == "$config_before" ]]
}

@test "install: an existing legacy tacquito.yaml is not overwritten; it goes through the upgrade gate" {
    fake_tacquito_serve
    mkdir -p "$TACCTL_ETC"
    cp "${FIX}/golden/tacquito.multiscope.rendered.yaml" "$CONFIG"
    run fresh_install
    assert_success
    assert_output --partial "Existing ${CONFIG} found: it is kept"
    assert_output --partial "Store migration complete"
    # The users of the existing install, not the seed users.
    run "$TACCTL_BIN_SCRIPT" user list
    assert_output --partial "alice"
    refute_output --partial "engineer"
    run stub_called '^openssl'
    assert_failure
}

@test "install: an existing legacy tacquito.yaml the gate stops on is left exactly as it is" {
    fake_tacquito_serve
    place_fixture legacy.unrepresentable.yaml
    fresh_install > /dev/null 2>&1
    [[ "$INSTALL_CONFIG_MODE" == "legacy" && -z "$INSTALL_SHARED_SECRET" ]]
    [[ ! -e "$STORE_FILE" ]]
    # Byte-identical to the file after the legacy migrations alone.
    local after_gate
    after_gate=$(sha "$CONFIG")
    config_sync_existing
    [[ "$(sha "$CONFIG")" == "$after_gate" ]]
    grep -q 'custom_setting' "$CONFIG"
}

# --- README.md (bug: never placed on a fresh install, and 0600) ---

@test "install_readme: places README.md world-readable under the script's umask" {
    [[ "$(umask)" == "0077" ]]
    run install_readme "${TACCTL_SRC}/README.md"
    assert_success
    cmp "${TACCTL_SRC}/README.md" "${CONFIG_DIR}/README.md"
    [[ "$(stat -c %a "${CONFIG_DIR}/README.md")" == "644" ]]
}

@test "install_readme: fails loudly when the config directory does not exist yet" {
    rm -rf "$CONFIG_DIR"
    run install_readme "${TACCTL_SRC}/README.md"
    assert_failure
}

@test "install_readme: a checkout without README.md is not an error" {
    run install_readme "${BATS_TEST_TMPDIR}/no-such-file"
    assert_success
    [[ ! -e "${CONFIG_DIR}/README.md" ]]
}

@test "cmd_install places README.md after the config directory exists" {
    # The order is the bug: the copy used to run before 'mkdir $CONFIG_DIR'.
    # Both are in the TACACS+ backend's 'account' phase of install, which
    # cmd_install runs before it seeds the configuration.
    local body mkdir_line readme_line
    body=$(declare -f cmd_install)
    run grep -c 'backends_run install account' <<< "$body"
    assert_output "1"
    (( $(grep -n 'backends_run install account' <<< "$body" | cut -d: -f1) \
        < $(grep -n 'install_seed_config' <<< "$body" | cut -d: -f1) ))
    body=$(declare -f _tacacs_install_account)
    mkdir_line=$(grep -n 'mkdir -p "$CONFIG_DIR" "$LOG_DIR"' <<< "$body" | cut -d: -f1)
    readme_line=$(grep -n 'install_readme ' <<< "$body" | cut -d: -f1)
    [[ -n "$mkdir_line" && -n "$readme_line" ]]
    (( readme_line > mkdir_line ))
    run grep -c 'README.md' <<< "$body"
    assert_output "1"
}

# --- uninstall (bug: tier sudoers rules and Linux host data were left behind) ---

@test "uninstall_remove_access: removes both sudoers drop-ins and the Linux host data" {
    # Guard: never let this test reach a real path.
    [[ "$SUDOERS_FILE" == "${BATS_TEST_TMPDIR}/"* && "$TIER_SUDOERS_FILE" == "${BATS_TEST_TMPDIR}/"* \
        && "$LINUX_DIR" == "${BATS_TEST_TMPDIR}/"* ]]
    mkdir -p "$(dirname "$SUDOERS_FILE")" "${LINUX_DIR}/builds/debian-13-x86_64"
    echo "%netops ALL=(root) /usr/local/bin/tacctl" > "$SUDOERS_FILE"
    echo "%tac-readonly ALL=(root) NOPASSWD: /usr/local/bin/tacctl status" > "$TIER_SUDOERS_FILE"
    echo "module" > "${LINUX_DIR}/builds/debian-13-x86_64/pam_tacplus.so"
    echo "keep" > "$(dirname "$SUDOERS_FILE")/other"
    run uninstall_remove_access
    assert_success
    assert_output ""
    [[ ! -e "$SUDOERS_FILE" && ! -e "$TIER_SUDOERS_FILE" ]]
    [[ ! -e "$LINUX_DIR" && ! -e "$(dirname "$LINUX_DIR")" ]]
    [[ -f "$(dirname "$SUDOERS_FILE")/other" ]]
}

@test "uninstall_remove_access: nothing to remove is not an error; a shared parent directory is kept" {
    [[ "$SUDOERS_FILE" == "${BATS_TEST_TMPDIR}/"* && "$TIER_SUDOERS_FILE" == "${BATS_TEST_TMPDIR}/"* \
        && "$LINUX_DIR" == "${BATS_TEST_TMPDIR}/"* ]]
    run uninstall_remove_access
    assert_success
    mkdir -p "$LINUX_DIR"
    echo "not ours" > "$(dirname "$LINUX_DIR")/other"
    run uninstall_remove_access
    assert_success
    [[ ! -e "$LINUX_DIR" ]]
    [[ -f "$(dirname "$LINUX_DIR")/other" ]]
}

@test "cmd_uninstall removes the tier sudoers rules, bash completion and Linux host data" {
    local body
    body=$(declare -f cmd_uninstall)
    grep -q 'uninstall_remove_access' <<< "$body"
    grep -q 'rm -f /etc/bash_completion.d/tacctl' <<< "$body"
    # Through the path variables, not a second copy of the literals.
    run grep -c '/etc/sudoers.d' <<< "$body"
    assert_output "0"
}
