package cli

import "github.com/spf13/cobra"

// The 'config' family (lib/dispatch.sh cmd_config at 0.1.16). Delegated
// until WP2.4c (device configs: WP3.1; linux: WP3.2; branch: WP3.3d).
func configCmd() *cobra.Command {
	filter := func(name, short string) *cobra.Command {
		return verb(name, short,
			verb("list", "Show the list"),
			verb("add", "Add one or more CIDRs"),
			verb("remove", "Remove one or more CIDRs"),
			verb("clear", "Wipe all (confirms)"),
		)
	}
	return verb("config", "Configuration (show, render, cisco, juniper, wti, validate, ...)",
		verb("show", "Show current configuration"),
		verb("dump", "Show tacctl defaults + overrides + merged view"),
		verb("defaults", "Print canonical tacctl defaults (shipped)"),
		verb("get", "Read a dotted-path value from the merged config"),
		verb("get-list", "Read a list value (one item per line)"),
		verb("validate", "Validate config syntax and structure"),
		verb("render", "Regenerate every enabled backend's config from the store"),
		verb("diff", "Diff store.yaml and tacctl.yaml vs the last snapshot (or named one)"),
		verb("restore", "Restore a snapshot (prompts for confirmation)"),
		verb("loglevel", "Show or change log level"),
		verb("listen", "Show, change, or reset a listen address"),
		verb("metrics", "Prometheus exporter control",
			verb("show", "Show the exporter's state"),
			verb("enable", "Enable the exporter"),
			verb("disable", "Disable the exporter"),
			verb("address", "Set the exporter's address"),
			verb("reset", "Reset the exporter's address"),
		),
		verb("sudoers", "Manage NOPASSWD sudoers drop-in for tacctl",
			verb("show", "Show the drop-in"),
			verb("install", "Install the drop-in (confirms)"),
			verb("remove", "Remove the drop-in"),
			verb("tiers", "Manage per-tier (RO/OP/SU) sudoers rules",
				verb("show", "Show the tier rules"),
				verb("install", "Install the tier rules"),
				verb("remove", "Remove the tier rules"),
			),
		),
		verb("password-age", "Show or set password age warning threshold"),
		verb("bcrypt-cost", "Show or set bcrypt cost factor (default 12)"),
		verb("password-min-length", "Show or set minimum interactive password length (default 12)"),
		verb("secret-min-length", "Show or set minimum shared-secret length (default 16)"),
		filter("allow", "Manage connection allow list"),
		filter("deny", "Manage connection deny list"),
		verb("mgmt-acl", "Manage Cisco VTY-ACL + Juniper lo0-filter permits",
			verb("list", "Show current permits"),
			verb("add", "Add one or more CIDRs"),
			verb("remove", "Remove one or more CIDRs"),
			verb("clear", "Wipe all permits (confirms)"),
			verb("cisco-name", "Show or set the Cisco ACL name"),
			verb("juniper-name", "Show or set the Juniper filter name"),
		),
		verb("cisco", "Show working Cisco device configuration for a scope"),
		verb("juniper", "Show working Juniper device configuration for a scope"),
		verb("wti", "Show step-by-step WTI console-server setup for a scope"),
		verb("linux", "TACACS+ or RADIUS login for Linux hosts (install/removal scripts)",
			verb("build", "Fetch and prepare the pinned pam_tacplus source"),
			verb("script", "Write the install script for hosts in a scope"),
			verb("remove-script", "Write the removal script"),
			verb("uid", "Show or change the UID/GID a user gets on every host"),
			verb("builds", "Show or drop the modules 'host enroll' built in containers"),
		),
		verb("branch", "Show or change the tacctl repo branch"),
	)
}
