#!/usr/bin/env bats
# Bash completion: 'tacctl completion bash' prints the generated script, which
# asks the binary ('tacctl __complete <words>') what can come next. The words
# come from the command tree and the verbs' argument specs, never from the
# store; live names (users, groups, scopes, backends, listeners, backups) come
# through the bridge 'sudo -n tacctl _completion-names <kind>', which the tests
# answer with a 'sudo' stub. The generated function runs in a bash of its own
# with the real bash-completion library.

load ../helpers/setup
load ../helpers/tmpenv
load ../helpers/mocks
load ../helpers/fixtures

setup() {
    tacctl_tmpenv_init
    tacctl_mocks_init
    stub_cmd chown
    stub_cmd systemctl
    [[ -r /usr/share/bash-completion/bash_completion ]] || skip "bash-completion not installed"
    # The command the script asks, by the name it was typed with.
    stub_cmd tacctl "exec \"${TACCTL_BIN_SCRIPT}\" \"\$@\""
    # The bridge: 'sudo -n tacctl _completion-names <kind> [arg]'.
    stub_cmd sudo 'case "$*" in
  *"_completion-names backends")         printf "%s\n" tacacs radius ;;
  *"_completion-names enabled-backends") printf "%s\n" tacacs ;;
  *"_completion-names listeners radius") printf "%s\n" auth acct ;;
  *"_completion-names listeners")        printf "%s\n" default ;;
  *"_completion-names scopes")           printf "%s\n" lab prod ;;
  *"_completion-names users")            printf "%s\n" alice bob ;;
  *"_completion-names groups")           printf "%s\n" ops admins ;;
  *"_completion-names hosts")            printf "%s\n" web1 db1 ;;
  *"_completion-names devices")          printf "%s\n" db1 sw1 web1 ;;
esac'
}

# complete_words <word>...: what the completion offers for that command line,
# one per line; the last word is the one being completed (empty string: a
# fresh word).
complete_words() {
    run bash -c '
        source /usr/share/bash-completion/bash_completion
        source <(tacctl completion bash)
        compopt() { :; }
        COMP_WORDS=("$@"); COMP_CWORD=$(( ${#COMP_WORDS[@]} - 1 ))
        COMP_LINE="${COMP_WORDS[*]}"; COMP_POINT=${#COMP_LINE}
        __start_tacctl
        printf "%s\n" "${COMPREPLY[@]}"
    ' _ "$@"
}

@test "completion: the script is generated by the binary and asks the binary" {
    run "$TACCTL_BIN_SCRIPT" completion bash
    assert_success
    assert_line --partial "bash completion V2 for tacctl"
    assert_output --partial "__complete"
    refute_output --partial "/etc/tacquito"
    run "$TACCTL_BIN_SCRIPT" completion
    assert_failure
    assert_output --partial "Usage: tacctl completion bash|zsh|fish"
    run "$TACCTL_BIN_SCRIPT" completion zsh
    assert_success
    assert_line "#compdef tacctl"
    assert_output --partial "__complete"
    refute_output --partial "/etc/tacquito"
    run "$TACCTL_BIN_SCRIPT" completion fish
    assert_success
    assert_line --partial "fish completion for tacctl"
    assert_output --partial "__complete"
    refute_output --partial "/etc/tacquito"
    run "$TACCTL_BIN_SCRIPT" completion powershell
    assert_failure
    assert_output --partial "Usage: tacctl completion bash|zsh|fish"
}

@test "completion: the top level offers backend and store, and not the hidden words" {
    complete_words tacctl ""
    assert_line "backend"
    assert_line "store"
    assert_line "install"
    refute_line "completion"
    refute_line "_phase"
    refute_line "_completion-names"
    refute_line "help"
    complete_words tacctl ba
    assert_output "$(printf 'backend\nbackup')"
}

@test "completion: backend subcommands, then backend ids, then -y" {
    complete_words tacctl backend ""
    assert_output "$(printf 'disable\nenable\nlist\nstatus')"
    complete_words tacctl backend enable ""
    assert_output "$(printf 'tacacs\nradius')"
    complete_words tacctl backend status r
    assert_output "radius"
    complete_words tacctl backend disable ""
    assert_output "tacacs"
    complete_words tacctl backend enable radius ""
    assert_output "$(printf -- '-y\n--yes')"
    complete_words tacctl backend list ""
    assert_output ""
}

@test "completion: store subcommands and their flags" {
    complete_words tacctl store ""
    assert_output "$(printf 'import\nrollback\nshow')"
    complete_words tacctl store show -
    assert_output "--json"
    complete_words tacctl store import --
    assert_output "$(printf -- '--check\n--force\n--replace')"
}

@test "completion: config offers render with --dry-run and --out, and listen takes --backend and --listener" {
    complete_words tacctl config ren
    assert_output "render"
    complete_words tacctl config render ""
    assert_output "$(printf -- '--force\n--dry-run\n--out')"
    complete_words tacctl config render --dry-run ""
    assert_output "$(printf -- '--force\n--out')"
    complete_words tacctl config listen ""
    assert_line "--backend"
    assert_line "--listener"
    assert_line "reset"
    complete_words tacctl config listen --backend ""
    assert_output "$(printf 'tacacs\nradius')"
    complete_words tacctl config listen --backend radius --listener ""
    assert_output "$(printf 'auth\nacct')"
    complete_words tacctl config listen --listener ""
    assert_output "default"
    complete_words tacctl config listen --backend radius ""
    assert_line "--listener"
    refute_line "--backend"
}

@test "completion: config cisco and juniper take --protocol, and its value is tacacs or radius" {
    complete_words tacctl config cisco ""
    assert_output "$(printf -- '--scope\n--protocol\n--staging\n--name\n--legacy')"
    complete_words tacctl config juniper ""
    assert_output "$(printf -- '--scope\n--protocol\n--staging\n--name')"
    complete_words tacctl config cisco --protocol ""
    assert_output "$(printf 'tacacs\nradius')"
    complete_words tacctl config juniper --scope lab --protocol ""
    assert_output "$(printf 'tacacs\nradius')"
    complete_words tacctl config juniper --scope lab ""
    assert_output "$(printf -- '--protocol\n--staging\n--name')"
    complete_words tacctl config cisco --protocol radius ""
    assert_output "$(printf -- '--scope\n--staging\n--name\n--legacy')"
    complete_words tacctl config cisco --protocol radius --scope lab ""
    assert_output "$(printf -- '--staging\n--name\n--legacy')"
    # WTI takes --protocol like the others.
    complete_words tacctl config wti ""
    assert_output "$(printf -- '--scope\n--protocol\n--staging\n--name')"
    complete_words tacctl config wti --protocol ""
    assert_output "$(printf 'tacacs\nradius')"
    complete_words tacctl config wti --scope lab ""
    assert_output "$(printf -- '--protocol\n--staging\n--name')"
}

@test "completion: scope offers radius-group beside tacacs-group" {
    complete_words tacctl scope radius
    assert_output "radius-group"
}

@test "completion: scope offers auth-method, a scope name, then tacacs, radius or clear" {
    complete_words tacctl scope auth
    assert_output "auth-method"
    complete_words tacctl scope auth-method lab ""
    assert_output "$(printf 'tacacs\nradius\nclear')"
}

@test "completion: scope vendor-attrs offers show, enable and disable, then vendors" {
    complete_words tacctl scope vend
    assert_output "vendor-attrs"
    complete_words tacctl scope vendor-attrs lab ""
    assert_output "$(printf 'show\nenable\ndisable')"
    complete_words tacctl scope vendor-attrs lab enable ""
    assert_line "cisco"
    assert_line "juniper"
    assert_line "wti"
    complete_words tacctl scope vendor-attrs lab disable w
    assert_output "wti"
}

@test "completion: scope devices offers list, set and unset, and a vendor after set's address" {
    complete_words tacctl scope dev
    assert_output "devices"
    complete_words tacctl scope devices lab ""
    assert_output "$(printf 'list\nset\nunset')"
    complete_words tacctl scope devices lab set 10.1.2.3 ""
    assert_output "$(printf 'cisco\njuniper\nwti')"
    complete_words tacctl scope devices lab unset 10.1.2.3 ""
    assert_output ""
}

@test "completion: scope add offers --protocols and --vendor-attrs, with their values" {
    complete_words tacctl scope add edge ""
    assert_output "$(printf -- '--prefixes\n--secret\n--protocols\n--vendor-attrs\n--default')"
    complete_words tacctl scope add edge --prefixes 10.0.0.0/8 --vendor-attrs ""
    assert_line "cisco"
    assert_line "juniper"
    assert_line "wti"
    complete_words tacctl scope add edge --prefixes 10.0.0.0/8 --vendor-attrs cisco,
    assert_output "$(printf 'cisco,juniper\ncisco,wti')"
    complete_words tacctl scope add edge --prefixes 10.0.0.0/8 --vendor-attrs cisco ""
    assert_output "$(printf -- '--secret\n--protocols\n--default')"
}

@test "completion: log subcommands take --backend, and its value is a backend id" {
    complete_words tacctl log tail --
    assert_output "$(printf -- '--backend\n--follow')"
    complete_words tacctl log tail --backend ""
    assert_output "$(printf 'tacacs\nradius')"
    complete_words tacctl log clear ""
    assert_output "$(printf -- '--backend\n--force\n-y\n--yes')"
    complete_words tacctl log clear --backend tacacs ""
    assert_output "$(printf -- '--force\n-y\n--yes')"
}

@test "completion: scope protocols still completes its verbs and the protocols" {
    complete_words tacctl scope protocols lab ""
    assert_output "$(printf 'list\nset\nclear')"
    complete_words tacctl scope protocols lab set ""
    assert_line "tacacs"
    assert_line "radius"
}

@test "completion: scope prefixes offers list, add and remove, then --all, then --force only after remove" {
    complete_words tacctl scope prefixes lab ""
    assert_output "$(printf 'list\nadd\nremove\nmove')"
    complete_words tacctl scope prefixes lab remove ""
    assert_output "$(printf -- '--all\n--force')"
    complete_words tacctl scope prefixes lab remove --all ""
    assert_output -- "--force"
    complete_words tacctl scope prefixes lab add ""
    assert_output ""
}

@test "completion: user scope offers list, add, remove and replace, and scope names; --all only after remove" {
    complete_words tacctl user scope alice ""
    assert_output "$(printf 'list\nadd\nremove\nreplace')"
    complete_words tacctl user scope alice remove ""
    assert_output "$(printf 'lab\nprod\n--all')"
    complete_words tacctl user scope alice remove --all ""
    assert_output ""
    complete_words tacctl user scope alice replace ""
    assert_output "$(printf 'lab\nprod')"
    complete_words tacctl user scope alice add ""
    assert_output "$(printf 'lab\nprod')"
    # A single candidate is shell-quoted by the generated script: lab\,prod
    # is the word lab,prod.
    complete_words tacctl user scope alice add lab,
    assert_output 'lab\,prod'
}

@test "completion: config linux script flags and methods, builds, backup restore --legacy" {
    complete_words tacctl config linux ""
    assert_output "$(printf 'build\nbuilds\nengineer-sudo\nremove-script\nscript\nuid\nuid-range')"
    complete_words tacctl config linux script ""
    assert_output "$(printf -- '--scope\n--server\n--method\n--output\n-o')"
    complete_words tacctl config linux script --method ""
    assert_output "$(printf 'tacplus\nradius')"
    complete_words tacctl config linux builds ""
    assert_output "$(printf 'list\nclear')"
    complete_words tacctl backup restore 20260101-000000 ""
    assert_output -- "--legacy"
    complete_words tacctl config restore 20260101-000000 ""
    assert_output -- "--legacy"
    complete_words tacctl host default-method ""
    assert_output "$(printf 'tacplus\nradius')"
}

@test "completion: install, upgrade, uninstall and version offer their flags" {
    complete_words tacctl install ""
    assert_output "$(printf -- '--branch\n-y\n--yes')"
    complete_words tacctl upgrade ""
    assert_output "--branch"
    complete_words tacctl uninstall ""
    assert_output "$(printf -- '-y\n--yes')"
    complete_words tacctl version ""
    assert_output "--long"
}

@test "completion: user, group and scope names come from the sudo bridge only, never from tacquito.yaml" {
    # A rendered tacquito.yaml lacks the scopes TACACS+ does not serve.
    stub_cmd sudo 'case "$*" in
  *"_completion-names scopes") printf "%s\n" lab radius-only ;;
esac'
    complete_words tacctl scope show ""
    assert_output "$(printf 'lab\nradius-only')"
    run "$TACCTL_BIN_SCRIPT" completion bash
    refute_output --partial "/etc/tacquito"
}

@test "completion: no sudo rule, no names, and no error" {
    stub_cmd sudo 'exit 1'
    complete_words tacctl scope show ""
    assert_success
    assert_output ""
}

# --- the names the bridge asks tacctl for ---------------------------------------

@test "_completion-names: backends are every registered id, enabled-backends the enabled ones, listeners a backend's" {
    load_fixture tacquito.minimal.yaml
    run "$TACCTL_BIN_SCRIPT" _completion-names backends
    assert_success
    assert_output "$(printf 'tacacs\nradius')"
    run "$TACCTL_BIN_SCRIPT" _completion-names enabled-backends
    assert_output "tacacs"
    run "$TACCTL_BIN_SCRIPT" _completion-names listeners
    assert_output "$(printf 'acct\nauth\ndefault')"
    run "$TACCTL_BIN_SCRIPT" _completion-names listeners radius
    assert_output "$(printf 'acct\nauth')"
    "$TACCTL_BIN_SCRIPT" config listen --listener mgmt tcp 127.0.0.1:4949 > /dev/null
    run "$TACCTL_BIN_SCRIPT" _completion-names listeners tacacs
    assert_output "$(printf 'default\nmgmt')"
    run "$TACCTL_BIN_SCRIPT" _completion-names listeners nope
    assert_success
    assert_output ""
}

@test "completion: host sync, unenroll and show offer the enrolled host names" {
    complete_words tacctl host sync ""
    assert_output "$(printf 'web1\ndb1\n--all\n--allow-uid-mismatch\n--remove-home')"
    complete_words tacctl host sync w
    assert_output "web1"
    complete_words tacctl host unenroll ""
    assert_output "$(printf 'web1\ndb1')"
    complete_words tacctl host show ""
    assert_output "$(printf 'web1\ndb1')"
    complete_words tacctl host show web1 ""
    assert_output "$(printf -- '--all\n--json\n--check')"
}

@test "completion: __complete host sync offers the names the bridge gives" {
    run "$TACCTL_BIN_SCRIPT" __complete host sync ""
    assert_success
    assert_line "web1"
    assert_line "db1"
    run "$TACCTL_BIN_SCRIPT" __complete host unenroll d
    assert_success
    assert_line "db1"
    refute_line "web1"
}

@test "_completion-names hosts and devices: the registry's names, one per line" {
    load_fixture tacquito.minimal.yaml
    printf 'web1|root@192.0.2.10||lab|192.0.2.1|\ndb1|root@192.0.2.11||lab|192.0.2.1|\n' \
        > "${TACCTL_STATE_DIR}/linux-hosts"
    run "$TACCTL_BIN_SCRIPT" _completion-names hosts
    assert_success
    assert_output "$(printf 'web1\ndb1')"
    run "$TACCTL_BIN_SCRIPT" _completion-names devices
    assert_success
    assert_output "$(printf 'db1\nweb1')"
    rm "${TACCTL_STATE_DIR}/linux-hosts"
    run "$TACCTL_BIN_SCRIPT" _completion-names hosts
    assert_success
    assert_output ""
}

@test "completion: Tab Tab lists each flag with its description, and shell -c offers the commands" {
    # COMP_TYPE 63 is bash's listing of the candidates (the second Tab).
    run bash -c '
        source /usr/share/bash-completion/bash_completion
        source <(tacctl completion bash)
        compopt() { :; }
        COMP_WORDS=(tacctl shell -); COMP_CWORD=2
        COMP_LINE="tacctl shell -"; COMP_POINT=${#COMP_LINE}; COMP_TYPE=63; COLUMNS=200
        __start_tacctl
        printf "%s\n" "${COMPREPLY[@]}"
    '
    assert_success
    assert_line --regexp '^--no-history +\(Keep no history file for this session\)$'
    assert_line --regexp '^--idle +\(<min>: End the session after this many idle minutes at the prompt\)$'
    assert_line --regexp '^-c +\(<line>: Run one line and exit\)$'
    complete_words tacctl shell -c sta
    assert_output "status"
    complete_words tacctl shell -c ""
    assert_line "user"
    refute_line "shell"
}
