#!/usr/bin/env bats
# The listener model at work (plan 3.4): 'tacctl config listen' with and
# without --backend/--listener, the backend's 'listeners' and 'service'
# verbs, the systemd drop-ins rendered from tacctl.yaml, and 'tacctl status'
# with more than one listener. systemctl is stubbed; the drop-ins land in
# $TACCTL_OVERRIDE_DIR (the default listener) and beside it (instances).
#
# The schema is in tests/unit/listeners.bats; converting an install from the
# hand-managed drop-in is in tests/integration/units_convert.bats.

load ../helpers/setup
load ../helpers/tmpenv
load ../helpers/mocks
load ../helpers/fixtures

setup() {
    tacctl_tmpenv_init
    tacctl_mocks_init
    export TACCTL_SETTLE_SECONDS=0
    stub_cmd chown
    stub_cmd logger
    stub_cmd systemctl
    load_fixture tacquito.multiscope.yaml
    OVERRIDES="${TACCTL_STATE_DIR}/tacctl.yaml"
    DROPIN="${TACCTL_OVERRIDE_DIR}/tacctl.conf"
    UNITS="${BATS_TEST_TMPDIR}"
    RENDERED="${TACCTL_STATE_DIR}/rendered.json"
}

instance_dropin() { echo "${UNITS}/tacquito@${1}.service.d/tacctl.conf"; }

refute_stub_called() {
    run stub_called "$1"
    assert_failure
}

# systemctl whose 'is-active' fails for the units matching $1 (a regex).
systemctl_fails_for() {
    stub_cmd systemctl "if [[ \"\$1\" == is-active && \"\$*\" =~ $1 ]]; then exit 3; fi; exit 0"
}

# --- The drop-in is rendered from the model ----------------------------------

@test "drop-in: one settings change renders every flag of the default listener" {
    run "$TACCTL_BIN_SCRIPT" config listen tcp 10.1.0.1:49
    assert_success
    run cat "$DROPIN"
    assert_line --index 0 --partial "GENERATED by tacctl from tacctl.yaml"
    assert_line "[Service]"
    assert_line 'Environment="TACQUITO_NETWORK=tcp"'
    assert_line 'Environment="TACQUITO_ADDRESS=10.1.0.1:49"'
    assert_line 'Environment="TACQUITO_LEVEL=20"'
    assert_line 'Environment="TACQUITO_METRICS_ADDRESS=127.0.0.1:8080"'
    assert_line "Environment=\"TACQUITO_ACCT_LOG=${TACCTL_LOG}/accounting.log\""
    [[ "$(stat -c %a "$DROPIN")" == "644" ]]
    # The source of truth is tacctl.yaml; the old hand-managed file is not written.
    grep -q 'address: 10.1.0.1:49' "$OVERRIDES"
    [[ ! -e "${TACCTL_OVERRIDE_DIR}/tacctl-overrides.conf" ]]
    # ...and it is a recorded artifact.
    grep -qF "\"${DROPIN}\"" "$RENDERED"
}

@test "drop-in: an instance gets its own address, accounting log and no reachable metrics" {
    "$TACCTL_BIN_SCRIPT" config loglevel debug
    run "$TACCTL_BIN_SCRIPT" config listen --listener mgmt tcp 127.0.0.1:4949
    assert_success
    run cat "$(instance_dropin mgmt)"
    assert_line 'Environment="TACQUITO_NETWORK=tcp"'
    assert_line 'Environment="TACQUITO_ADDRESS=127.0.0.1:4949"'
    assert_line 'Environment="TACQUITO_LEVEL=30"'
    assert_line 'Environment="TACQUITO_METRICS_ADDRESS=127.0.0.1:0"'
    assert_line "Environment=\"TACQUITO_ACCT_LOG=${TACCTL_LOG}/accounting-mgmt.log\""
    # The default listener keeps its own.
    run cat "$DROPIN"
    assert_line 'Environment="TACQUITO_ADDRESS=:49"'
    assert_line "Environment=\"TACQUITO_ACCT_LOG=${TACCTL_LOG}/accounting.log\""
}

@test "drop-in: rendering is deterministic, and a second render changes nothing" {
    "$TACCTL_BIN_SCRIPT" config render --force > /dev/null
    local before
    before=$(sha256sum "$DROPIN" "$RENDERED")
    : > "$CALLS_LOG"
    run "$TACCTL_BIN_SCRIPT" config render
    assert_success
    assert_output --partial "already up to date"
    [[ "$(sha256sum "$DROPIN" "$RENDERED")" == "$before" ]]
    refute_stub_called '^systemctl'
}

# --- The drop-in in the render machinery -------------------------------------

@test "render: a tacctl.yaml changed by hand is applied by 'config render': reload, restart, instance started" {
    "$TACCTL_BIN_SCRIPT" config render --force > /dev/null
    touch "${UNITS}/tacquito.service"
    printf 'listeners:\n  tacacs:\n    default: {network: tcp, address: "10.1.0.1:49"}\n    mgmt: {network: tcp, address: "127.0.0.1:4949"}\n' > "$OVERRIDES"
    run "$TACCTL_BIN_SCRIPT" config validate
    assert_failure
    assert_output --partial "is missing"
    : > "$CALLS_LOG"
    run "$TACCTL_BIN_SCRIPT" config render
    assert_success
    grep -qxF 'Environment="TACQUITO_ADDRESS=10.1.0.1:49"' "$DROPIN"
    [[ -f "$(instance_dropin mgmt)" ]]
    stub_called '^systemctl daemon-reload$'
    stub_called '^systemctl restart tacquito$'
    stub_called '^systemctl enable --quiet --now tacquito@mgmt.service$'
    grep -qF "\"$(instance_dropin mgmt)\"" "$RENDERED"
}

@test "render: a listener removed from tacctl.yaml loses its drop-in, its record and its instance" {
    "$TACCTL_BIN_SCRIPT" config render --force > /dev/null
    "$TACCTL_BIN_SCRIPT" config listen --listener mgmt tcp 127.0.0.1:4949
    touch "${UNITS}/tacquito.service"
    mkdir -p "${UNITS}/tacquito.service.wants"
    ln -s /nonexistent/tacquito@.service "${UNITS}/tacquito.service.wants/tacquito@mgmt.service"
    rm -f "$OVERRIDES"
    : > "$CALLS_LOG"
    run "$TACCTL_BIN_SCRIPT" config render
    assert_success
    [[ ! -e "$(instance_dropin mgmt)" ]]
    [[ ! -d "${UNITS}/tacquito@mgmt.service.d" ]]
    run grep -F "tacquito@mgmt" "$RENDERED"
    assert_failure
    stub_called '^systemctl daemon-reload$'
    stub_called '^systemctl disable --quiet --now tacquito@mgmt.service$'
}

@test "render: a listener model that cannot be served fails the render and changes nothing" {
    "$TACCTL_BIN_SCRIPT" config render --force > /dev/null
    local before
    before=$(sha256sum "$DROPIN" "$TACCTL_CONFIG" "$RENDERED")
    printf 'listeners:\n  tacacs:\n    tls: {network: tcp, address: ":300", tls: {enabled: true}}\n' > "$OVERRIDES"
    run "$TACCTL_BIN_SCRIPT" config render
    assert_failure
    assert_output --partial "tls.enabled: true is reserved for a future release"
    [[ "$(sha256sum "$DROPIN" "$TACCTL_CONFIG" "$RENDERED")" == "$before" ]]
    # ...and so does a mutation, which puts the store back.
    run "$TACCTL_BIN_SCRIPT" config validate
    assert_failure
    assert_output --partial "listeners.tacacs.tls: tls.enabled: true is reserved"
}

# --- config listen: unchanged when used as before ----------------------------

@test "config listen: show prints what it always printed for the default listener" {
    run "$TACCTL_BIN_SCRIPT" config listen
    assert_success
    assert_line "  Current listener: tcp :49"
    assert_line "  (template default)"
    assert_line "  Usage: tacctl config listen <show|tcp|tcp6|reset> [address]"
    assert_line "    tacctl config listen reset       # drop override, use template default"
    refute_output --partial "Listener '"
    run "$TACCTL_BIN_SCRIPT" config listen show
    assert_line "  Current listener: tcp :49"
}

@test "config listen: a change restarts tacquito after a reload, and show names tacctl.yaml" {
    run "$TACCTL_BIN_SCRIPT" config listen tcp 10.1.0.1:49
    assert_success
    assert_output --partial "Listener changed to tcp 10.1.0.1:49. Service restarted."
    run grep -n -E '^systemctl (daemon-reload|restart tacquito|is-active --quiet tacquito)$' "$CALLS_LOG"
    assert_line --index 0 --partial "daemon-reload"
    assert_line --index 1 --partial "restart tacquito"
    assert_line --index 2 --partial "is-active --quiet tacquito"
    run "$TACCTL_BIN_SCRIPT" config listen show
    assert_line "  Current listener: tcp 10.1.0.1:49"
    assert_line "  (override in ${OVERRIDES})"
    run "$TACCTL_BIN_SCRIPT" config listen tcp 10.1.0.1:49
    assert_output --partial "Already listening on tcp 10.1.0.1:49."
}

@test "config listen: a bad address is refused before anything is written" {
    : > "$CALLS_LOG"
    run "$TACCTL_BIN_SCRIPT" config listen tcp 10.1.0.1
    assert_failure
    assert_output --partial "Invalid tcp address: '10.1.0.1'"
    run "$TACCTL_BIN_SCRIPT" config listen tcp "[::1]:49"
    assert_failure
    run "$TACCTL_BIN_SCRIPT" config listen tcp6 10.1.0.1:49
    assert_failure
    run "$TACCTL_BIN_SCRIPT" config listen tcp
    assert_failure
    assert_output --partial "Missing address. Example: tacctl config listen tcp :49"
    run "$TACCTL_BIN_SCRIPT" config listen udp :49
    assert_failure
    assert_output --partial "Invalid subcommand: 'udp'. Use: show, tcp, tcp6, or reset"
    [[ ! -e "$OVERRIDES" && ! -e "$DROPIN" ]]
    refute_stub_called '^systemctl'
    run bash -c 'ls -d "$1"/backups/2* 2>/dev/null' _ "$TACCTL_STATE_DIR"
    assert_output ""
}

@test "config listen: tcp6 asks first, and 'n' changes nothing" {
    run bash -c 'echo n | "$1" config listen tcp6 "[::]:49"' _ "$TACCTL_BIN_SCRIPT"
    assert_success
    assert_output --partial "tcp6 enables dual-stack sockets"
    assert_output --partial "Aborted."
    [[ ! -e "$OVERRIDES" && ! -e "$DROPIN" ]]
    run bash -c 'echo y | "$1" config listen tcp6 "[::]:49"' _ "$TACCTL_BIN_SCRIPT"
    assert_success
    assert_output --partial "Listener changed to tcp6 [::]:49."
    grep -qxF 'Environment="TACQUITO_NETWORK=tcp6"' "$DROPIN"
    grep -qxF 'Environment="TACQUITO_ADDRESS=[::]:49"' "$DROPIN"
}

@test "config listen: reset says what it always said, and goes back to the default" {
    run "$TACCTL_BIN_SCRIPT" config listen reset
    assert_success
    assert_output --partial "No listener override set. Already on template default (tcp :49)."
    "$TACCTL_BIN_SCRIPT" config listen tcp 10.1.0.1:49
    run "$TACCTL_BIN_SCRIPT" config listen reset
    assert_success
    assert_output --partial "Listener override removed. Using template default. Service restarted."
    grep -qxF 'Environment="TACQUITO_ADDRESS=:49"' "$DROPIN"
    run grep -c listeners "$OVERRIDES"
    assert_failure
}

@test "config listen: a unit that does not come up gets the previous settings back" {
    "$TACCTL_BIN_SCRIPT" config listen tcp 10.1.0.1:49
    local before
    before=$(sha256sum "$DROPIN" "$OVERRIDES" "$RENDERED")
    systemctl_fails_for 'tacquito$'
    : > "$CALLS_LOG"
    run "$TACCTL_BIN_SCRIPT" config listen tcp 10.9.9.9:49
    assert_failure
    assert_output --partial "tacquito failed to start. Restoring previous override."
    [[ "$(sha256sum "$DROPIN" "$OVERRIDES" "$RENDERED")" == "$before" ]]
    # Reload and restart twice: with the new address, then with the old one.
    run grep -c '^systemctl restart tacquito$' "$CALLS_LOG"
    assert_output "2"
    run grep -c '^systemctl daemon-reload$' "$CALLS_LOG"
    assert_output "2"
}

@test "config listen: the first failure leaves no tacctl.yaml and no drop-in behind" {
    systemctl_fails_for 'tacquito$'
    run "$TACCTL_BIN_SCRIPT" config listen tcp 10.9.9.9:49
    assert_failure
    [[ ! -e "$OVERRIDES" && ! -e "$DROPIN" ]]
    run grep -c tacctl.conf "$RENDERED"
    assert_failure
}

@test "config listen: works without a store (legacy mode), as it always did" {
    rm -f "${TACCTL_STATE_DIR}/store.yaml"
    run "$TACCTL_BIN_SCRIPT" config listen tcp 10.1.0.1:49
    assert_success
    assert_output --partial "Listener changed to tcp 10.1.0.1:49. Service restarted."
    grep -qxF 'Environment="TACQUITO_ADDRESS=10.1.0.1:49"' "$DROPIN"
    run "$TACCTL_BIN_SCRIPT" config loglevel debug
    assert_success
    run "$TACCTL_BIN_SCRIPT" config metrics disable
    assert_success
    grep -qxF 'Environment="TACQUITO_LEVEL=30"' "$DROPIN"
    grep -qxF 'Environment="TACQUITO_METRICS_ADDRESS=127.0.0.1:0"' "$DROPIN"
    [[ ! -e "${TACCTL_STATE_DIR}/store.yaml" ]]
    # A user mutation is still refused there.
    run "$TACCTL_BIN_SCRIPT" user disable alice
    assert_failure
}

@test "config listen: with a store the change is snapshotted first and can be diffed" {
    run "$TACCTL_BIN_SCRIPT" config listen tcp 10.1.0.1:49
    assert_success
    assert_output --partial "Config snapshot saved to"
    run "$TACCTL_BIN_SCRIPT" backup diff
    assert_output --partial "10.1.0.1:49"
}

@test "config listen: a hand-edited tacquito.yaml does not stand in the way" {
    "$TACCTL_BIN_SCRIPT" config render --force > /dev/null
    echo "# edited" >> "$TACCTL_CONFIG"
    run "$TACCTL_BIN_SCRIPT" config listen tcp 10.1.0.1:49
    assert_success
    grep -q '# edited' "$TACCTL_CONFIG"
    run "$TACCTL_BIN_SCRIPT" config loglevel debug
    assert_success
}

# --- config listen: --listener and --backend ---------------------------------

@test "config listen --listener: adds a listener as its own instance, restarting nothing else" {
    : > "$CALLS_LOG"
    run "$TACCTL_BIN_SCRIPT" config listen --listener mgmt tcp 127.0.0.1:4949
    assert_success
    assert_output --partial "Listener 'mgmt' added on tcp 127.0.0.1:4949. tacquito@mgmt.service enabled and started."
    assert_output --partial "${TACCTL_LOG}/accounting-mgmt.log"
    stub_called '^systemctl daemon-reload$'
    stub_called '^systemctl enable --quiet tacquito@mgmt.service$'
    stub_called '^systemctl restart tacquito@mgmt.service$'
    stub_called '^systemctl is-active --quiet tacquito@mgmt.service$'
    refute_stub_called '^systemctl restart tacquito$'
    grep -q 'mgmt:' "$OVERRIDES"
}

@test "config listen --listener: show, change and the flag forms" {
    "$TACCTL_BIN_SCRIPT" config listen --listener mgmt tcp 127.0.0.1:4949
    run "$TACCTL_BIN_SCRIPT" config listen --listener mgmt
    assert_success
    assert_line "  Listener 'mgmt': tcp 127.0.0.1:4949"
    assert_line "  (tacquito@mgmt.service; set in ${OVERRIDES})"
    # The default listener's show now lists it too.
    run "$TACCTL_BIN_SCRIPT" config listen show
    assert_line "  Current listener: tcp :49"
    assert_line "  Listener 'mgmt': tcp 127.0.0.1:4949 (tacquito@mgmt.service)"

    : > "$CALLS_LOG"
    run "$TACCTL_BIN_SCRIPT" config listen tcp 127.0.0.1:4950 --listener=mgmt --backend=tacacs
    assert_success
    assert_output --partial "Listener 'mgmt' changed to tcp 127.0.0.1:4950. tacquito@mgmt.service restarted."
    refute_stub_called '^systemctl restart tacquito$'
    grep -qxF 'Environment="TACQUITO_ADDRESS=127.0.0.1:4950"' "$(instance_dropin mgmt)"
    run "$TACCTL_BIN_SCRIPT" config listen --backend tacacs --listener mgmt tcp 127.0.0.1:4950
    assert_output --partial "Already listening on tcp 127.0.0.1:4950."
}

@test "config listen --listener: an address another listener has is refused before anything is written" {
    : > "$CALLS_LOG"
    run "$TACCTL_BIN_SCRIPT" config listen --listener mgmt tcp 10.1.0.1:49
    assert_failure
    assert_output --partial "Cannot listen on tcp 10.1.0.1:49"
    assert_output --partial "already used by listeners.tacacs.default (tcp :49)"
    [[ ! -e "$OVERRIDES" && ! -e "$(instance_dropin mgmt)" ]]
    refute_stub_called '^systemctl'

    "$TACCTL_BIN_SCRIPT" config listen --listener mgmt tcp 127.0.0.1:4949
    run "$TACCTL_BIN_SCRIPT" config listen --listener other tcp 127.0.0.1:4949
    assert_failure
    assert_output --partial "already used by listeners.tacacs.mgmt"
    run "$TACCTL_BIN_SCRIPT" config listen tcp 127.0.0.1:4949
    assert_failure
    assert_output --partial "already used by listeners.tacacs.mgmt"
}

@test "config listen --listener: reset removes the listener, its drop-in and its instance" {
    "$TACCTL_BIN_SCRIPT" config listen --listener mgmt tcp 127.0.0.1:4949
    : > "$CALLS_LOG"
    run "$TACCTL_BIN_SCRIPT" config listen --listener mgmt reset
    assert_success
    assert_output --partial "Listener 'mgmt' removed. tacquito@mgmt.service stopped and disabled."
    [[ ! -e "$(instance_dropin mgmt)" ]]
    stub_called '^systemctl disable --quiet --now tacquito@mgmt.service$'
    refute_stub_called '^systemctl restart'
    run grep -c mgmt "$OVERRIDES" "$RENDERED"
    refute_output --regexp ':[1-9]'
    run "$TACCTL_BIN_SCRIPT" config listen --listener mgmt reset
    assert_failure
    assert_output --partial "No listener 'mgmt'."
    run "$TACCTL_BIN_SCRIPT" config listen --listener mgmt show
    assert_failure
    assert_output --partial "No listener 'mgmt'. Create it: tacctl config listen --listener mgmt tcp <address>"
}

@test "config listen --listener: an instance that does not come up is taken back out" {
    systemctl_fails_for 'tacquito@mgmt'
    run "$TACCTL_BIN_SCRIPT" config listen --listener mgmt tcp 127.0.0.1:4949
    assert_failure
    assert_output --partial "tacquito@mgmt failed to start. Restoring previous override."
    [[ ! -e "$OVERRIDES" && ! -e "$(instance_dropin mgmt)" ]]
    stub_called '^systemctl disable --quiet --now tacquito@mgmt.service$'
    run "$TACCTL_BIN_SCRIPT" config listen show
    refute_output --partial "mgmt"
}

@test "config listen: bad flags, listener names and backends are refused" {
    run "$TACCTL_BIN_SCRIPT" config listen --backend ldap show
    assert_failure
    assert_output --partial "Unknown backend 'ldap' (known: tacacs radius)."
    run "$TACCTL_BIN_SCRIPT" config listen --listener Bad_Name tcp :300
    assert_failure
    assert_output --partial "Invalid listener name 'Bad_Name'"
    run "$TACCTL_BIN_SCRIPT" config listen --listener
    assert_failure
    assert_output --partial "--listener needs a value"
    run "$TACCTL_BIN_SCRIPT" config listen bogus
    assert_failure
    assert_output --partial "Invalid subcommand: 'bogus'. Use: show, tcp, tcp6, or reset"
    [[ ! -e "$OVERRIDES" ]]
}

# --- loglevel and metrics are per backend ------------------------------------

@test "config loglevel: lives in tacctl.yaml and reaches every listener's drop-in" {
    "$TACCTL_BIN_SCRIPT" config listen --listener mgmt tcp 127.0.0.1:4949
    : > "$CALLS_LOG"
    run "$TACCTL_BIN_SCRIPT" config loglevel debug
    assert_success
    assert_output --partial "Log level changed to debug (30). Service restarted."
    grep -q 'level: 30' "$OVERRIDES"
    grep -qxF 'Environment="TACQUITO_LEVEL=30"' "$DROPIN"
    grep -qxF 'Environment="TACQUITO_LEVEL=30"' "$(instance_dropin mgmt)"
    # Restarting tacquito.service restarts the instances (PartOf); they are
    # also made sure to be enabled and running.
    stub_called '^systemctl restart tacquito$'
    stub_called '^systemctl enable --quiet --now tacquito@mgmt.service$'
    run "$TACCTL_BIN_SCRIPT" config loglevel
    assert_output --partial "Current log level: debug (30)"
    run "$TACCTL_BIN_SCRIPT" config loglevel debug
    assert_output --partial "Already at debug (30)."
    "$TACCTL_BIN_SCRIPT" config loglevel info
    run grep -c 'level' "$OVERRIDES"
    assert_output "0"
    grep -qxF 'Environment="TACQUITO_LEVEL=20"' "$DROPIN"
}

@test "config metrics: lives in tacctl.yaml; a bad address is refused with everything as it was" {
    run "$TACCTL_BIN_SCRIPT" config metrics address 10.1.0.1:9090
    assert_success
    grep -q 'metrics_address: 10.1.0.1:9090' "$OVERRIDES"
    grep -qxF 'Environment="TACQUITO_METRICS_ADDRESS=10.1.0.1:9090"' "$DROPIN"
    local before
    before=$(sha256sum "$DROPIN" "$OVERRIDES")
    : > "$CALLS_LOG"
    run "$TACCTL_BIN_SCRIPT" config metrics address "bad host:9090"
    assert_failure
    assert_output --partial "must be host:port"
    assert_output --partial "Nothing was changed."
    [[ "$(sha256sum "$DROPIN" "$OVERRIDES")" == "$before" ]]
    refute_stub_called '^systemctl'
}

# --- The contract verbs ------------------------------------------------------

@test "a user mutation still restarts tacquito once and touches no instance or drop-in" {
    "$TACCTL_BIN_SCRIPT" config render --force > /dev/null
    local before
    before=$(sha256sum "$DROPIN")
    : > "$CALLS_LOG"
    run "$TACCTL_BIN_SCRIPT" user disable alice
    assert_success
    run grep '^systemctl' "$CALLS_LOG"
    assert_output "systemctl restart tacquito"
    [[ "$(sha256sum "$DROPIN")" == "$before" ]]
}

# --- status and logs ---------------------------------------------------------
# (the port sent to enrolled Linux hosts: tests/integration/config_linux.bats)

status_stubs() {
    stub_cmd systemctl '
case "$1" in
  is-active) if [[ "$*" == *tacquito@down* ]]; then echo "failed"; exit 3; fi; echo "active"; exit 0 ;;
  show)
    case " $* " in
      *--property=ActiveEnterTimestamp*) echo "ActiveEnterTimestamp=Mon 2026-04-21 10:00:00 UTC" ;;
      *tacquito@mgmt*--property=MainPID*) echo "MainPID=5151" ;;
      *tacquito@down*--property=MainPID*) echo "MainPID=0" ;;
      *--property=MainPID*) echo "MainPID=4242" ;;
    esac
    ;;
  *) exit 0 ;;
esac'
    stub_cmd ss 'echo "LISTEN 0 128 *:4901 *:* users:((\"tacquito\",pid=4242,fd=3))"'
    stub_cmd ps 'echo "12345"'
    stub_cmd curl 'exit 7'
    stub_cmd journalctl
}

@test "status: one listener prints exactly the lines it always printed" {
    status_stubs
    stub_cmd ss 'echo "LISTEN 0 128 *:49 *:* users:((\"tacquito\",pid=4242,fd=3))"'
    run "$TACCTL_BIN_SCRIPT" status
    assert_success
    assert_line --regexp 'Service:.*active'
    assert_line --regexp 'PID:.* 4242$'
    assert_line --regexp 'Listening:.*\*:49'
    assert_line --regexp 'Log level:.* info \(20\)$'
    refute_output --partial "Listener "
    refute_output --partial "Accounting log ("
}

@test "status: each further listener has its own line, state and accounting log" {
    "$TACCTL_BIN_SCRIPT" config listen tcp 10.1.0.1:4901
    "$TACCTL_BIN_SCRIPT" config listen --listener mgmt tcp 127.0.0.1:4949
    "$TACCTL_BIN_SCRIPT" config listen --listener down tcp 127.0.0.1:4950
    "$TACCTL_BIN_SCRIPT" config loglevel debug
    printf 'a\nb\n' > "${TACCTL_LOG}/accounting.log"
    printf 'c\n' > "${TACCTL_LOG}/accounting-mgmt.log"
    status_stubs
    run "$TACCTL_BIN_SCRIPT" status
    assert_success
    # The default listener: the port looked for is the model's, not 49.
    assert_line --regexp 'Listening:.*\*:4901'
    refute_output --partial "port 49 not detected"
    assert_line --regexp 'Listener down:.*failed.* — tcp 127\.0\.0\.1:4950 \(tacquito@down\.service\)$'
    assert_line --regexp 'Listener mgmt:.*active.* — tcp 127\.0\.0\.1:4949 \(tacquito@mgmt\.service, PID 5151\)$'
    assert_line --regexp 'Log level:.* debug \(30\)$'
    assert_line --regexp 'Accounting log:.*\(2 entries\)$'
    assert_line --regexp 'Accounting log \(mgmt\):.*\(1 entries\)$'
    # Recent errors are read from every listener's unit.
    stub_called '^journalctl -u tacquito -u tacquito@down.service -u tacquito@mgmt.service --no-pager'
}

@test "status: a port nobody listens on is named" {
    "$TACCTL_BIN_SCRIPT" config listen tcp 10.1.0.1:4902
    status_stubs
    run "$TACCTL_BIN_SCRIPT" status
    assert_output --partial "port 4902 not detected"
}

@test "log tail: one listener calls journalctl as before; more listeners add their units" {
    stub_cmd journalctl
    run "$TACCTL_BIN_SCRIPT" log tail
    stub_called '^journalctl -u tacquito --no-pager -n 20$'
    "$TACCTL_BIN_SCRIPT" config listen --listener mgmt tcp 127.0.0.1:4949
    run "$TACCTL_BIN_SCRIPT" log tail 5
    stub_called '^journalctl -u tacquito -u tacquito@mgmt.service --no-pager -n 5$'
}
