#!/usr/bin/env bats
# The move of a legacy install into the store on 'tacctl upgrade', and the way
# back ('tacctl store rollback').
#
# cmd_upgrade itself shells out to git, go and systemd; what it does to the
# configuration is three functions, driven here in the order it calls them:
#
#   state_migrate          state directory (tests/integration/state_migrate.bats)
#   config_sync_existing   legacy migrations of tacquito.yaml, or a re-render
#   upgrade_store_flip     the gate: 0 flipped, 10 store already there, 20 stopped
#
# The gate needs the daemon binary for its load-smoke, so tests that expect a
# flip install a stand-in for it. A stop must leave tacquito.yaml byte for
# byte as it was, create no store, and never restart the daemon.

load ../helpers/setup
load ../helpers/tmpenv
load ../helpers/mocks
load ../helpers/fixtures

FIX="${BATS_TEST_DIRNAME}/../fixtures"
HASH="24326224313024616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161"

setup() {
    tacctl_tmpenv_init
    tacctl_mocks_init
    stub_cmd chown
    stub_cmd systemctl
    stub_cmd logger
    tacctl_source_lib
    LEGACY_DIR="${BACKUP_DIR}/legacy"
    FLIP_OUT="${BATS_TEST_TMPDIR}/flip.out"
    FLIP_RC=0
}

# --- helpers ---

# A stand-in for the tacquito binary: 'serve' loads any config, 'fatal'
# rejects it (see tests/unit/render_tacacs.bats).
fake_tacquito() {
    cat > "${TACCTL_BIN}/tacquito" <<SH
#!/usr/bin/env bash
case "$1" in
    serve)
        echo "INFO: main.go:135: serve on 127.0.0.1:40001" >&2
        echo "INFO: loader.go:241: updated all providers from config source" >&2
        exec sleep 30 ;;
    fatal)
        echo "FATAL: main.go:98: error fetching config; loader failed" >&2
        exit 0 ;;
esac
SH
    chmod +x "${TACCTL_BIN}/tacquito"
}

# The part of an upgrade that runs before the gate.
upgrade_sync() {
    state_migrate
    config_sync_existing
}

# Run the gate; its exit status lands in FLIP_RC and its output in FLIP_OUT.
flip() {
    FLIP_RC=0
    upgrade_store_flip > "$FLIP_OUT" 2>&1 || FLIP_RC=$?
}

sha() { sha256sum "$1" | cut -d' ' -f1; }

pre_store_files() {
    find "$LEGACY_DIR" -maxdepth 1 -type f -name 'tacquito.yaml.pre-store.*' 2>/dev/null | sort
}

# The install is in legacy read-only mode and the daemon was left alone:
# $1 = sha256 tacquito.yaml had before the gate ran.
assert_stopped() {
    [[ "$FLIP_RC" -eq 20 ]] || { cat "$FLIP_OUT"; false; }
    grep -q "Store migration stopped" "$FLIP_OUT"
    grep -q "legacy read-only mode" "$FLIP_OUT"
    [[ "$(sha "$CONFIG")" == "$1" ]]
    [[ ! -e "$STORE_FILE" && ! -e "$RENDERED_FILE" ]]
    [[ -z "$(pre_store_files)" ]]
    run stub_called '^systemctl'
    assert_failure
    run "$TACCTL_BIN_SCRIPT" user add zed superuser --hash "$HASH"
    assert_failure
    assert_output --partial "store not initialised"
    [[ "$(sha "$CONFIG")" == "$1" ]]
}

# --- the gate passes ---

@test "flip: a legacy install moves into the store; the old file is kept; the config is rendered and recorded" {
    fake_tacquito serve
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    upgrade_sync
    local before
    before=$(sha "$CONFIG")
    flip
    [[ "$FLIP_RC" -eq 0 ]] || { cat "$FLIP_OUT"; false; }

    run cat "$FLIP_OUT"
    assert_output --partial "    EQUIVALENT"
    assert_output --partial "daemon load-smoke:   OK"
    assert_output --partial "Store migration complete"
    assert_output --partial "tacctl store rollback"

    # The store: root-only. The config: rendered, readable by the service
    # group, and what rendered.json says it is.
    [[ "$(stat -c %a "$STORE_FILE")" == "600" ]]
    [[ "$(stat -c %a "$CONFIG")" == "640" ]]
    run head -1 "$CONFIG"
    assert_output --partial "GENERATED by tacctl"
    run rendered_check "$CONFIG"
    assert_output "ok"

    # Exactly one copy of the pre-flip file, byte-identical, 0600, named as
    # the plan says -- and no second 'drift' copy from the forced render.
    local pre
    pre=$(pre_store_files)
    [[ "$(wc -l <<< "$pre")" -eq 1 ]]
    [[ "$pre" =~ /tacquito\.yaml\.pre-store\.[0-9]{8}_[0-9]{6}$ ]]
    [[ "$(sha "$pre")" == "$before" ]]
    [[ "$(stat -c %a "$pre")" == "600" ]]
    [[ "$(find "$LEGACY_DIR" -type f | wc -l)" -eq 1 ]]

    # What the daemon is given is equivalent to what it had.
    run store_equiv_check "$pre" "$CONFIG"
    assert_success
    assert_output "EQUIVALENT"

    # The gate does not restart; cmd_upgrade does, once, after it.
    run stub_called '^systemctl'
    assert_failure
}

@test "flip: afterwards the install is fully working: validate is clean, nothing drifted, mutations apply" {
    fake_tacquito serve
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    upgrade_sync
    # The upgrade's 'files' phase, which runs before the gate: unit files and
    # the listener drop-in (tests/integration/units_convert.bats).
    _tacacs_units_install "$TACCTL_SRC" > /dev/null
    _tacacs_units_keep_discard
    flip
    [[ "$FLIP_RC" -eq 0 ]]
    run "$TACCTL_BIN_SCRIPT" config validate
    assert_success
    assert_line --regexp 'Rendered config:.* up to date$'
    refute_output --partial "DRIFT"
    refute_output --partial "not initialised"
    run "$TACCTL_BIN_SCRIPT" user add alice superuser --hash "$HASH"
    assert_success
    # Nothing left to adopt: the flip already rendered and recorded the file.
    refute_output --partial "Previous"
    grep -q 'name: alice' "$CONFIG"
    stub_called 'systemctl restart tacquito'
}

@test "flip: the gate judges the file as upgrade's legacy migrations leave it" {
    fake_tacquito serve
    place_fixture tacquito.legacy-exec.yaml
    # As it stands the file does not pass: it names the Cisco service 'exec'
    # and carries no command rules.
    run store_import --check
    assert_failure 1
    upgrade_sync
    flip
    [[ "$FLIP_RC" -eq 0 ]] || { cat "$FLIP_OUT"; false; }
    # The kept file is the migrated one, i.e. what the daemon was running.
    grep -q 'name: shell' "$(pre_store_files)"
}

# --- the gate stops ---

@test "stop: content the store cannot represent -- nothing is forced, nothing changes" {
    fake_tacquito serve
    place_fixture legacy.unrepresentable.yaml
    upgrade_sync
    local before
    before=$(sha "$CONFIG")
    flip
    assert_stopped "$before"
    run cat "$FLIP_OUT"
    assert_output --partial "Cannot be represented in the store"
    assert_output --partial "the check above did not pass"
    assert_output --partial "tacctl store import --check"
    refute_output --partial "Dropped (--force)"
    # Reads still work from the legacy file.
    run "$TACCTL_BIN_SCRIPT" user list
    assert_success
    assert_output --partial "mallory"
}

@test "stop: a clean import that is not equivalent (secrets out of specificity order) is not sorted to make it pass" {
    fake_tacquito serve
    place_fixture tacquito.multiscope.yaml
    upgrade_sync
    local before
    before=$(sha "$CONFIG")
    flip
    assert_stopped "$before"
    run cat "$FLIP_OUT"
    assert_output --partial "import + validate:   OK"
    assert_output --partial "NOT EQUIVALENT"
    assert_output --partial "the check above did not pass"
}

@test "stop: the daemon does not load the rendered config" {
    fake_tacquito fatal
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    upgrade_sync
    local before
    before=$(sha "$CONFIG")
    flip
    assert_stopped "$before"
    run cat "$FLIP_OUT"
    assert_output --partial "    EQUIVALENT"
    assert_output --partial "daemon load-smoke:   FAILED"
}

@test "stop: without the daemon binary the load-smoke cannot run, and a skipped smoke is not a pass" {
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    upgrade_sync
    local before
    before=$(sha "$CONFIG")
    # The check alone calls this a pass (smoke skipped)...
    run store_import --check
    assert_success
    assert_output --partial "daemon load-smoke:   SKIPPED"
    # ...the upgrade gate does not.
    flip
    assert_stopped "$before"
    run cat "$FLIP_OUT"
    assert_output --partial "the daemon load-smoke cannot run"
}

@test "stop: 'clean import, equivalence not proven' (check exit 3) is not a pass" {
    fake_tacquito serve
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    upgrade_sync
    local before
    before=$(sha "$CONFIG")
    store_render_hook() { return 2; }
    flip
    assert_stopped "$before"
    run cat "$FLIP_OUT"
    assert_output --partial "equivalence with ${CONFIG} was not proven"
}

@test "stop: no tacquito.yaml at all" {
    fake_tacquito serve
    state_migrate
    flip
    [[ "$FLIP_RC" -eq 20 ]]
    [[ ! -e "$STORE_FILE" && ! -e "$CONFIG" ]]
    run cat "$FLIP_OUT"
    assert_output --partial "there is no ${CONFIG} to import"
}

@test "stop: a render that fails after the import takes the store away again" {
    fake_tacquito serve
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    upgrade_sync
    local before
    before=$(sha "$CONFIG")
    tacacs_render_apply() { return 1; }
    flip
    [[ "$FLIP_RC" -eq 20 ]] || { cat "$FLIP_OUT"; false; }
    [[ "$(sha "$CONFIG")" == "$before" ]]
    [[ ! -e "$STORE_FILE" && ! -e "$RENDERED_FILE" ]]
    run cat "$FLIP_OUT"
    assert_output --partial "could not be rendered from the store (the store was removed again)"
    run stub_called '^systemctl'
    assert_failure
}

# --- re-runs ---

@test "re-run: a store that exists is never re-imported or overwritten" {
    fake_tacquito serve
    load_fixture tacquito.minimal.yaml
    "$TACCTL_BIN_SCRIPT" user add alice superuser --hash "$HASH" > /dev/null
    : > "$CALLS_LOG"
    local store_before config_before
    store_before=$(sha "$STORE_FILE")
    config_before=$(sha "$CONFIG")
    upgrade_sync
    flip
    [[ "$FLIP_RC" -eq 10 ]]
    [[ ! -s "$FLIP_OUT" ]]
    [[ "$(sha "$STORE_FILE")" == "$store_before" ]]
    [[ "$(sha "$CONFIG")" == "$config_before" ]]
    [[ "$CONFIG_SYNC_RENDERED" == "0" ]]
    [[ -z "$(pre_store_files)" ]]
}

@test "re-run: a second upgrade after a flip changes nothing" {
    fake_tacquito serve
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    upgrade_sync
    flip
    [[ "$FLIP_RC" -eq 0 ]]
    local tree_before tree_after
    tree_before=$(find "$TACCTL_ETC" "$TACCTL_STATE_DIR" -type f ! -name .store.lock -exec sha256sum {} + | sort)
    run upgrade_sync
    assert_success
    assert_output ""
    upgrade_sync
    [[ "$CONFIG_SYNC_RENDERED" == "0" ]]
    flip
    [[ "$FLIP_RC" -eq 10 ]]
    tree_after=$(find "$TACCTL_ETC" "$TACCTL_STATE_DIR" -type f ! -name .store.lock -exec sha256sum {} + | sort)
    [[ "$tree_before" == "$tree_after" ]]
}

@test "re-run: a stopped upgrade stops the same way again, and passes once the cause is gone" {
    fake_tacquito fatal
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    upgrade_sync
    local before
    before=$(sha "$CONFIG")
    flip
    [[ "$FLIP_RC" -eq 20 ]]
    upgrade_sync
    flip
    assert_stopped "$before"
    fake_tacquito serve
    upgrade_sync
    flip
    [[ "$FLIP_RC" -eq 0 ]] || { cat "$FLIP_OUT"; false; }
    [[ "$(sha "$(pre_store_files)")" == "$before" ]]
}

@test "re-run: an upgrade interrupted between writing the store and rendering is finished by the next one" {
    fake_tacquito serve
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    upgrade_sync
    local before
    before=$(sha "$CONFIG")
    # The state such an interruption leaves (also what a manual
    # 'tacctl store import' leaves): store written, legacy file still live.
    store_import > /dev/null
    [[ -f "$STORE_FILE" && ! -e "$RENDERED_FILE" ]]
    [[ "$(sha "$CONFIG")" == "$before" ]]

    run config_sync_existing
    assert_success
    assert_output --partial "is equivalent to what the store renders; replacing it with the rendered file"
    refute_output --partial "ERROR"
    config_sync_existing
    run rendered_check "$CONFIG"
    assert_output "ok"
    run head -1 "$CONFIG"
    assert_output --partial "GENERATED by tacctl"
    # The interrupted run's pre-store copy is the only copy.
    [[ "$(sha "$(pre_store_files)")" == "$before" ]]
    [[ "$(find "$LEGACY_DIR" -type f | wc -l)" -eq 1 ]]
    flip
    [[ "$FLIP_RC" -eq 10 ]]
}

@test "re-run: the first sync that renders asks for a restart; the gate's caller sees it" {
    fake_tacquito serve
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    upgrade_sync
    store_import > /dev/null
    config_sync_existing > /dev/null
    [[ "$CONFIG_SYNC_RENDERED" == "1" ]]
    config_sync_existing > /dev/null
    [[ "$CONFIG_SYNC_RENDERED" == "0" ]]
}

@test "legacy: a migration that changes tacquito.yaml asks for a restart; a second run does not" {
    place_fixture tacquito.legacy-exec.yaml
    state_migrate
    config_sync_existing > /dev/null
    [[ "$CONFIG_SYNC_RENDERED" == "1" ]]
    config_sync_existing > /dev/null
    [[ "$CONFIG_SYNC_RENDERED" == "0" ]]
}

@test "re-run: a store beside a never-rendered config that says something else leaves that config alone" {
    fake_tacquito serve
    place_fixture tacquito.multiscope.yaml
    upgrade_sync
    # Operator's own decision: import although the check does not pass.
    store_import > /dev/null
    local before
    before=$(sha "$CONFIG")
    run config_sync_existing
    assert_success
    assert_output --partial "is not proven equivalent to it; it was left as it is"
    assert_output --partial "tacctl config render --force"
    [[ "$(sha "$CONFIG")" == "$before" ]]
    [[ ! -e "$RENDERED_FILE" ]]
}

@test "re-run: a store beside a never-rendered, equivalent config is not adopted while the daemon cannot load the render" {
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    upgrade_sync
    store_import > /dev/null
    local before
    before=$(sha "$CONFIG")
    # No daemon binary: the load-smoke cannot run.
    run config_sync_existing
    assert_success
    assert_output --partial "it was left as it is"
    [[ "$(sha "$CONFIG")" == "$before" ]]
    fake_tacquito fatal
    run config_sync_existing
    assert_output --partial "it was left as it is"
    [[ "$(sha "$CONFIG")" == "$before" ]]
    [[ ! -e "$RENDERED_FILE" ]]
}

@test "re-run: with a store, a hand-edited rendered config is reported and left alone" {
    fake_tacquito serve
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    upgrade_sync
    flip
    echo "# hand edit" >> "$CONFIG"
    local before
    before=$(sha "$CONFIG")
    run config_sync_existing
    assert_success
    assert_output --partial "was edited since tacctl rendered it"
    assert_output --partial "tacquito.yaml was not re-rendered"
    [[ "$(sha "$CONFIG")" == "$before" ]]
}

# --- store rollback ---

# A flipped install; prints nothing. ORIGINAL holds the pre-flip sha256.
flipped_install() {
    fake_tacquito serve
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    upgrade_sync
    ORIGINAL=$(sha "$CONFIG")
    flip
    [[ "$FLIP_RC" -eq 0 ]]
    : > "$CALLS_LOG"
}

@test "rollback: restores the pre-store file, removes the store and the render record, restarts" {
    flipped_install
    run "$TACCTL_BIN_SCRIPT" store rollback <<< "y"
    assert_success
    assert_output --partial "Rolled back"
    assert_output --partial "legacy read-only mode"
    [[ "$(sha "$CONFIG")" == "$ORIGINAL" ]]
    [[ "$(stat -c %a "$CONFIG")" == "640" ]]
    [[ ! -e "$STORE_FILE" && ! -e "$RENDERED_FILE" ]]
    stub_called 'systemctl restart tacquito'
    # The store went into a snapshot first; the pre-store file is still there.
    run find "$BACKUP_DIR" -mindepth 2 -maxdepth 2 -name store.yaml
    [[ "$(wc -l <<< "$output")" -eq 1 && -n "$output" ]]
    [[ -n "$(pre_store_files)" ]]
    # Legacy read-only mode under the new code.
    run "$TACCTL_BIN_SCRIPT" user list
    assert_success
    assert_output --partial "engineer"
    run "$TACCTL_BIN_SCRIPT" user add zed superuser --hash "$HASH"
    assert_failure
    assert_output --partial "store not initialised"
}

@test "rollback: the next upgrade flips again and reuses the pre-store copy" {
    flipped_install
    "$TACCTL_BIN_SCRIPT" store rollback <<< "y" > /dev/null
    upgrade_sync
    flip
    [[ "$FLIP_RC" -eq 0 ]] || { cat "$FLIP_OUT"; false; }
    [[ "$(pre_store_files | wc -l)" -eq 1 ]]
}

@test "rollback: anything but 'y' at the prompt changes nothing" {
    flipped_install
    local store_before config_before
    store_before=$(sha "$STORE_FILE")
    config_before=$(sha "$CONFIG")
    run "$TACCTL_BIN_SCRIPT" store rollback <<< "n"
    assert_success
    assert_output --partial "Cancelled."
    [[ "$(sha "$STORE_FILE")" == "$store_before" ]]
    [[ "$(sha "$CONFIG")" == "$config_before" ]]
    [[ -f "$RENDERED_FILE" ]]
    run stub_called '^systemctl'
    assert_failure
}

@test "rollback: says so when the store changed since the import; the change survives in the snapshot" {
    flipped_install
    "$TACCTL_BIN_SCRIPT" user add alice superuser --hash "$HASH" > /dev/null
    run "$TACCTL_BIN_SCRIPT" store rollback <<< "y"
    assert_success
    assert_output --partial "The store no longer says what the pre-store file says"
    [[ "$(sha "$CONFIG")" == "$ORIGINAL" ]]
    run grep -l 'alice' "$BACKUP_DIR"/*/store.yaml
    assert_success
}

@test "rollback: an unchanged store draws no such warning" {
    flipped_install
    run "$TACCTL_BIN_SCRIPT" store rollback <<< "n"
    refute_output --partial "no longer says"
}

@test "rollback: a hand-edited rendered config is kept under backups/legacy first" {
    flipped_install
    echo "# hand edit" >> "$CONFIG"
    run "$TACCTL_BIN_SCRIPT" store rollback <<< "y"
    assert_success
    run grep -l '# hand edit' "$LEGACY_DIR"/tacquito.yaml.drift.*
    assert_success
    [[ "$(sha "$CONFIG")" == "$ORIGINAL" ]]
}

@test "rollback: refuses when there is no store" {
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    local before
    before=$(sha "$CONFIG")
    run "$TACCTL_BIN_SCRIPT" store rollback <<< "y"
    assert_failure 1
    assert_output --partial "already in legacy read-only mode"
    [[ "$(sha "$CONFIG")" == "$before" ]]
    run stub_called '^systemctl'
    assert_failure
}

@test "rollback: refuses on an install that never had a legacy file, and leaves its store alone" {
    stub_cmd openssl 'echo 0123456789abcdef0123456789abcdef'
    state_migrate
    install_seed_config > /dev/null
    : > "$CALLS_LOG"
    local store_before config_before
    store_before=$(sha "$STORE_FILE")
    config_before=$(sha "$CONFIG")
    run "$TACCTL_BIN_SCRIPT" store rollback <<< "y"
    assert_failure 1
    assert_output --partial "there is nothing to roll back to"
    assert_output --partial "The store was left untouched"
    [[ "$(sha "$STORE_FILE")" == "$store_before" ]]
    [[ "$(sha "$CONFIG")" == "$config_before" ]]
    [[ -f "$RENDERED_FILE" ]]
    run stub_called '^systemctl'
    assert_failure
}

@test "rollback: refuses a pre-store file that cannot be read as a config" {
    flipped_install
    printf 'users: [unterminated\n' > "$(pre_store_files)"
    local store_before config_before
    store_before=$(sha "$STORE_FILE")
    config_before=$(sha "$CONFIG")
    run "$TACCTL_BIN_SCRIPT" store rollback <<< "y"
    assert_failure 1
    assert_output --partial "cannot be read as a tacquito.yaml. Nothing was changed."
    [[ "$(sha "$STORE_FILE")" == "$store_before" ]]
    [[ "$(sha "$CONFIG")" == "$config_before" ]]
}

@test "rollback: ignores a symlink and takes the newest pre-store file" {
    flipped_install
    printf 'older\n' > "${LEGACY_DIR}/tacquito.yaml.pre-store.20200101_000000"
    ln -s /etc/passwd "${LEGACY_DIR}/tacquito.yaml.pre-store.99990101_000000"
    run "$TACCTL_BIN_SCRIPT" store rollback <<< "y"
    assert_success
    [[ "$(sha "$CONFIG")" == "$ORIGINAL" ]]
}

@test "rollback: takes no arguments" {
    flipped_install
    run "$TACCTL_BIN_SCRIPT" store rollback --force
    assert_failure 2
    assert_output --partial "Usage: tacctl store rollback"
    [[ -f "$STORE_FILE" ]]
}

@test "rollback: superuser only" {
    run tier_permits superuser store rollback
    assert_success
    run tier_permits operator store rollback
    assert_failure
    run tier_permits readonly store rollback
    assert_failure
}

# --- the pre-store copy is made by the import itself ---

@test "import: the first import of the live config keeps it, so a manual import can be rolled back too" {
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    local before
    before=$(sha "$CONFIG")
    run "$TACCTL_BIN_SCRIPT" store import
    assert_success
    assert_output --partial "Pre-store ${CONFIG} kept as ${LEGACY_DIR}/tacquito.yaml.pre-store."
    [[ "$(sha "$(pre_store_files)")" == "$before" ]]
    "$TACCTL_BIN_SCRIPT" config render --force > /dev/null
    [[ "$(find "$LEGACY_DIR" -type f | wc -l)" -eq 1 ]]
    run "$TACCTL_BIN_SCRIPT" store rollback <<< "y"
    assert_success
    [[ "$(sha "$CONFIG")" == "$before" ]]
}

@test "import: --check, another file, and --replace keep no pre-store copy" {
    cp "${FIX}/legacy.fresh-install.yaml" "$CONFIG"
    run "$TACCTL_BIN_SCRIPT" store import --check
    [[ -z "$(pre_store_files)" ]]
    "$TACCTL_BIN_SCRIPT" store import "${FIX}/tacquito.minimal.yaml" > /dev/null
    [[ -z "$(pre_store_files)" ]]
    "$TACCTL_BIN_SCRIPT" store import --replace > /dev/null
    [[ -z "$(pre_store_files)" ]]
}
