# shellcheck shell=bash
# tacctl lib/conf.sh -- tacctl.yaml: defaults, schema, read/write API, source-time tunables, tunable setters, config dump
# Sourced by bin/tacctl.sh (see the load block there for ordering); not executable.

# =====================================================================
#  Unified config (tacctl.yaml + in-script defaults)
# =====================================================================
#
# Canonical defaults live in conf_emit_defaults() below — the single
# source of truth for shipped tunables. Operator overrides live in
# $TACCTL_OVERRIDES_FILE (default /etc/tacquito/tacctl.yaml); only keys
# the operator has changed appear there.
#
# Reads deep-merge the two (scalars + lists override, maps union-merge),
# cached once per invocation in $_TACCTL_CFG_CACHE (merged JSON string).
# Writes mutate the overrides file and invalidate the cache. A write
# equal to the default removes the key (revert-to-default); an overrides
# file with no keys left is pruned.
#
#   conf_get <dotted.path> [fallback]           -> scalar, one line
#   conf_get_list <dotted.path>                 -> newline-joined list
#   conf_get_keys <dotted.path>                 -> keys of a map, one per line
#   conf_set <dotted.path> <value>              -> scalar write
#   conf_set_list <dotted.path> [newline-items] -> list write (items on stdin)
#   conf_unset <dotted.path>                    -> delete key from overrides
#   conf_emit_defaults                          -> canonical defaults as YAML
#   conf_is_default <dotted.path> <value>       -> 0 if value equals default

# --- Canonical defaults ---
# The ONE source of truth for shipped tunables. Every entry here is also
# validated by _CONF_SCHEMA below; add new tunables in both places.
conf_emit_defaults() {
    cat <<'YAML'
# tacctl canonical defaults (emitted by `tacctl config defaults`).
# DO NOT edit this output — it is generated by conf_emit_defaults() in
# bin/tacctl.sh. Override any key in /etc/tacquito/tacctl.yaml.

password:
  max_age_days: 90        # warning threshold used by `tacctl status`
  min_length: 12          # floor for interactively-typed passwords

secret:
  min_length: 16          # floor for operator-typed shared secrets

bcrypt:
  cost: 12                # applies to new hashes; range 10..14

scope:
  default: lab            # matches the fresh-install seed scope; override via `tacctl scope default <name>`

host:
  default_method: tacplus # how `tacctl host enroll` sets up a new Linux host: tacplus | radius

mgmt_acl:
  names:
    cisco: VTY-ACL        # ACL name emitted by `tacctl config cisco`
    juniper: MGMT-ACL # filter name emitted by `tacctl config juniper`
  permits: []             # CIDRs for Cisco VTY-ACL + Juniper lo0 filter

privileges:
  # Per-group Cisco priv-exec lists. Shipped defaults move only
  # verified priv-15 commands DOWN to lower-privilege groups; they
  # never move commands UP from a lower default level (which would
  # silently restrict readonly users). Override any list in tacctl.yaml.
  operator:
    # Shipped priv-15 read/diagnostic commands lowered to priv-7 so
    # commands.operator's `show` permit is actually reachable for
    # common read paths. No write/configure/debug included.
    - show running-config
    - show startup-config
    - show tech-support
    - show archive
    - show access-list
    - show ip route

commands:
  # Per-group per-command authorization rules. tacctl.yaml is the ONE
  # source of truth; tacquito.yaml's per-group `commands:` block is
  # regenerated from this section on every mutation, and
  # `tacctl config juniper` renders the same rules as class-level
  # allow-commands / deny-commands for Junos.
  #
  # Each rule: {name, action: permit|deny, match: [regex, ...]}
  # `name` is compared literally against the TACACS+ cmd= word. `match`
  # regexes are applied by tacquito to the command's ARGUMENTS only —
  # the space-joined cmd-arg values after the cmd word, e.g. for
  # `show running-config` the string tested is `running-config`, not
  # the full line. A regex that repeats the command word (`^show .*$`)
  # can therefore never match and silently denies every invocation.
  # Omit `match` to permit/deny the command with any arguments.
  # A trailing name: "*" entry is the catch-all; its action is the
  # group's default action.
  #
  # Ordered superuser → operator → readonly to match how a reader scans
  # privilege from most-to-least permissive.
  superuser:
    # Priv 15 + RW-CLASS — unrestricted by policy.
    - { name: "*", action: permit }
  operator:
    # Read-only + diagnostics; everything else (configure, write,
    # debug, reload, etc.) hits the deny catch-all.
    - { name: show,       action: permit }
    - { name: ping,       action: permit }
    - { name: traceroute, action: permit }
    - { name: terminal,   action: permit }
    - { name: "*",        action: deny }
  readonly:
    # Defense in depth on top of priv-1 / RO-CLASS. Permits are the
    # read / diagnostic subset of operator's; `terminal` is omitted
    # (terminal monitor can leak debug output across sessions).
    - { name: show,       action: permit }
    - { name: ping,       action: permit }
    - { name: traceroute, action: permit }
    - { name: "*",        action: deny }
YAML
}

# --- Cache control ---------------------------------------------------------
# _TACCTL_CFG_CACHE holds the merged defaults+overrides as a JSON string.
# Empty = cold cache (next read re-merges). _conf_invalidate is called from
# every write path so subsequent reads see the mutation.
_TACCTL_CFG_CACHE=""
# It also drops the list of enabled backends (lib/backend.sh), which is read
# from the same file.
_conf_invalidate() { _TACCTL_CFG_CACHE=""; _BACKENDS_LOADED=0; }

_conf_load_cache() {
    [[ -n "$_TACCTL_CFG_CACHE" ]] && return 0
    # One python invocation: load defaults (from conf_emit_defaults output
    # on a throwaway fd) + overrides file, deep-merge, dump as JSON to
    # stdout. The merged JSON stays small (<2 KB for typical installs).
    _TACCTL_CFG_CACHE=$(python3 - <(conf_emit_defaults) "${TACCTL_OVERRIDES_FILE:-}" <<'PY'
import json, os, sys, yaml
defaults_path, overrides_path = sys.argv[1:3]
def load(p):
    if p and os.path.exists(p):
        try:
            with open(p) as f:
                return yaml.safe_load(f) or {}
        except Exception:
            return {}
    return {}
def merge(a, b):
    out = dict(a)
    for k, v in (b or {}).items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = merge(out[k], v)
        else:
            out[k] = v
    return out
print(json.dumps(merge(load(defaults_path), load(overrides_path))))
PY
)
}

# Walk the cached merged view along a dotted path.
# mode: get | get_list | get_keys.
_conf_walk() {
    local mode="$1" path="$2" fallback="${3:-}"
    _conf_load_cache
    python3 -c '
import json, sys
data = json.loads(sys.argv[1])
mode, path, fallback = sys.argv[2], sys.argv[3], sys.argv[4]
cur = data
for part in (path.split(".") if path else []):
    if isinstance(cur, dict) and part in cur:
        cur = cur[part]
    else:
        cur = None
        break
if mode == "get":
    if cur is None:
        print(fallback)
    elif isinstance(cur, bool):
        print("true" if cur else "false")
    elif isinstance(cur, (list, dict)):
        pass  # caller should use get_list / get_keys
    else:
        print(cur)
elif mode == "get_list":
    if isinstance(cur, list):
        for item in cur:
            print(item)
elif mode == "get_keys":
    if isinstance(cur, dict):
        for k in cur.keys():
            print(k)
' "$_TACCTL_CFG_CACHE" "$mode" "$path" "$fallback"
}

conf_get()      { _conf_walk get      "$1" "${2:-}"; }
conf_get_list() { _conf_walk get_list "$1"; }
conf_get_keys() { _conf_walk get_keys "$1"; }

# --- Schema for write-time validation --------------------------------------
# The ONE source of truth for what's legal in tacctl.yaml. Emitted as a
# Python literal so both _conf_write (mutation-time) and
# _conf_validate_overrides_file (scan-time) can import it unchanged.
#
# Types: int (with optional min/max), string (with optional regex pattern
# + optional max_length), nullable_string (string or null), cidr_list,
# cisco_cmd_list, backend_list, host_port, listener, string_scalar. The
# `pattern` is a Python regex.

# --- Listener model (plan 3.4) ---------------------------------------------
# listeners.<backend>.<name> in tacctl.yaml says where a backend's daemon
# listens:
#
#   listeners:
#     tacacs:
#       default: { network: tcp, address: ":49" }
#       mgmt:    { network: tcp, address: "10.1.0.1:4949" }
#
# Keys: network (tcp|tcp6|udp|udp6), address (host:port, [v6]:port or :port),
# role (auth|acct|both), metrics_address (host:port; a daemon that exports
# metrics per process), and tls {enabled, cert, key, ca,
# require_client_cert}. The tls block is reserved: its fields are accepted so
# that TACACS+ over TLS needs no schema change, and 'enabled: true' is
# refused until a release implements it.
#
# LISTENER_BACKENDS says what each backend's daemon can do and which
# listeners exist without being written down ('defaults'); a listener named
# there can be changed and reset but not removed. Python shared by the schema
# below and by the backends' renderers.
_listener_py() {
    cat <<'PY'
import ipaddress, re

LISTENER_BACKENDS = {
    # One tacquito process serves one stream listener, authentication and
    # accounting together.
    'tacacs': {'networks': ('tcp', 'tcp6'), 'roles': ('both',),
               'defaults': {'default': {'network': 'tcp', 'address': ':49'}}},
    # One FreeRADIUS process serves every listener; a listener answers
    # authentication or accounting, never both (a listener written without a
    # role is an authentication one).
    'radius': {'networks': ('udp', 'udp6'), 'roles': ('acct', 'auth'),
               'defaults': {'auth': {'network': 'udp', 'address': ':1812', 'role': 'auth'},
                            'acct': {'network': 'udp', 'address': ':1813', 'role': 'acct'}}},
}
LISTENER_NETWORKS = ('tcp', 'tcp6', 'udp', 'udp6')
LISTENER_ROLES = ('auth', 'acct', 'both')
LISTENER_KEYS = ('network', 'address', 'role', 'metrics_address', 'tls')
LISTENER_TLS_KEYS = ('enabled', 'cert', 'key', 'ca', 'require_client_cert')
RE_LISTENER_NAME = re.compile(r'[a-z][a-z0-9_-]{0,31}')
RE_HOST_PORT = re.compile(r'(\[[0-9A-Fa-f:.]+\]|[A-Za-z0-9.-]*):([0-9]{1,5})')
WILDCARD_HOSTS = ('', '0.0.0.0', '::')


def split_listen_address(addr):
    """'host:port' or '[v6]:port' -> (host, port); None when it is neither."""
    if not isinstance(addr, str):
        return None
    m = re.fullmatch(r'\[([^\]]+)\]:(\d+)', addr) or re.fullmatch(r'([^:]*):(\d+)', addr)
    if not m:
        return None
    return m.group(1), int(m.group(2))


def listen_address_problem(network, addr):
    """'' when addr is a listen address of the network's family, else why not.
    The host is empty (every address) or an IP literal, never a name."""
    parts = split_listen_address(addr)
    if parts is None:
        return 'must be host:port, [ipv6]:port or :port'
    host, port = parts
    if not 1 <= port <= 65535:
        return 'port must be 1..65535'
    if host:
        try:
            ip = ipaddress.ip_address(host)
        except ValueError:
            return f'{host!r} is not an IP address'
        if network in ('tcp', 'udp') and ip.version != 4:
            return f'{network} takes an IPv4 address ({network}6 for IPv6)'
        if network in ('tcp6', 'udp6') and ip.version != 6:
            return f'{network} takes an IPv6 address in brackets'
    return ''


def host_port_problem(value):
    """'' when value is host:port (host may be empty or a name; port 0 is
    the kernel's choice), else why not."""
    if not isinstance(value, str):
        return 'must be a string host:port'
    m = RE_HOST_PORT.fullmatch(value)
    if not m:
        return "must be host:port (e.g. '127.0.0.1:8080' or ':8080')"
    if int(m.group(2)) > 65535:
        return 'port must be 0..65535'
    return ''


def listener_normalize(backend, value):
    """Every key present, defaults filled in. value must have passed
    listener_problem."""
    spec = LISTENER_BACKENDS[backend]
    tls = value.get('tls') or {}
    return {
        'network': value.get('network') or spec['networks'][0],
        'address': value['address'],
        'role': value.get('role') or spec['roles'][-1],
        'metrics_address': value.get('metrics_address') or '',
        'tls': {
            'enabled': False,
            'cert': tls.get('cert') or '',
            'key': tls.get('key') or '',
            'ca': tls.get('ca') or '',
            'require_client_cert': bool(tls.get('require_client_cert')),
        },
    }


def listener_compact(backend, value):
    """What tacctl.yaml stores: only what differs from the defaults."""
    spec = LISTENER_BACKENDS[backend]
    full = listener_normalize(backend, value)
    out = {'network': full['network'], 'address': full['address']}
    if full['role'] != spec['roles'][-1]:
        out['role'] = full['role']
    if full['metrics_address']:
        out['metrics_address'] = full['metrics_address']
    tls = {k: v for k, v in full['tls'].items() if v}
    if tls:
        out['tls'] = tls
    return out


def listener_problem(backend, name, value):
    """'' when value is a valid listeners.<backend>.<name>, else why not."""
    spec = LISTENER_BACKENDS.get(backend)
    if spec is None:
        return f"'{backend}' is not a backend with listeners (known: {', '.join(LISTENER_BACKENDS)})"
    if not RE_LISTENER_NAME.fullmatch(name):
        return 'a listener name is a lowercase letter, then up to 31 of [a-z0-9_-]'
    if not isinstance(value, dict):
        return 'must be a mapping {network, address, role?, metrics_address?, tls?}'
    extra = sorted(set(value) - set(LISTENER_KEYS))
    if extra:
        return f"unknown keys {extra} (known: {', '.join(LISTENER_KEYS)})"
    network = value.get('network', spec['networks'][0])
    if network not in LISTENER_NETWORKS:
        return f"network must be one of {', '.join(LISTENER_NETWORKS)} (got {network!r})"
    if network not in spec['networks']:
        return f"the {backend} backend listens on {' or '.join(spec['networks'])} only (got {network})"
    if 'address' not in value:
        return 'address is required'
    why = listen_address_problem(network, value['address'])
    if why:
        return f"address {value['address']!r}: {why}"
    role = value.get('role', spec['roles'][-1])
    if role not in LISTENER_ROLES:
        return f"role must be one of {', '.join(LISTENER_ROLES)} (got {role!r})"
    if role not in spec['roles']:
        return f"a {backend} listener has role {' or '.join(spec['roles'])} (got {role})"
    if value.get('metrics_address') not in (None, ''):
        why = host_port_problem(value['metrics_address'])
        if why:
            return f'metrics_address: {why}'
    tls = value.get('tls')
    if tls is not None:
        if not isinstance(tls, dict):
            return f"tls must be a mapping {{{', '.join(LISTENER_TLS_KEYS)}}}"
        extra = sorted(set(tls) - set(LISTENER_TLS_KEYS))
        if extra:
            return f"tls: unknown keys {extra} (known: {', '.join(LISTENER_TLS_KEYS)})"
        for k in ('enabled', 'require_client_cert'):
            if not isinstance(tls.get(k, False), bool):
                return f'tls.{k} must be true or false'
        for k in ('cert', 'key', 'ca'):
            if not isinstance(tls.get(k, ''), str):
                return f'tls.{k} must be a file path'
        if tls.get('enabled'):
            return 'tls.enabled: true is reserved for a future release (TLS listeners are not implemented)'
    return ''


def listeners_effective(doc, backend):
    """{name: normalized listener} for one backend: the built-in ones
    (as overridden), then the others by name. An entry that does not
    validate is left out, or falls back to the built-in one of its name;
    listeners_problems names it."""
    spec = LISTENER_BACKENDS.get(backend) or {'defaults': {}}
    section = ((doc or {}).get('listeners') or {})
    mine = section.get(backend) if isinstance(section, dict) else None
    mine = mine if isinstance(mine, dict) else {}
    out = {}
    for name in list(spec['defaults']) + sorted(n for n in mine if isinstance(n, str) and n not in spec['defaults']):
        value = mine.get(name)
        if value is None or listener_problem(backend, name, value):
            value = spec['defaults'].get(name)
        if value is not None:
            out[name] = listener_normalize(backend, value)
    return out


def _binds_collide(a, b):
    """Two listeners that cannot both bind: same transport and port, and
    the same host or a wildcard on either side (':49' is every address of
    both families)."""
    if a['network'][:3] != b['network'][:3]:
        return False
    # FreeRADIUS, the one udp daemon, binds a socket per family: udp ':1812'
    # is IPv4 only and does not take the port from a udp6 listener.
    if a['network'][:3] == 'udp' and a['network'] != b['network']:
        return False
    (ha, pa), (hb, pb) = split_listen_address(a['address']), split_listen_address(b['address'])
    if pa != pb:
        return False
    if ha in WILDCARD_HOSTS or hb in WILDCARD_HOSTS:
        return True
    return ipaddress.ip_address(ha) == ipaddress.ip_address(hb)


def listeners_problems(doc, only=None):
    """Every problem of the listeners section of a tacctl.yaml document, as
    '<path>: <reason>' strings: invalid entries, and two listeners (of any
    backends) on one network and address. With only=<path>, the problems of
    that one listener, a collision told from its side."""
    problems = []
    section = (doc or {}).get('listeners')
    if section is None:
        section = {}
    if not isinstance(section, dict):
        return ['listeners: must be a mapping of backends']
    for backend, mine in section.items():
        if not isinstance(mine, dict):
            problems.append(f'listeners.{backend}: must be a mapping of listener names')
            continue
        for name, value in mine.items():
            why = listener_problem(str(backend), str(name), value)
            if why:
                problems.append(f'listeners.{backend}.{name}: {why}')
    if only is not None:
        problems = [p for p in problems if p.startswith(only + ':')]
    seen = []
    for backend in LISTENER_BACKENDS:
        for name, l in listeners_effective(doc, backend).items():
            path = f'listeners.{backend}.{name}'
            for other_path, other in seen:
                if only is not None and only not in (path, other_path):
                    continue
                # Told from the later listener's side, or from only's.
                (pa, a), (pb, b) = ((other_path, other), (path, l)) if only == other_path else ((path, l), (other_path, other))
                if _binds_collide(a, b):
                    problems.append(f"{pa}: {a['network']} {a['address']} is already used by {pb} ({b['network']} {b['address']})")
                if a['metrics_address'] and a['metrics_address'] == b['metrics_address'] \
                        and not a['metrics_address'].endswith(':0'):
                    problems.append(f"{pa}: metrics_address {a['metrics_address']} is already used by {pb}")
            seen.append((path, l))
    return problems

PY
}

_conf_schema_py() {
    _listener_py
    # The registered backends (lib/backend.sh) as a Python list literal.
    local ids="" id
    for id in ${BACKEND_IDS[@]+"${BACKEND_IDS[@]}"}; do
        ids+="${ids:+, }'${id}'"
    done
    sed "s/@BACKEND_IDS@/[${ids}]/" <<'PY'
SCHEMA = {
    'password.max_age_days': {'type': 'int', 'min': 1},
    'password.min_length':   {'type': 'int', 'min': 8,  'max': 64},
    'secret.min_length':     {'type': 'int', 'min': 16, 'max': 128},
    'bcrypt.cost':           {'type': 'int', 'min': 10, 'max': 14},
    'scope.default':         {'type': 'nullable_string',
                              'pattern': r'^[a-zA-Z][a-zA-Z0-9_-]{0,31}$'},
    'host.default_method':   {'type': 'enum', 'values': ['tacplus', 'radius']},
    'mgmt_acl.names.cisco':  {'type': 'acl_name'},
    'mgmt_acl.names.juniper':{'type': 'acl_name'},
    'mgmt_acl.permits':      {'type': 'cidr_list'},
    # Backends that serve the model, in render and restart order. 'values' is
    # the registry (BACKEND_IDS, lib/backend.sh: every module in lib/backends/
    # registers itself), substituted when the schema is emitted, so a new
    # module needs no edit here. Not in conf_emit_defaults: 'default' below is
    # the shipped value, as for the wildcard entries, and
    # BACKENDS_DEFAULT_ENABLED in lib/backend.sh mirrors it (a unit test pins
    # both).
    'backends.enabled':      {'type': 'backend_list',
                              'values': @BACKEND_IDS@,
                              'default': ['tacacs']},
    # Per-backend daemon settings ('tacctl config loglevel|metrics'). They
    # apply to every listener's process; tacquito takes 10 (error), 20 (info)
    # or 30 (debug). The metrics address is the default listener's; another
    # listener exports metrics only when it sets metrics_address itself.
    'backends.tacacs.level': {'type': 'int', 'min': 0, 'max': 100, 'default': 20},
    'backends.tacacs.metrics_address':
                             {'type': 'host_port', 'default': '127.0.0.1:8080'},
}
# Wildcard paths: each operator-created group/scope gets its own entry
# under privileges.<group>, commands.<group>, aaa.order.<scope>. The
# matcher below accepts any lowercase-start name as the single trailing
# path segment and validates the value against the rule type.
WILDCARDS = [
    ('privileges.',   {'type': 'cisco_cmd_list'}),
    ('commands.',     {'type': 'command_rules'}),
    ('aaa.order.',    {'type': 'enum',
                       'values': ['tacacs-first', 'local-first'],
                       # Implicit per-instance default. _conf_write uses
                       # this to prune the override when the set value
                       # matches (scopes aren't pre-enumerated in
                       # conf_emit_defaults, so we can't rely on
                       # get_nested(defaults, ...) to tell us the default).
                       'default': 'tacacs-first'}),
    ('exec_timeout.', {'type': 'int',
                       # 0 = never expire (Cisco: `exec-timeout 0 0`).
                       # Junos `idle-timeout` max is 60 minutes, so the
                       # upper bound is set to what both vendors accept
                       # cleanly with one knob.
                       'min': 0, 'max': 60,
                       'default': 60}),
    ('tacacs_group.', {'type': 'acl_name',
                       # Cisco `aaa group server tacacs+ <name>` label.
                       # Default 'TACACS-GROUP' is what the template
                       # shipped before this knob existed. Per-scope
                       # override lets operators match site naming
                       # conventions (e.g. TACACS_PROD, ISE-GROUP).
                       # acl_name type enforces letter-start +
                       # [A-Za-z0-9_-] which is what IOS accepts.
                       'default': 'TACACS-GROUP'}),
    ('radius_group.', {'type': 'acl_name',
                       # The RADIUS twin of tacacs_group.<scope>: the
                       # Cisco `aaa group server radius <name>` label
                       # `config cisco --protocol radius` renders. Same
                       # naming rules, own default.
                       'default': 'RADIUS-GROUP'}),
    ('scope_auth_method.',
                      {'type': 'enum',
                       # The protocol a scope's devices and hosts use
                       # when the command is given none ('tacctl scope
                       # auth-method'): `config cisco|juniper` without
                       # --protocol, `host enroll` and `config linux
                       # script` without --method. No default here on
                       # purpose: an unset key means "not decided for
                       # this scope" (devices: tacacs; hosts:
                       # host.default_method), which an explicit
                       # 'tacacs' is not.
                       'values': ['tacacs', 'radius']}),
    # Per-scope mgmt-ACL overrides. These live under a separate
    # `scope_mgmt_acl.*` top-level namespace rather than extending
    # `mgmt_acl.*`, because the global `mgmt_acl.permits` is a list
    # and `mgmt_acl.names.{cisco,juniper}` are scalars — nesting
    # `<scope>` under either would require set_nested to silently
    # reshape list->dict / scalar->dict and wipe the global value.
    # The render code walks: scope_mgmt_acl.permits.<scope> ->
    # mgmt_acl.permits (global) -> shipped default, same for names.
    ('scope_mgmt_acl.names.cisco.',
                      {'type': 'acl_name', 'default': 'VTY-ACL'}),
    ('scope_mgmt_acl.names.juniper.',
                      {'type': 'acl_name', 'default': 'MGMT-ACL'}),
    # Default [] so an explicit empty list prunes the override and
    # renders fall through to the global `mgmt_acl.permits`.
    ('scope_mgmt_acl.permits.',
                      {'type': 'cidr_list', 'default': []}),
    # listeners.<backend>.<name>: two trailing segments, and the value is a
    # mapping (see _listener_py). Its default is per name, from
    # LISTENER_BACKENDS.
    ('listeners.',    {'type': 'listener', 'depth': 2}),
]

import re

CMD_RE = re.compile(r'^[a-zA-Z][a-zA-Z0-9 _-]+$')

def command_match_is_dead(name, rx):
    """True when a command-rule `match` regex can never match.

    tacquito's CommandBasedAuthorizer compares a rule's `name` to the
    TACACS+ cmd= word and then tests each `match` regex against the
    space-joined cmd-arg values ONLY (`show running-config` is tested
    as 'running-config'). A regex that begins with the command word
    itself -- `^show .*$`, `^ping( .*)?$`, `^show$` -- would only ever
    match an argument string that repeats the command, so the rule is
    dead and every invocation falls through to the next rule (usually
    the deny catch-all). Used at write time, by `group commands add`,
    and by the upgrade migration that heals older configs.
    """
    if not isinstance(name, str) or name == '*' or not isinstance(rx, str):
        return False
    body = rx[1:] if rx.startswith('^') else rx
    tail = r'(?:\s|\\s|\$|\((?:\?:)?(?:\s|\\s))'
    return re.match(re.escape(name) + tail, body) is not None

def schema_for(path):
    if path in SCHEMA:
        return SCHEMA[path]
    for prefix, rule in WILDCARDS:
        if not path.startswith(prefix):
            continue
        # Reject empty names (just the prefix itself, or an empty segment).
        parts = path[len(prefix):].split('.')
        if len(parts) == rule.get('depth', 1) and all(parts):
            return rule
    return None

def implicit_default(path):
    """Return the implicit per-instance default for a wildcard schema
    entry (e.g. aaa.order.<scope> -> 'tacacs-first'), or None if the path
    has no implicit default. Used by _conf_write's revert-to-default
    prune so operators can unset a wildcard override by re-setting it to
    the default value."""
    rule = schema_for(path)
    if rule is None:
        return None
    if rule['type'] == 'listener':
        _, backend, name = path.split('.')
        return (LISTENER_BACKENDS.get(backend) or {'defaults': {}})['defaults'].get(name)
    return rule.get('default')

def validate(path, value, is_list):
    """Return (ok: bool, msg: str). msg is empty on success."""
    rule = schema_for(path)
    if rule is None:
        return False, f"unknown config key (typo? path must be one of the known tunables)"
    t = rule['type']

    if is_list and t not in ('cidr_list', 'cisco_cmd_list', 'command_rules', 'backend_list'):
        return False, f"{t} does not accept list input; drop 'set-list'"
    if not is_list and t in ('cidr_list', 'cisco_cmd_list', 'command_rules', 'backend_list'):
        return False, f"{t} requires list input (use conf_set_list)"

    if t == 'int':
        if not isinstance(value, int) or isinstance(value, bool):
            return False, f"must be an integer"
        lo, hi = rule.get('min'), rule.get('max')
        if lo is not None and value < lo:
            return False, f"must be >= {lo}; got {value}"
        if hi is not None and value > hi:
            return False, f"must be <= {hi}; got {value}"
        return True, ''
    if t == 'nullable_string':
        if value is None:
            return True, ''
        if not isinstance(value, str):
            return False, f"must be a string or null"
        p = rule.get('pattern')
        if p and not re.match(p, value):
            return False, f"does not match required pattern {p!r}"
        return True, ''
    if t == 'enum':
        vals = rule.get('values') or []
        if not isinstance(value, str):
            return False, f"must be a string (one of: {', '.join(vals)})"
        if value not in vals:
            return False, f"must be one of: {', '.join(vals)} (got {value!r})"
        return True, ''
    if t == 'acl_name':
        # Cisco/Juniper ACL name shape; mirrors validate_acl_name's rules.
        if not isinstance(value, str):
            return False, f"must be a string"
        if not (1 <= len(value) <= 63):
            return False, f"must be 1..63 chars; got {len(value)}"
        if not re.match(r'^[A-Za-z][A-Za-z0-9_-]*$', value):
            return False, f"must start with a letter and contain only [A-Za-z0-9_-]"
        return True, ''
    if t == 'cidr_list':
        import ipaddress
        if not isinstance(value, list):
            return False, f"must be a list of CIDRs"
        for i, item in enumerate(value):
            if not isinstance(item, str):
                return False, f"element {i}: must be a string"
            try:
                ipaddress.ip_network(item, strict=False)
            except ValueError:
                return False, f"element {i}: {item!r} is not a valid CIDR"
        return True, ''
    if t == 'host_port':
        why = host_port_problem(value)
        return (not why), why
    if t == 'listener':
        _, backend, name = path.split('.')
        why = listener_problem(backend, name, value)
        return (not why), why
    if t == 'backend_list':
        vals = rule.get('values') or []
        if not isinstance(value, list) or not value:
            return False, f"must be a non-empty list of backends (known: {', '.join(vals)})"
        for i, item in enumerate(value):
            if item not in vals:
                return False, f"element {i}: {item!r} is not a backend (known: {', '.join(vals)})"
            if item in value[:i]:
                return False, f"element {i}: {item!r} is listed twice"
        return True, ''
    if t == 'cisco_cmd_list':
        if not isinstance(value, list):
            return False, f"must be a list of Cisco priv-exec command strings"
        for i, item in enumerate(value):
            if not isinstance(item, str):
                return False, f"element {i}: must be a string"
            if not CMD_RE.match(item):
                return False, f"element {i}: {item!r} has invalid characters (letters/digits/spaces/_/- only)"
            if len(item) > 64:
                return False, f"element {i}: too long ({len(item)} chars; max 64)"
        return True, ''
    if t == 'command_rules':
        # Per-group TACACS+ command authorization rules. Each entry is a
        # dict {name, action, match?}; the tail must be a "*" catch-all
        # whose action is the group's default. Regenerated into both
        # tacquito.yaml (for tacquito's command-authz) and Junos class
        # allow-commands / deny-commands.
        if not isinstance(value, list):
            return False, f"must be a list of rule dicts"
        if not value:
            return False, f"must not be empty (need at least a catch-all '*' rule)"
        name_re = re.compile(r'^([A-Za-z][A-Za-z0-9_-]{0,31}|\*)$')
        catchall_count = 0
        for i, item in enumerate(value):
            if not isinstance(item, dict):
                return False, f"element {i}: must be a dict {{name, action, match?}}"
            name = item.get('name')
            action = item.get('action')
            match = item.get('match', [])
            if not isinstance(name, str) or not name_re.match(name):
                return False, f"element {i}: name must be '*' or a letter-start token (got {name!r})"
            if name == '*':
                catchall_count += 1
                if i != len(value) - 1:
                    return False, f"element {i}: '*' catch-all must be the LAST rule"
            if action not in ('permit', 'deny'):
                return False, f"element {i}: action must be 'permit' or 'deny' (got {action!r})"
            if match is None:
                match = []
            if not isinstance(match, list):
                return False, f"element {i}: match must be a list of regex strings"
            for j, m in enumerate(match):
                if not isinstance(m, str):
                    return False, f"element {i}: match[{j}]: must be a string"
                try:
                    re.compile(m)
                except re.error as e:
                    return False, f"element {i}: match[{j}]: invalid regex ({e})"
                if command_match_is_dead(name, m):
                    return False, (f"element {i}: match[{j}]: {m!r} repeats the command word; "
                                   f"tacquito tests match regexes against the ARGUMENTS only "
                                   f"(e.g. 'running-config' for 'show running-config'), so this "
                                   f"rule can never match. Drop the '{name} ' prefix or omit match.")
            extra = set(item.keys()) - {'name', 'action', 'match'}
            if extra:
                return False, f"element {i}: unknown keys {sorted(extra)}"
        if catchall_count != 1:
            return False, f"must contain exactly one '*' catch-all rule (found {catchall_count})"
        return True, ''
    return False, f"unknown schema type {t!r}"
PY
}

# --- Write path -----------------------------------------------------------
# _conf_write: validate via schema, then load defaults (from
# conf_emit_defaults) + overrides, mutate via mode/path + optional scalar
# value or list-items-file, atomic-write. All value input arrives via argv
# or a temp file path, never via stdin — stdin belongs to the heredoc.
_conf_write() {
    local mode="$1" path="$2" value="${3:-}" items_file="${4:-}"
    mkdir -p "$(dirname "$TACCTL_OVERRIDES_FILE")"
    # shellcheck disable=SC2016
    python3 - <(conf_emit_defaults) "$TACCTL_OVERRIDES_FILE" "$mode" "$path" "$value" "$items_file" <<PY
$(_conf_schema_py)

import os, sys, tempfile, yaml
defaults_path, overrides_path, mode, path, value, items_file = sys.argv[1:7]

def load(p):
    if p and os.path.exists(p):
        try:
            with open(p) as f:
                return yaml.safe_load(f) or {}
        except Exception:
            return {}
    return {}

def get_nested(d, path):
    cur = d
    for part in path.split('.'):
        if not isinstance(cur, dict) or part not in cur:
            return None
        cur = cur[part]
    return cur

def set_nested(d, path, val):
    parts = path.split('.')
    cur = d
    for p in parts[:-1]:
        if not isinstance(cur.get(p), dict):
            cur[p] = {}
        cur = cur[p]
    cur[parts[-1]] = val

def unset_nested(d, path):
    parts = path.split('.')
    chain = [d]
    cur = d
    for p in parts[:-1]:
        if not isinstance(cur, dict) or p not in cur:
            return
        cur = cur[p]
        chain.append(cur)
    if isinstance(cur, dict) and parts[-1] in cur:
        del cur[parts[-1]]
    # Prune empty parent maps from the leaf upward.
    for i in range(len(parts) - 2, -1, -1):
        parent = chain[i]
        key = parts[i]
        if isinstance(parent.get(key), dict) and not parent[key]:
            del parent[key]

def coerce_scalar(s):
    # value comes in as a string (argv). Parse as int/bool/null when it
    # looks like one; else keep as-is. Empty string is preserved.
    if s == '':
        return ''
    try:
        return int(s)
    except ValueError:
        pass
    if '.' in s:
        try:
            return float(s)
        except ValueError:
            pass
    low = s.lower()
    if low == 'true':
        return True
    if low == 'false':
        return False
    if low == 'null':
        return None
    return s

# --- Validate BEFORE loading+mutating anything. ---
if mode == 'set':
    parsed = coerce_scalar(value)
    ok, msg = validate(path, parsed, is_list=False)
    if not ok:
        print(f"tacctl config: {path}: {msg}", file=sys.stderr)
        sys.exit(1)
elif mode == 'set_list':
    items = []
    if items_file and os.path.isfile(items_file):
        with open(items_file) as f:
            items = [line.rstrip('\n') for line in f if line.strip()]
    ok, msg = validate(path, items, is_list=True)
    if not ok:
        print(f"tacctl config: {path}: {msg}", file=sys.stderr)
        sys.exit(1)
elif mode == 'set_json':
    # value is a JSON payload (scalar, list, or dict). Parse + validate
    # as-is; the schema entry for <path> decides what's acceptable.
    import json
    try:
        parsed = json.loads(value) if value else None
    except json.JSONDecodeError as e:
        print(f"tacctl config: {path}: invalid JSON payload ({e})", file=sys.stderr)
        sys.exit(1)
    ok, msg = validate(path, parsed, is_list=isinstance(parsed, list))
    if not ok:
        print(f"tacctl config: {path}: {msg}", file=sys.stderr)
        sys.exit(1)
    if schema_for(path)['type'] == 'listener':
        # Stored without the keys that only repeat a default.
        parsed = listener_compact(path.split('.')[1], parsed)
elif mode == 'unset':
    pass  # unsetting an unknown key is a no-op, not an error.
else:
    print(f"_conf_write: bad mode {mode!r}", file=sys.stderr)
    sys.exit(2)

defaults = load(defaults_path)
overrides = load(overrides_path)

# Revert-to-default prune: compare the new value against the YAML
# defaults tree first, then fall back to the schema's implicit default
# (for wildcard paths like aaa.order.<scope> that aren't pre-enumerated
# in conf_emit_defaults).
def _default_for(p):
    v = get_nested(defaults, p)
    if v is not None:
        return v
    return implicit_default(p)

if mode == 'set':
    if _default_for(path) == parsed:
        unset_nested(overrides, path)
    else:
        set_nested(overrides, path, parsed)
elif mode == 'set_list':
    if _default_for(path) == items:
        unset_nested(overrides, path)
    else:
        set_nested(overrides, path, items)
elif mode == 'set_json':
    if _default_for(path) == parsed:
        unset_nested(overrides, path)
    else:
        set_nested(overrides, path, parsed)
elif mode == 'unset':
    unset_nested(overrides, path)

# A listener is also checked against the others: two on one network and
# address cannot both bind. Refused before anything is written.
if path.startswith('listeners.') and mode != 'unset':
    clash = listeners_problems(overrides, only=path)
    if clash:
        print(f"tacctl config: {clash[0]}", file=sys.stderr)
        sys.exit(1)

# Empty overrides dict -> remove the file entirely (no-overrides posture).
if not overrides:
    try:
        os.unlink(overrides_path)
    except FileNotFoundError:
        pass
    sys.exit(0)

tmp = tempfile.NamedTemporaryFile('w', dir=os.path.dirname(overrides_path) or '.', delete=False)
tmp.write("# tacctl overrides. Hand-edits are fine as long as the YAML stays\n")
tmp.write("# valid. View effective posture: 'tacctl config dump'.\n\n")
yaml.safe_dump(overrides, tmp, default_flow_style=False, sort_keys=False)
tmp.close()
os.chmod(tmp.name, 0o640)
os.rename(tmp.name, overrides_path)
PY
    local rc=$?
    # Ownership matches tacquito.yaml when we're installed; silent-fail in tests.
    chown tacquito:tacquito "$TACCTL_OVERRIDES_FILE" 2>/dev/null || true
    _conf_invalidate
    return $rc
}

conf_set()      { _conf_write set      "$1" "${2:-}"; }
conf_set_json() { _conf_write set_json "$1" "${2:-}"; }  # value is a JSON payload
conf_unset()    { _conf_write unset    "$1"; }

# Return 0 if the overrides file explicitly sets <path>; non-zero if the
# path is entirely default. Useful for UIs that want to show "Source:
# explicit" vs "Source: default" without comparing values.
conf_has_override() {
    local path="$1"
    [[ -f "$TACCTL_OVERRIDES_FILE" ]] || return 1
    python3 - "$TACCTL_OVERRIDES_FILE" "$path" <<'PY'
import os, sys, yaml
with open(sys.argv[1]) as f:
    d = yaml.safe_load(f) or {}
cur = d
for part in sys.argv[2].split('.'):
    if isinstance(cur, dict) and part in cur:
        cur = cur[part]
    else:
        sys.exit(1)
sys.exit(0)
PY
}

# Emit the merged-view value at <path> as JSON. For structured paths
# (e.g. commands.<group> is a list of rule dicts); callers feed the
# result back through conf_set_json after editing.
conf_get_json() {
    local path="$1"
    _conf_load_cache
    python3 -c '
import json, sys
data = json.loads(sys.argv[1])
cur = data
for part in sys.argv[2].split("."):
    if isinstance(cur, dict) and part in cur:
        cur = cur[part]
    else:
        cur = None
        break
print(json.dumps(cur))
' "$_TACCTL_CFG_CACHE" "$path"
}

# Schema-walk the on-disk overrides file (not the merged view). Emits one
# "<path>: <reason>" line per problem to stdout; silent when clean. Uses
# the shared schema emitted by _conf_schema_py so it stays lock-step with
# the write-time validator.
_conf_validate_overrides_file() {
    [[ -f "$TACCTL_OVERRIDES_FILE" ]] || return 0
    # shellcheck disable=SC2016
    python3 - "$TACCTL_OVERRIDES_FILE" <<PY
$(_conf_schema_py)

import sys, yaml
overrides_path = sys.argv[1]
try:
    with open(overrides_path) as f:
        data = yaml.safe_load(f) or {}
except Exception as e:
    print(f"could not parse {overrides_path}: {e}")
    sys.exit(0)

# Walk every leaf (scalar or list) in the overrides and run it through
# the schema. Maps aren't themselves validated — only their leaves.
def walk(node, prefix=''):
    if isinstance(node, dict):
        for k, v in node.items():
            child = f"{prefix}.{k}" if prefix else k
            if isinstance(v, dict):
                yield from walk(v, child)
            else:
                yield child, v
    # Top-level non-dict shouldn't happen for tacctl.yaml; ignore.

# The listeners section is checked as a whole (its leaves are mappings, and
# two listeners can collide); everything else leaf by leaf.
rest = {k: v for k, v in data.items() if k != 'listeners'} if isinstance(data, dict) else data
for path, value in walk(rest):
    # Lists come through as the raw value (not split into elements).
    is_list = isinstance(value, list)
    ok, msg = validate(path, value, is_list=is_list)
    if not ok:
        print(f"{path}: {msg}")
if isinstance(data, dict):
    for problem in listeners_problems(data):
        print(problem)
PY
}
# Items arrive on stdin, one per line. Callers pass a list via `<<< "$list"`
# or a heredoc. Whitespace-only lines are dropped. We funnel stdin into a
# temp file and pass the path to python so the python script's own heredoc
# doesn't contend with stdin.
conf_set_list() {
    local path="$1" tmp
    tmp=$(mktemp)
    cat > "$tmp"
    _conf_write set_list "$path" "" "$tmp"
    local rc=$?
    rm -f "$tmp"
    return $rc
}

# --- Resolve tunable scalars from the unified config ---
# conf_get returns the merged (defaults + overrides) value, or the $2
# fallback when either file is missing. The clamp-to-range checks below
# handle garbage in the overrides file (hand-edited out of range, etc.).
# The four reads share one merge of defaults + overrides: each $(conf_get)
# runs in a subshell and would otherwise redo it. The cache is dropped again
# afterwards so nothing later in this shell depends on its age.
_conf_load_cache
PASSWORD_MAX_AGE_DAYS=$(conf_get password.max_age_days 90)
if ! [[ "$PASSWORD_MAX_AGE_DAYS" =~ ^[0-9]+$ ]] || [[ "$PASSWORD_MAX_AGE_DAYS" -lt 1 ]]; then
    PASSWORD_MAX_AGE_DAYS=90
fi

# Bcrypt cost: default 12 follows OWASP 2025 guidance (~300ms on modern CPUs).
# Existing hashes at lower cost keep verifying — bcrypt encodes cost in the
# hash itself. Clamp to [10,14] to avoid accidental DoS or downgrade.
BCRYPT_COST=$(conf_get bcrypt.cost 12)
if ! [[ "$BCRYPT_COST" =~ ^[0-9]+$ ]] || [[ "$BCRYPT_COST" -lt 10 || "$BCRYPT_COST" -gt 14 ]]; then
    BCRYPT_COST=12
fi

# Interactive password floor: default 12 (OWASP 2025). Clamp to [8, 64] —
# 8 is NIST 800-63's floor, 64 is a practical ceiling for typed input.
PASSWORD_MIN_LENGTH=$(conf_get password.min_length 12)
if ! [[ "$PASSWORD_MIN_LENGTH" =~ ^[0-9]+$ ]] || [[ "$PASSWORD_MIN_LENGTH" -lt 8 || "$PASSWORD_MIN_LENGTH" -gt 64 ]]; then
    PASSWORD_MIN_LENGTH=12
fi

# Shared-secret floor: default 16 (Cisco TACACS+ best practice). Clamp
# to [16, 128] — shorter silently downgrades Cisco's guidance, longer
# risks shell-quoting issues on devices.
SECRET_MIN_LENGTH=$(conf_get secret.min_length 16)
if ! [[ "$SECRET_MIN_LENGTH" =~ ^[0-9]+$ ]] || [[ "$SECRET_MIN_LENGTH" -lt 16 || "$SECRET_MIN_LENGTH" -gt 128 ]]; then
    SECRET_MIN_LENGTH=16
fi
_conf_invalidate

# --- CONFIG PASSWORD-AGE ---
cmd_config_password_age() {
    local new_days="${1:-}"

    if [[ -z "$new_days" ]]; then
        echo ""
        echo "  Password age warning threshold: ${PASSWORD_MAX_AGE_DAYS} days"
        echo ""
        echo "  Usage: tacctl config password-age <days>"
        echo ""
        return
    fi

    conf_set password.max_age_days "$new_days" || exit 1
    PASSWORD_MAX_AGE_DAYS="$new_days"
    info "Password age warning threshold set to ${new_days} days."
    echo ""
}

# --- CONFIG BCRYPT-COST ---
# Cost factor affects only NEW hashes; existing hashes verify at whatever
# cost they were minted with. Higher = slower login + stronger.
cmd_config_bcrypt_cost() {
    local new_cost="${1:-}"

    if [[ -z "$new_cost" ]]; then
        echo ""
        echo "  Bcrypt cost factor: ${BCRYPT_COST}"
        echo "  (New hashes only — existing hashes keep their minted cost.)"
        echo ""
        echo "  Usage: tacctl config bcrypt-cost <10-14>"
        echo "  Typical wall-clock on a modern CPU: 10≈100ms, 12≈300ms, 14≈1.2s"
        echo ""
        return
    fi

    conf_set bcrypt.cost "$new_cost" || exit 1
    BCRYPT_COST="$new_cost"
    info "Bcrypt cost set to ${new_cost}. Applies to new/changed passwords."
    echo ""
}

# --- CONFIG PASSWORD-MIN-LENGTH ---
# Floor enforced by validate_password_strength on user-supplied passwords.
# Auto-generated passwords (when the user accepts the prompt's blank
# default) bypass this — they're always 24+ chars.
cmd_config_password_min_length() {
    local new_len="${1:-}"

    if [[ -z "$new_len" ]]; then
        echo ""
        echo "  Password minimum length: ${PASSWORD_MIN_LENGTH}"
        echo "  (Enforced on interactively-entered passwords; auto-generated bypass.)"
        echo ""
        echo "  Usage: tacctl config password-min-length <8-64>"
        echo "  Guidance: NIST 800-63 floor is 8; OWASP 2025 recommends ≥12."
        echo ""
        return
    fi

    conf_set password.min_length "$new_len" || exit 1
    PASSWORD_MIN_LENGTH="$new_len"
    info "Password minimum length set to ${new_len}. Applies to new/changed passwords."
    echo ""
}

# --- CONFIG SECRET-MIN-LENGTH ---
# Floor enforced when the operator types a custom shared secret. The
# auto-gen path ('openssl rand -base64 24') always exceeds this.
cmd_config_secret_min_length() {
    local new_len="${1:-}"

    if [[ -z "$new_len" ]]; then
        echo ""
        echo "  Shared-secret minimum length: ${SECRET_MIN_LENGTH}"
        echo "  (Enforced on user-supplied secrets; auto-generated bypass.)"
        echo ""
        echo "  Usage: tacctl config secret-min-length <16-128>"
        echo "  Guidance: Cisco TACACS+ best practice is ≥16."
        echo ""
        return
    fi

    conf_set secret.min_length "$new_len" || exit 1
    SECRET_MIN_LENGTH="$new_len"
    info "Shared-secret minimum length set to ${new_len}. Applies to new secrets."
    echo ""
}

# --- CONFIG DUMP ---
# Prints the tacctl configuration posture: defaults, overrides, and the
# merged view. Diagnostic — no mutation.
cmd_config_dump() {
    echo ""
    echo -e "${BOLD}tacctl configuration${NC}"
    echo "--------------------------------------------"
    echo -e "  Defaults:  embedded in bin/tacctl.sh (conf_emit_defaults)"
    echo -e "  Overrides: ${TACCTL_OVERRIDES_FILE}"
    echo ""

    echo -e "${BOLD}--- Defaults (canonical) ---${NC}"
    conf_emit_defaults
    echo ""
    echo -e "${BOLD}--- Overrides (operator-set) ---${NC}"
    if [[ -r "$TACCTL_OVERRIDES_FILE" ]]; then
        cat "$TACCTL_OVERRIDES_FILE"
    else
        echo "  (no overrides — running on defaults)"
    fi
    echo ""
    echo -e "${BOLD}--- Effective (merged) ---${NC}"
    # Print the cached merged view (JSON) as YAML. One python call.
    _conf_load_cache
    python3 -c '
import json, sys, yaml
print(yaml.safe_dump(json.loads(sys.argv[1]), default_flow_style=False, sort_keys=False).rstrip())
' "$_TACCTL_CFG_CACHE"
    echo ""
}

