# shellcheck shell=bash
# tacctl lib/render_tacacs.sh -- TACACS+ renderer (model + tacctl.yaml -> tacquito.yaml), rendered-artifact bookkeeping, daemon load-smoke, 'tacctl config render'
# Sourced by bin/tacctl.sh (see the load block there for ordering); not executable.
#
# tacquito.yaml is an ARTIFACT: everything in it is derived from the model
# (lib/model.sh) and the merged tacctl.yaml view (lib/conf.sh). This file
# owns producing it and noticing when somebody edited it by hand.
#
#   render_tacacs_config <model.json> <out>   pure: model -> file, nothing else
#   tacacs_render_apply [--force]             the live config: drift gate,
#                                             render, install, record
#   rendered_record / rendered_check          sha256 bookkeeping (rendered.json)
#   tacacs_load_smoke <file>                  can the real daemon load it?
#
# The rendered file holds shared secrets and password hashes. The model
# reaches python as a 0600 file, never on argv.

# {path: sha256} of every artifact tacctl rendered (plan 4.5).
RENDERED_FILE="${TACCTL_STATE_DIR:-/etc/tacctl}/rendered.json"

# --- Python: renderer, read-back check, bookkeeping -------------------------
# Appended to _store_py and _model_py (lib/store.sh, lib/model.sh), whose
# names it uses; carries its own command dispatcher.
_render_tacacs_py() {
    cat <<'PY'
import shutil

# ---- tacquito.yaml renderer ------------------------------------------------
#
# Emits the layout tacctl has always written (config/tacquito.yaml plus what
# 'user add', 'group add', 'scope add' and 'config allow|deny' spliced in):
# type constants, the file accounter, one bcrypt_<user> authenticator anchor
# per user, exec_<group> / junos_exec_<group> service anchors, one group
# anchor per group, the users list, one secrets[] entry per (scope, prefix)
# sorted by specificity, and the prefix filters. Output depends only on the
# inputs -- no timestamps -- so an unchanged model renders byte-identically.

RENDER_HEADER = (
    "# GENERATED by tacctl from /etc/tacctl/store.yaml and tacctl.yaml. Edits here are overwritten.\n"
    "# Use tacctl commands, or 'tacctl store import --replace' to adopt manual edits.\n"
    "#\n"
    "# Tacquito TACACS+ server configuration (Cisco IOS/IOS-XE + Juniper).\n"
)
# The order config/tacquito.yaml lists the built-in groups in.
BUILTIN_RENDER_ORDER = ('readonly', 'operator', 'superuser')
# Words PyYAML (YAML 1.1) reads as a boolean or null when left unquoted.
YAML_WORDS = ('y', 'n', 'yes', 'no', 'on', 'off', 'true', 'false', 'null')
# Top-level keys the layout itself uses; a group may not take one of them.
RENDER_TOP_KEYS = set(LEGACY_TOP_KEYS) | set(LEGACY_CONSTANTS) | {'file_accounter'}
RENDER_KEY_PREFIXES = ('exec_', 'junos_exec_', 'bcrypt_', 'group_')
ACTIONS = {'permit': 2, 'deny': 1}


def yq(s):
    """A YAML double-quoted scalar that every YAML parser decodes to exactly s."""
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch in '"\\':
            out.append('\\' + ch)
        elif 0x20 <= o < 0x7f:
            out.append(ch)
        elif o <= 0xff:
            out.append('\\x%02x' % o)
        elif o <= 0xffff:
            out.append('\\u%04x' % o)
        else:
            out.append('\\U%08x' % o)
    out.append('"')
    return ''.join(out)


def yname(s):
    """A name as a plain scalar, as tacctl always wrote it, unless a parser
    could read that as something other than the string."""
    if re.fullmatch(r'[A-Za-z_][A-Za-z0-9_-]*', s) and s.lower() not in YAML_WORDS:
        return s
    return yq(s)


def group_key(name):
    """Top-level key and anchor of a group: its name, unless that would
    collide with a key the layout owns."""
    if name in RENDER_TOP_KEYS or name.startswith(RENDER_KEY_PREFIXES):
        return 'group_' + name
    return name


def group_order(groups):
    first = [g for g in BUILTIN_RENDER_ORDER if g in groups]
    return first + sorted(g for g in groups if g not in first)


def tacacs_scopes(model):
    """Scopes this backend serves: no protocols filter, or one naming tacacs."""
    return {n: s for n, s in model['scopes'].items()
            if not s.get('protocols') or 'tacacs' in s['protocols']}


def rendered_hash(user):
    """What goes in the file: the real hash, or the marker nothing matches."""
    if user.get('disabled') or user.get('accounting_sink') or not user.get('hash'):
        return DISABLED_MARKER_HEX
    return user['hash']


def group_commands(conf, group):
    """commands.<group> from the merged tacctl.yaml view -> validated rules."""
    rules = (conf.get('commands') or {}).get(group) or []
    if not isinstance(rules, list):
        raise StoreError(f'tacctl.yaml: commands.{group} is not a list of rules')
    out = []
    for r in rules:
        if not isinstance(r, dict) or not isinstance(r.get('name'), str) or not r['name']:
            raise StoreError(f'tacctl.yaml: commands.{group} has a rule without a name')
        action = r.get('action', 'permit')
        if action not in ACTIONS:
            raise StoreError(f"tacctl.yaml: commands.{group}: rule '{r['name']}' has an action that is neither permit nor deny")
        match = r.get('match') or []
        if not isinstance(match, list) or any(not isinstance(m, str) for m in match):
            raise StoreError(f"tacctl.yaml: commands.{group}: rule '{r['name']}' has a match that is not a list of strings")
        out.append({'name': r['name'], 'action': action, 'match': list(match)})
    return out


def render_tacacs(model, conf):
    """Model + merged tacctl.yaml view -> tacquito.yaml text."""
    errs = store_validate(model)
    if errs:
        raise StoreError('cannot render an invalid model:\n  - ' + '\n  - '.join(errs))
    groups, users = model['groups'], model['users']
    scopes = tacacs_scopes(model)
    w = []

    w.append(RENDER_HEADER)
    w.append(
        "\n# --- Type constants ---\n"
        "authenticator_type_bcrypt: &authenticator_type_bcrypt 1\n"
        "action_deny:  &action_deny  1\n"
        "action_permit: &action_permit 2\n"
        "accounter_type_file: &accounter_type_file 3\n"
        "handler_type_start: &handler_type_start 1\n"
        "provider_type_prefix: &provider_type_prefix 1\n"
        "\n# --- Accounting ---\n"
        "file_accounter: &file_accounter\n"
        "  name: tacquito_accounter\n"
        "  type: *accounter_type_file\n"
        "\n# --- Per-user bcrypt authenticators ---\n"
        "# A disabled account and the 'root' accounting sink carry a well-formed\n"
        "# hash that no password matches.\n"
    )
    for name in sorted(users):
        h = rendered_hash(users[name])
        # All-digit hex would read as a number; nothing else needs quotes.
        w.append(
            f"\nbcrypt_{name}: &bcrypt_{name}\n"
            f"  type: *authenticator_type_bcrypt\n"
            f"  options:\n"
            f"    hash: {yq(h) if h.isdigit() else h}\n"
        )

    w.append(
        "\n# --- Services ---\n"
        "# Cisco IOS/IOS-XE sends service=shell for exec authorization and expects\n"
        "# priv-lvl; the anchors keep 'exec' as the label for the tier.\n"
        "# Juniper requests service=junos-exec and expects local-user-name.\n"
        "# Each device type only requests its own service; the other is ignored.\n"
    )
    order = group_order(groups)
    for name in order:
        g = groups[name]
        w.append(
            f"\n# Cisco exec - {name} (priv-lvl {g['priv_lvl']})\n"
            f"exec_{name}: &exec_{name}\n"
            f"  name: shell\n"
            f"  set_values:\n"
            f"    - name: priv-lvl\n"
            f"      values: [{g['priv_lvl']}]\n"
            f"\n# Juniper junos-exec - {name}\n"
            f"# \"{g['juniper_class']}\" must match a local template user on Juniper devices\n"
            f"junos_exec_{name}: &junos_exec_{name}\n"
            f"  name: junos-exec\n"
            f"  set_values:\n"
            f"    - name: local-user-name\n"
            f"      values: [{yq(g['juniper_class'])}]\n"
        )

    w.append("\n# --- Groups ---\n"
             "# Command rules come from commands.<group> in tacctl.yaml.\n")
    for i, name in enumerate(order):
        key = group_key(name)
        w.append(
            f"{'' if i == 0 else chr(10)}{yname(key)}: &{key}\n"
            f"  name: {yname(name)}\n"
            f"  services:\n"
            f"    - *exec_{name}\n"
            f"    - *junos_exec_{name}\n"
        )
        rules = group_commands(conf, name)
        if rules:
            w.append("  commands:\n")
            for r in rules:
                w.append(f"    - name: {yq(r['name'])}\n")
                if r['match']:
                    w.append("      match: [" + ", ".join(yq(m) for m in r['match']) + "]\n")
                w.append(f"      action: *action_{r['action']}\n")
        w.append("  accounter: *file_accounter\n")

    w.append("\n# --- Users ---\n")
    if users:
        w.append("users:\n")
        for name in sorted(users):
            u = users[name]
            mine = [s for s in u['scopes'] if s in scopes]
            w.append(
                f"\n  # {name}\n"
                f"  - name: {yname(name)}\n"
                f"    scopes: [{', '.join(yq(s) for s in mine)}]\n"
                f"    groups: [*{group_key(u['group'])}]\n"
                f"    authenticator: *bcrypt_{name}\n"
                f"    accounter: *file_accounter\n"
            )
    else:
        w.append("users: []\n")

    w.append(
        "\n# --- Secret Providers (Scopes) ---\n"
        "# One entry per (scope, prefix), most specific prefix first: tacquito\n"
        "# answers a client with the first entry whose prefix contains it.\n"
    )
    entries = sorted(((c, n) for n, s in scopes.items() for c in s['prefixes']),
                     key=lambda t: (cidr_key(t[0]), t[1]))
    if entries:
        w.append("secrets:\n")
        for cidr, name in entries:
            w.append(
                f"  - name: {yname(name)}\n"
                f"    secret:\n"
                f"      group: tacquito\n"
                f"      key: {yq(scopes[name]['secret'])}\n"
                f"    handler:\n"
                f"      type: *handler_type_start\n"
                f"    type: *provider_type_prefix\n"
                f"    options:\n"
                f"      prefixes: |\n"
                f"        [\n"
                f"          {json.dumps(cidr)}\n"
                f"        ]\n"
            )
    else:
        w.append("secrets: []\n")

    filters = model.get('filters') or {}
    lines = []
    for store_key, key in (('allow', 'prefix_allow'), ('deny', 'prefix_deny')):
        items = sorted(filters.get(store_key) or [], key=cidr_key)
        if items:
            lines.append(f"{key}: [" + ", ".join(yq(c) for c in items) + "]\n")
    if lines:
        w.append("\n# --- Connection filters ---\n" + "".join(lines))
    return "".join(w)


def render_readback(path, model, conf):
    """Read a rendered file back with the importer and check it says what
    the model says. Guards every render against a quoting or layout bug:
    a file that fails here is never installed."""
    back, rep = legacy_load(path)
    problems = [f'importer reports: {m}' for m in rep['errors'] + rep['dropped']]
    scopes = tacacs_scopes(model)

    want_groups = {n: (g['priv_lvl'], g['juniper_class']) for n, g in model['groups'].items()}
    got_groups = {n: (g['priv_lvl'], g['juniper_class']) for n, g in back['groups'].items()}
    if want_groups != got_groups:
        problems.append('groups differ')

    want_users, got_users = {}, {}
    for n, u in model['users'].items():
        h = rendered_hash(u)
        want_users[n] = (u['group'], [s for s in u['scopes'] if s in scopes],
                         None if h == DISABLED_MARKER_HEX else h)
    for n, u in back['users'].items():
        got_users[n] = (u['group'], u['scopes'], None if u['disabled'] else u['hash'])
    if want_users != got_users:
        problems.append('users differ')

    want_scopes = {n: (canonical_cidr_list(list(s['prefixes'])), s['secret']) for n, s in scopes.items()}
    got_scopes = {n: (canonical_cidr_list(list(s['prefixes'])), s['secret']) for n, s in back['scopes'].items()}
    if want_scopes != got_scopes:
        problems.append('scopes differ')

    for k in FILTER_KEYS:
        if canonical_cidr_list(list((model.get('filters') or {}).get(k) or [])) != canonical_cidr_list(back['filters'][k]):
            problems.append(f'filters.{k} differs')

    with open(path) as f:
        doc = yaml.safe_load(f)
    by_name = {v['name']: v for v in doc.values()
               if isinstance(v, dict) and isinstance(v.get('services'), list)}
    for name in model['groups']:
        want = [dict({'name': r['name'], 'action': ACTIONS[r['action']]},
                     **({'match': r['match']} if r['match'] else {}))
                for r in group_commands(conf, name)]
        got = (by_name.get(name) or {}).get('commands') or []
        if want != got:
            problems.append(f"command rules of group '{name}' differ")

    if problems:
        raise StoreError('internal error: the rendered config does not read back as the model ('
                         + '; '.join(problems) + '). Nothing was written.')


def render_to_file(model, conf, out):
    """Render, verify, and move into place (0640, tacquito:tacquito when
    that account exists and we may chown)."""
    text = render_tacacs(model, conf)
    d = os.path.dirname(out) or '.'
    fd, tmp = tempfile.mkstemp(prefix='.tacquito.', suffix='.tmp', dir=d)
    try:
        with os.fdopen(fd, 'w') as f:
            os.fchmod(f.fileno(), 0o640)
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        render_readback(tmp, model, conf)
        with contextlib.suppress(LookupError, OSError):
            shutil.chown(tmp, 'tacquito', 'tacquito')
        os.replace(tmp, out)
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(tmp)
        raise


def load_conf_view(overrides_path):
    """The merged tacctl.yaml view arrives on stdin. A tacctl.yaml that does
    not parse would silently fall back to shipped defaults there, and with
    it to the default command rules -- refuse instead."""
    if overrides_path and os.path.exists(overrides_path):
        try:
            with open(overrides_path) as f:
                raw = yaml.safe_load(f)
        except yaml.YAMLError as e:
            raise StoreError(yaml_problem(overrides_path, e) + ' -- fix it before rendering')
        if raw is not None and not isinstance(raw, dict):
            raise StoreError(f'{overrides_path}: not a YAML mapping -- fix it before rendering')
    conf = json.load(sys.stdin)
    if not isinstance(conf, dict):
        raise StoreError('internal: merged tacctl.yaml view is not a mapping')
    return conf


# ---- rendered-artifact bookkeeping (plan 4.5) ------------------------------

def file_sha256(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(65536), b''):
            h.update(chunk)
    return h.hexdigest()


def rendered_load(json_path):
    """{path: sha256}; {} when nothing was ever recorded."""
    try:
        with open(json_path) as f:
            data = json.load(f)
    except FileNotFoundError:
        return {}
    except ValueError:
        raise StoreError(f'{json_path}: not valid JSON')
    if not isinstance(data, dict) or any(not isinstance(v, str) for v in data.values()):
        raise StoreError(f'{json_path}: not a path-to-sha256 mapping')
    return data


def rendered_status(records, path):
    """ok | drift | missing | unrecorded"""
    if not os.path.exists(path):
        return 'missing'
    if path not in records:
        return 'unrecorded'
    return 'ok' if file_sha256(path) == records[path] else 'drift'


def render_main(argv):
    cmd, rest = argv[0], argv[1:]

    if cmd == 'render':
        # render <model.json> <out> <tacctl.yaml path>; merged view on stdin
        with open(rest[0]) as f:
            model = json.load(f)
        render_to_file(model, load_conf_view(rest[2]), rest[1])

    elif cmd == 'record':
        # record <rendered.json> <path>
        json_path, path = rest[0], os.path.abspath(rest[1])
        with store_lock(json_path):
            records = rendered_load(json_path)
            records[path] = file_sha256(path)
            atomic_write(json_path, json.dumps(records, indent=2, sort_keys=True) + '\n')

    elif cmd == 'forget':
        # forget <rendered.json> <path>
        json_path, path = rest[0], os.path.abspath(rest[1])
        if os.path.exists(json_path):
            with store_lock(json_path):
                records = rendered_load(json_path)
                if records.pop(path, None) is not None:
                    atomic_write(json_path, json.dumps(records, indent=2, sort_keys=True) + '\n')

    elif cmd == 'check':
        # check <rendered.json> <path>
        print(rendered_status(rendered_load(rest[0]), os.path.abspath(rest[1])))

    elif cmd == 'drift':
        # drift <rendered.json>: one '<status>\t<path>' line per artifact that
        # no longer is what tacctl rendered.
        bad = 0
        for path, _sha in sorted(rendered_load(rest[0]).items()):
            status = rendered_status({path: _sha}, path)
            if status != 'ok':
                print(f'{status}\t{path}')
                bad = 1
        return bad

    else:
        raise StoreError(f'internal: unknown command {cmd!r}')
    return 0


if __name__ == '__main__':
    try:
        sys.exit(render_main(sys.argv[1:]))
    except StoreError as e:
        print(f'tacctl render: {e}', file=sys.stderr)
        sys.exit(1)
    except OSError as e:
        print(f'tacctl render: {e.filename or "I/O"}: {e.strerror}', file=sys.stderr)
        sys.exit(1)
PY
}

# Run the render program: _render_python <command> [args...].
_render_python() {
    python3 <(_store_py; _model_py; _render_tacacs_py) "$@"
}

# --- Renderer ---------------------------------------------------------------

# render_tacacs_config <model.json> <out>
# Render a complete tacquito.yaml from a model (as model_dump prints it) and
# the merged tacctl.yaml view (command rules), and move it into place at
# <out> (0640; tacquito:tacquito when possible). Before the move the file is
# read back through the importer and compared with the model; on any
# mismatch nothing is written. Pure with respect to tacctl state: no drift
# check, no rendered.json, no restart -- see tacacs_render_apply for those.
# Returns 0 rendered, 1 failed (message on stderr).
render_tacacs_config() {
    local model="${1:-}" out="${2:-}"
    if [[ -z "$model" || -z "$out" ]]; then
        error "Usage: render_tacacs_config <model.json> <out>"
        return 1
    fi
    _conf_load_cache
    _render_python render "$model" "$out" "${TACCTL_OVERRIDES_FILE:-}" \
        < <(printf '%s' "$_TACCTL_CFG_CACHE") || return 1
}

# --- Bookkeeping ------------------------------------------------------------

# rendered_record <path>: remember the file's current sha256 as "what tacctl
# rendered" in rendered.json.
rendered_record() {
    _render_python record "$RENDERED_FILE" "$1"
}

# rendered_forget <path>: drop a path from rendered.json (no-op if absent).
rendered_forget() {
    _render_python forget "$RENDERED_FILE" "$1"
}

# rendered_check <path>: compare a file with its record. Prints one word and
# returns: ok (0) unchanged since tacctl rendered it; drift (1) content
# differs; missing (2) the file is gone; unrecorded (3) tacctl has no record
# of rendering it. An unreadable rendered.json is a failure (4, message on
# stderr) -- callers must not treat it as "ok".
rendered_check() {
    local status
    status=$(_render_python check "$RENDERED_FILE" "$1") || status=""
    case "$status" in
        ok)         echo "ok";         return 0 ;;
        drift)      echo "drift";      return 1 ;;
        missing)    echo "missing";    return 2 ;;
        unrecorded) echo "unrecorded"; return 3 ;;
        *)          return 4 ;;
    esac
}

# --- Applying a render to the live config -----------------------------------

# tacacs_render_apply [--force]
# Render the current model into $CONFIG.
#   stdout  CHANGED or UNCHANGED (nothing else; messages go to stderr)
#   return  0 done; 1 failed; 3 refused because the file on disk is not what
#           tacctl rendered (hand edit, or never rendered by tacctl) and the
#           new render would replace it.
# --force overwrites such a file after copying it to backups/legacy/.
# A file whose content already equals the new render is never a conflict.
# Requires the store: in legacy mode tacquito.yaml is still the source of
# truth and is not regenerated.
tacacs_render_apply() {
    local force=0
    case "${1:-}" in
        "")      ;;
        --force) force=1 ;;
        *)
            error "Usage: tacacs_render_apply [--force]"
            return 1
            ;;
    esac
    if [[ ! -f "$STORE_FILE" ]]; then
        error "$STORE_NOT_INITIALISED_MSG"
        return 1
    fi
    # Subshell: scopes the temp dir (it holds the model and the candidate,
    # secrets included) and its cleanup trap.
    ( _tacacs_render_apply_run "$force" )
}

_tacacs_render_apply_run() {
    local force="$1" tmpd status rc=0
    tmpd=$(mktemp -d) || exit 1
    # shellcheck disable=SC2064  # expand tmpd now; the subshell owns this trap
    trap "rm -rf '${tmpd}'" EXIT

    model_dump > "${tmpd}/model.json" || exit 1
    render_tacacs_config "${tmpd}/model.json" "${tmpd}/tacquito.yaml" || exit 1

    if [[ -f "$CONFIG" ]] && cmp -s "${tmpd}/tacquito.yaml" "$CONFIG"; then
        rendered_record "$CONFIG" || exit 1
        echo "UNCHANGED"
        exit 0
    fi

    status=$(rendered_check "$CONFIG") || rc=$?
    case "$rc" in
        0|2) ;;
        1|3)
            if (( ! force )); then
                if [[ "$status" == "drift" ]]; then
                    error "${CONFIG} was edited since tacctl rendered it; rendering would discard those edits."
                else
                    error "${CONFIG} was not rendered by tacctl; rendering would replace it."
                fi
                error "To keep what the file says: 'tacctl store import --replace', then 'tacctl config render --force'."
                error "To discard it: 'tacctl config render --force' alone. Either way the current file is saved under ${BACKUP_DIR}/legacy/ first."
                exit 3
            fi
            _tacacs_save_displaced "$CONFIG" || exit 1
            ;;
        *)
            error "Cannot read ${RENDERED_FILE}; refusing to overwrite ${CONFIG}."
            exit 1
            ;;
    esac

    # Same directory as the target, so the final step is a rename.
    local staged="${CONFIG}.tacctl-new"
    cp "${tmpd}/tacquito.yaml" "$staged" || exit 1
    chmod 640 "$staged"
    chown tacquito:tacquito "$staged" 2>/dev/null || true
    mv -f "$staged" "$CONFIG" || { rm -f "$staged"; exit 1; }
    rendered_record "$CONFIG" || exit 1
    echo "CHANGED"
    exit 0
}

# Copy a file that is about to be overwritten into backups/legacy/.
_tacacs_save_displaced() {
    local src="$1" dir="${BACKUP_DIR}/legacy" dest
    mkdir -p "$dir" || return 1
    chmod 700 "$dir"
    dest="${dir}/$(basename "$src").drift.$(date +%Y%m%d_%H%M%S_%3N)"
    cp "$src" "$dest" || return 1
    chmod 600 "$dest"
    warn "Previous ${src} saved to ${dest}" >&2
}

# --- Daemon load-smoke (plan 4.3 step 4) ------------------------------------

# tacacs_load_smoke <rendered-file>
# Start the real tacquito on a copy of the file and see whether it loads it.
# Returns 0 loaded and serving; 2 skipped (no daemon binary); 1 failed.
#
# Isolation: every flag that names a resource is set explicitly, so nothing
# falls back to a production default -- the listener and the metrics
# exporter bind 127.0.0.1 on a kernel-chosen port (never :49), the
# accounting log and the config live in a private temp dir. The daemon is
# run under 'timeout' (so it dies even if tacctl is killed), is killed as
# soon as the verdict is known, and the temp dir is removed on exit.
TACACS_SMOKE_SECONDS=5

tacacs_load_smoke() {
    local rendered="${1:-}"
    [[ -x "$TACQUITO_BIN" ]] || return 2
    command -v timeout >/dev/null 2>&1 || return 2
    if [[ ! -f "$rendered" ]]; then
        error "Load-smoke: ${rendered} not found."
        return 1
    fi
    ( _tacacs_load_smoke_run "$rendered" )
}

_tacacs_load_smoke_run() {
    local rendered="$1" tmpd i verdict=1
    _TACACS_SMOKE_PID=""
    tmpd=$(mktemp -d) || exit 1
    # shellcheck disable=SC2064  # expand tmpd now; the pid is read when the trap fires
    trap "_tacacs_smoke_stop; rm -rf '${tmpd}'" EXIT

    # tacquito watches the config's DIRECTORY and logs every event in it, so
    # the config gets a directory of its own, apart from the logs.
    mkdir "${tmpd}/conf" "${tmpd}/run" || exit 1
    cp "$rendered" "${tmpd}/conf/tacquito.yaml" || exit 1

    timeout -k 1 "$(( TACACS_SMOKE_SECONDS + 1 ))" "$TACQUITO_BIN" \
        -config "${tmpd}/conf/tacquito.yaml" \
        -network tcp -address 127.0.0.1:0 \
        -acct-log-path "${tmpd}/run/accounting.log" \
        -metrics-address 127.0.0.1:0 \
        -level 20 >/dev/null 2>"${tmpd}/run/stderr.log" &
    _TACACS_SMOKE_PID=$!

    # Loaded = the listener is up AND the loader built its providers from
    # the file. A config the loader rejects logs 'error fetching config' and
    # the process exits (with status 0, so the log is what counts).
    for (( i = 0; i < TACACS_SMOKE_SECONDS * 10; i++ )); do
        if grep -q 'serve on ' "${tmpd}/run/stderr.log" 2>/dev/null \
            && grep -q 'updated all providers from config source' "${tmpd}/run/stderr.log" 2>/dev/null; then
            verdict=0
            break
        fi
        kill -0 "$_TACACS_SMOKE_PID" 2>/dev/null || break
        sleep 0.1
    done

    if (( verdict != 0 )); then
        # Name the cause without echoing the daemon's log: a YAML error can
        # quote a line of the config.
        if grep -q 'no users were unmarshalled' "${tmpd}/run/stderr.log" 2>/dev/null; then
            error "Load-smoke: tacquito refuses a config with no users."
        elif grep -q 'no secret providers were unmarshalled' "${tmpd}/run/stderr.log" 2>/dev/null; then
            error "Load-smoke: tacquito refuses a config with no scopes."
        elif grep -q 'error fetching config' "${tmpd}/run/stderr.log" 2>/dev/null; then
            error "Load-smoke: tacquito could not parse the config."
        else
            error "Load-smoke: tacquito did not start serving within ${TACACS_SMOKE_SECONDS}s."
        fi
    fi
    exit "$verdict"
}

_tacacs_smoke_stop() {
    [[ -n "${_TACACS_SMOKE_PID:-}" ]] || return 0
    kill "$_TACACS_SMOKE_PID" 2>/dev/null || true
    wait "$_TACACS_SMOKE_PID" 2>/dev/null || true
    _TACACS_SMOKE_PID=""
}

# --- CLI: tacctl config render [--force] ------------------------------------

cmd_config_render() {
    local force=()
    case "${1:-}" in
        "")      ;;
        --force) force=(--force) ;;
        *)
            error "Usage: tacctl config render [--force]"
            return 1
            ;;
    esac
    if (( $# > 1 )); then
        error "Usage: tacctl config render [--force]"
        return 1
    fi
    local result rc=0
    result=$(tacacs_render_apply "${force[@]}") || rc=$?
    if (( rc != 0 )); then
        return "$rc"
    fi
    if [[ "$result" == "CHANGED" ]]; then
        info "Rendered ${CONFIG}."
        restart_service
    else
        info "${CONFIG} is already up to date."
    fi
    if [[ -z "$(model_users)" || -z "$(model_scopes)" ]]; then
        warn "The store has no users or no scopes; tacquito refuses to serve such a config."
    fi
}
