package devreg

// The generated known_hosts (docs/plans/operator-console.md 3.7): every
// pinned key of the registry, one '<name> <type> <base64>' line each, the
// name being the HostKeyAlias ssh is given. ssh looks a host up by its
// HostKeyAlias alone (no port, no address) when one is set, so the file
// holds nothing but the names; it is regenerated under the registry's lock
// on every registry write (Mutate), root-owned and 0644 so the user's own
// ssh can read it.

import (
	"bytes"
	"os"
	"path/filepath"
)

// KnownHostsHeader starts the generated file.
const KnownHostsHeader = "# Generated by tacctl from devices.yaml on every registry change; do not edit.\n" +
	"# ssh reads it with: -o UserKnownHostsFile=<this file> -o HostKeyAlias=<name> -o StrictHostKeyChecking=yes\n"

// KnownHostsMode is the generated file's mode: readable by the users who
// run ssh, writable by root alone.
const KnownHostsMode os.FileMode = 0o644

// KnownHosts is the generated file for f: the devices' pinned keys in
// registry order, then the enrolled hosts' in name order. A key that does
// not parse is left out (the registry refuses one when it is read).
func (f *File) KnownHosts() []byte {
	var b bytes.Buffer
	b.WriteString(KnownHostsHeader)
	line := func(name string, keys []string) {
		for _, k := range sortKeys(ParseHostKeys(keys)) {
			b.WriteString(name + " " + k.String() + "\n")
		}
	}
	for _, d := range f.Devices {
		line(d.Name, d.HostKeys)
	}
	for _, h := range f.Hosts {
		line(h.Name, h.Keys)
	}
	return b.Bytes()
}

// WriteKnownHosts brings the generated file at path up to date with f:
// written through a temporary file and renamed when its bytes or its mode
// differ, left alone otherwise.
func WriteKnownHosts(path string, f *File) error {
	want := f.KnownHosts()
	if cur, err := os.ReadFile(path); err == nil && bytes.Equal(cur, want) {
		if st, err := os.Stat(path); err == nil && st.Mode().Perm() == KnownHostsMode {
			return nil
		}
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fail("Cannot write " + path + ": " + errText(err))
	}
	return atomicWrite(path, want, KnownHostsMode)
}

// SyncKnownHosts regenerates the file at knownHosts from the registry at
// devicesPath, under the registry's lock: for a registry written another
// way than Mutate (a restored snapshot).
func SyncKnownHosts(devicesPath, knownHosts string) error {
	unlock, err := Lock(devicesPath)
	if err != nil {
		return err
	}
	defer unlock()
	f, err := Load(devicesPath)
	if err != nil {
		return err
	}
	return WriteKnownHosts(knownHosts, f)
}
