package devreg

// 'tacctl device ssh-config' (docs/plans/operator-console.md 5.4): an
// ssh_config fragment with one Host block per entry the caller may see, for
// the user to save and Include from ~/.ssh/config, so a plain 'ssh <name>'
// reaches the device with its profile and is held to its pinned keys the
// way 'tacctl ssh <name>' is. There is no User line: ssh logs in with the
// local username, which for tacctl's users is their tacctl name, by
// password (the profile turns public keys off). tacctl only prints it: no
// root process writes into a user's home.

import (
	"bytes"
	"strconv"
	"time"
)

// SSHConfigHint is the install hint printed on stderr after the fragment.
const SSHConfigHint = "Save it with: tacctl device ssh-config > ~/.ssh/tacctl.conf\n" +
	"then add 'Include ~/.ssh/tacctl.conf' at the top of ~/.ssh/config (before any Host block, or it belongs to that block).\n"

// SSHConfig is the fragment for entries, in their order: server names the
// machine it was generated on and now the date, for the header line;
// knownHosts is the generated known_hosts the pinned entries are checked
// against. An entry ssh cannot reach (a host enrolled with --local) is left
// out.
func SSHConfig(entries []Entry, knownHosts, server string, now time.Time) []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by tacctl device ssh-config on " + server + ", " + now.Format("2006-01-02") +
		". Re-run after registry changes.\n")
	line := func(o SSHOption) { b.WriteString(o.ConfigLine() + "\n") }
	for _, e := range entries {
		target, ok := SSHTarget(e)
		if !ok {
			continue
		}
		b.WriteString("Host " + e.Name + "\n")
		line(SSHOption{"HostName", target})
		if e.Port != 0 && e.Port != DefaultPort {
			line(SSHOption{"Port", strconv.Itoa(e.Port)})
		}
		for _, o := range Profile(e) {
			line(o)
		}
		if !Pinned(e) {
			b.WriteString("    # No host key is pinned: ssh asks with your own known_hosts. Pin it: tacctl device hostkey " + e.Name + " accept\n")
			continue
		}
		for _, o := range PinOptions(e.Name, knownHosts) {
			line(o)
		}
	}
	return b.Bytes()
}
