// Package tacacs is the TACACS+ (tacquito) renderer of tacctl
// (lib/backends/tacacs.sh at the 0.1.16 tag, "RENDERER" and the drop-in
// half of "Units, listeners and their systemd drop-ins"):
//
//   - Render: the store and the merged tacctl.yaml view -> tacquito.yaml,
//     byte for byte the layout 0.1.16 writes;
//   - the read-back check every render passes before the file is used
//     (Readback, through the legacy loader, the importer of
//     'store import');
//   - Units: one systemd drop-in per listener of listeners.tacacs;
//   - the stage/commit/gate/check steps of the backend contract as
//     functions over a set of paths (Renderer), which internal/backend/tacacs
//     wraps.
//
// The rendered file holds shared secrets and password hashes; no message
// of this package contains either.
package tacacs

import (
	"fmt"
	"math/big"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"

	"github.com/rett/tacctl/internal/cidr"
	"github.com/rett/tacctl/internal/hash"
	"github.com/rett/tacctl/internal/model"
	"github.com/rett/tacctl/internal/py"
	"github.com/rett/tacctl/internal/rendered"
	"github.com/rett/tacctl/internal/store"
	"github.com/rett/tacctl/internal/yamlpy"
)

// Header is RENDER_HEADER, the comment block tacquito.yaml starts with.
const Header = "# GENERATED by tacctl from /etc/tacctl/store.yaml and tacctl.yaml. Edits here are overwritten.\n" +
	"# Use tacctl commands, or 'tacctl store import --replace' to adopt manual edits.\n" +
	"#\n" +
	"# Tacquito TACACS+ server configuration (Cisco IOS/IOS-XE + Juniper).\n"

// BuiltinRenderOrder is the order the built-in groups are listed in.
var BuiltinRenderOrder = []string{"readonly", "operator", "superuser"}

// yamlWords are the words PyYAML (YAML 1.1) reads as a boolean or null
// when left unquoted.
var yamlWords = []string{"y", "n", "yes", "no", "on", "off", "true", "false", "null"}

// LegacyTopKeys and LegacyConstants are the importer's (lib/model.sh)
// top-level keys of the layout; with file_accounter they are the keys a
// group may not take (RENDER_TOP_KEYS).
var (
	LegacyTopKeys   = []string{"users", "secrets", "prefix_allow", "prefix_deny"}
	LegacyConstants = []string{"authenticator_type_bcrypt", "action_deny", "action_permit",
		"accounter_type_file", "handler_type_start", "provider_type_prefix"}
	renderKeyPrefixes = []string{"exec_", "junos_exec_", "bcrypt_", "group_"}
)

// Actions are the values tacquito gives a command rule's action.
var Actions = map[string]int{"permit": 2, "deny": 1}

// Protocol is the scope 'protocols' entry this backend serves.
const Protocol = "tacacs"

// YQ is yq: a YAML double-quoted scalar that every YAML parser decodes to
// exactly s; the result is ASCII ("\xNN", "\uNNNN", "\UNNNNNNNN" escapes).
func YQ(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch {
		case r == '"' || r == '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case r >= 0x20 && r < 0x7f:
			b.WriteRune(r)
		case r <= 0xff:
			fmt.Fprintf(&b, `\x%02x`, r)
		case r <= 0xffff:
			fmt.Fprintf(&b, `\u%04x`, r)
		default:
			fmt.Fprintf(&b, `\U%08x`, r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

var reName = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_-]*$`)

// YName is yname: a name as a plain scalar, as tacctl always wrote it,
// unless a parser could read that as something other than the string.
func YName(s string) string {
	if reName.MatchString(s) && !slices.Contains(yamlWords, strings.ToLower(s)) {
		return s
	}
	return YQ(s)
}

// GroupKey is group_key: the top-level key and anchor of a group, its
// name unless that would collide with a key the layout owns.
func GroupKey(name string) string {
	if slices.Contains(LegacyTopKeys, name) || slices.Contains(LegacyConstants, name) || name == "file_accounter" {
		return "group_" + name
	}
	for _, p := range renderKeyPrefixes {
		if strings.HasPrefix(name, p) {
			return "group_" + name
		}
	}
	return name
}

// GroupOrder is group_order: the built-in groups present in their order,
// then the others by name.
func GroupOrder(names []string) []string {
	var first, rest []string
	for _, b := range BuiltinRenderOrder {
		if slices.Contains(names, b) {
			first = append(first, b)
		}
	}
	for _, n := range names {
		if !slices.Contains(first, n) {
			rest = append(rest, n)
		}
	}
	sort.Strings(rest)
	return append(first, rest...)
}

// Rule is one validated command rule of commands.<group>.
type Rule struct {
	Name   string
	Action string // permit | deny
	Match  []string
}

// truthy is Python's bool() of a tacctl.yaml value.
func truthy(v any) bool {
	switch x := v.(type) {
	case nil:
		return false
	case bool:
		return x
	case string:
		return x != ""
	case float64:
		return x != 0
	case *yamlpy.Map:
		return x.Len() > 0
	}
	if b := py.BigInt(v); b != nil {
		return b.Sign() != 0
	}
	if l, ok := py.List(v); ok {
		return len(l) > 0
	}
	return true
}

func get(v any, key string) (any, bool) {
	m, ok := v.(*yamlpy.Map)
	if !ok {
		return nil, false
	}
	return m.Get(key)
}

// GroupCommands is group_commands: commands.<group> of the merged
// tacctl.yaml view as validated rules.
func GroupCommands(view *yamlpy.Map, group string) ([]Rule, error) {
	cmds, _ := view.Get("commands")
	if !truthy(cmds) {
		return nil, nil
	}
	if _, ok := cmds.(*yamlpy.Map); !ok {
		// 0.1.16 died with a Python traceback here.
		return nil, &rendered.Error{Msg: "tacctl.yaml: commands is not a mapping of groups"}
	}
	rules, _ := get(cmds, group)
	if !truthy(rules) {
		return nil, nil
	}
	list, ok := py.List(rules)
	if !ok {
		return nil, &rendered.Error{Msg: fmt.Sprintf("tacctl.yaml: commands.%s is not a list of rules", group)}
	}
	var out []Rule
	for _, r := range list {
		nameV, _ := get(r, "name")
		name, isStr := nameV.(string)
		if _, isMap := r.(*yamlpy.Map); !isMap || !isStr || name == "" {
			return nil, &rendered.Error{Msg: fmt.Sprintf("tacctl.yaml: commands.%s has a rule without a name", group)}
		}
		actionV, has := get(r, "action")
		if !has {
			actionV = "permit"
		}
		action, isStr := actionV.(string)
		if _, known := Actions[action]; !isStr || !known {
			return nil, &rendered.Error{Msg: fmt.Sprintf("tacctl.yaml: commands.%s: rule '%s' has an action that is neither permit nor deny", group, name)}
		}
		matchV, _ := get(r, "match")
		var match []string
		if truthy(matchV) {
			items, isList := py.List(matchV)
			if !isList {
				return nil, &rendered.Error{Msg: fmt.Sprintf("tacctl.yaml: commands.%s: rule '%s' has a match that is not a list of strings", group, name)}
			}
			for _, m := range items {
				s, isStr := m.(string)
				if !isStr {
					return nil, &rendered.Error{Msg: fmt.Sprintf("tacctl.yaml: commands.%s: rule '%s' has a match that is not a list of strings", group, name)}
				}
				match = append(match, s)
			}
		}
		out = append(out, Rule{Name: name, Action: action, Match: match})
	}
	return out, nil
}

// RenderedHash is rendered_hash: what goes in the file for a user, the
// real hash or the marker nothing matches.
func RenderedHash(u *model.User) string {
	if u.IsDisabled() {
		return hash.DisabledMarkerHex
	}
	return u.Hash
}

func isDigits(s string) bool {
	if s == "" {
		return false
	}
	for i := 0; i < len(s); i++ {
		if s[i] < '0' || s[i] > '9' {
			return false
		}
	}
	return true
}

// cidrKey is cidr_key of a CIDR the validator accepted.
func cidrKey(c string) cidr.Key {
	k, _ := cidr.SortKey(c)
	return k
}

// sortCIDRs is sorted(items, key=cidr_key) (stable).
func sortCIDRs(items []string) []string {
	out := slices.Clone(items)
	sort.SliceStable(out, func(i, j int) bool { return cidrKey(out[i]).Less(cidrKey(out[j])) })
	return out
}

func privText(g *model.Group) string {
	if g.PrivLvl == nil {
		return "None"
	}
	return strconv.Itoa(*g.PrivLvl)
}

// Render is render_tacacs: the store and the merged tacctl.yaml view ->
// the text of tacquito.yaml. A store that does not validate is refused
// with every problem ('cannot render an invalid model: ...'), and so is a
// command rule of tacctl.yaml that is not one. The output depends only on
// the inputs, so an unchanged model renders byte-identically.
func Render(st *store.Store, view *yamlpy.Map) ([]byte, error) {
	if errs := store.Validate(st.Doc()); len(errs) > 0 {
		return nil, &rendered.Error{Msg: "cannot render an invalid model:\n  - " + strings.Join(errs, "\n  - ")}
	}
	m := model.FromStore(st)
	var w strings.Builder

	w.WriteString(Header)
	w.WriteString("\n# --- Type constants ---\n" +
		"authenticator_type_bcrypt: &authenticator_type_bcrypt 1\n" +
		"action_deny:  &action_deny  1\n" +
		"action_permit: &action_permit 2\n" +
		"accounter_type_file: &accounter_type_file 3\n" +
		"handler_type_start: &handler_type_start 1\n" +
		"provider_type_prefix: &provider_type_prefix 1\n" +
		"\n# --- Accounting ---\n" +
		"file_accounter: &file_accounter\n" +
		"  name: tacquito_accounter\n" +
		"  type: *accounter_type_file\n" +
		"\n# --- Per-user bcrypt authenticators ---\n" +
		"# A disabled account and the 'root' accounting sink carry a well-formed\n" +
		"# hash that no password matches.\n")
	for _, u := range m.Users {
		h := RenderedHash(u)
		// All-digit hex would read as a number; nothing else needs quotes.
		if isDigits(h) {
			h = YQ(h)
		}
		fmt.Fprintf(&w, "\nbcrypt_%s: &bcrypt_%s\n"+
			"  type: *authenticator_type_bcrypt\n"+
			"  options:\n"+
			"    hash: %s\n", u.Name, u.Name, h)
	}

	w.WriteString("\n# --- Services ---\n" +
		"# Cisco IOS/IOS-XE sends service=shell for exec authorization and expects\n" +
		"# priv-lvl; the anchors keep 'exec' as the label for the tier.\n" +
		"# Juniper requests service=junos-exec and expects local-user-name.\n" +
		"# Each device type only requests its own service; the other is ignored.\n")
	order := GroupOrder(m.GroupNames())
	for _, name := range order {
		g := m.Group(name)
		p := privText(g)
		fmt.Fprintf(&w, "\n# Cisco exec - %s (priv-lvl %s)\n"+
			"exec_%s: &exec_%s\n"+
			"  name: shell\n"+
			"  set_values:\n"+
			"    - name: priv-lvl\n"+
			"      values: [%s]\n"+
			"\n# Juniper junos-exec - %s\n"+
			"# \"%s\" must match a local template user on Juniper devices\n"+
			"junos_exec_%s: &junos_exec_%s\n"+
			"  name: junos-exec\n"+
			"  set_values:\n"+
			"    - name: local-user-name\n"+
			"      values: [%s]\n",
			name, p, name, name, p, name, g.JuniperClass, name, name, YQ(g.JuniperClass))
	}

	w.WriteString("\n# --- Groups ---\n" +
		"# Command rules come from commands.<group> in tacctl.yaml.\n")
	for i, name := range order {
		key := GroupKey(name)
		if i > 0 {
			w.WriteByte('\n')
		}
		fmt.Fprintf(&w, "%s: &%s\n"+
			"  name: %s\n"+
			"  services:\n"+
			"    - *exec_%s\n"+
			"    - *junos_exec_%s\n", YName(key), key, YName(name), name, name)
		rules, err := GroupCommands(view, name)
		if err != nil {
			return nil, err
		}
		if len(rules) > 0 {
			w.WriteString("  commands:\n")
			for _, r := range rules {
				fmt.Fprintf(&w, "    - name: %s\n", YQ(r.Name))
				if len(r.Match) > 0 {
					q := make([]string, len(r.Match))
					for i, s := range r.Match {
						q[i] = YQ(s)
					}
					w.WriteString("      match: [" + strings.Join(q, ", ") + "]\n")
				}
				fmt.Fprintf(&w, "      action: *action_%s\n", r.Action)
			}
		}
		w.WriteString("  accounter: *file_accounter\n")
	}

	w.WriteString("\n# --- Users ---\n")
	if len(m.Users) > 0 {
		w.WriteString("users:\n")
		for _, u := range m.Users {
			var mine []string
			for _, s := range u.Scopes {
				if sc := m.Scope(s); sc != nil && sc.ServedBy(Protocol) {
					mine = append(mine, YQ(s))
				}
			}
			fmt.Fprintf(&w, "\n  # %s\n"+
				"  - name: %s\n"+
				"    scopes: [%s]\n"+
				"    groups: [*%s]\n"+
				"    authenticator: *bcrypt_%s\n"+
				"    accounter: *file_accounter\n",
				u.Name, YName(u.Name), strings.Join(mine, ", "), GroupKey(u.Group), u.Name)
		}
	} else {
		w.WriteString("users: []\n")
	}

	w.WriteString("\n# --- Secret Providers (Scopes) ---\n" +
		"# One entry per (scope, prefix), most specific prefix first: tacquito\n" +
		"# answers a client with the first entry whose prefix contains it.\n")
	type entry struct {
		cidr, scope string
		key         cidr.Key
	}
	var entries []entry
	for _, sc := range m.Scopes {
		if !sc.ServedBy(Protocol) {
			continue
		}
		for _, c := range sc.Prefixes {
			entries = append(entries, entry{c, sc.Name, cidrKey(c)})
		}
	}
	sort.SliceStable(entries, func(i, j int) bool {
		a, b := entries[i], entries[j]
		if a.key != b.key {
			return a.key.Less(b.key)
		}
		return a.scope < b.scope
	})
	if len(entries) > 0 {
		w.WriteString("secrets:\n")
		for _, e := range entries {
			cj, _ := py.Dumps(e.cidr)
			fmt.Fprintf(&w, "  - name: %s\n"+
				"    secret:\n"+
				"      group: tacquito\n"+
				"      key: %s\n"+
				"    handler:\n"+
				"      type: *handler_type_start\n"+
				"    type: *provider_type_prefix\n"+
				"    options:\n"+
				"      prefixes: |\n"+
				"        [\n"+
				"          %s\n"+
				"        ]\n", YName(e.scope), YQ(m.Scope(e.scope).Secret), cj)
		}
	} else {
		w.WriteString("secrets: []\n")
	}

	var lines []string
	for _, f := range []struct {
		items []string
		key   string
	}{{m.Filters.Allow, "prefix_allow"}, {m.Filters.Deny, "prefix_deny"}} {
		items := sortCIDRs(f.items)
		if len(items) > 0 {
			q := make([]string, len(items))
			for i, c := range items {
				q[i] = YQ(c)
			}
			lines = append(lines, f.key+": ["+strings.Join(q, ", ")+"]\n")
		}
	}
	if len(lines) > 0 {
		w.WriteString("\n# --- Connection filters ---\n" + strings.Join(lines, ""))
	}
	return []byte(w.String()), nil
}

// isLevel is is_int(level) and 0 <= level <= 100.
func isLevel(v any) bool {
	b := py.BigInt(v)
	return b != nil && b.Sign() >= 0 && b.Cmp(big.NewInt(100)) <= 0
}
