package tacacs

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strings"
	"testing"

	"github.com/rett/tacctl/internal/hash"
	"github.com/rett/tacctl/internal/model"
	"github.com/rett/tacctl/internal/rendered"
	"github.com/rett/tacctl/internal/store"
	"github.com/rett/tacctl/internal/yamlpy"
)

// Ported from tests/unit/render_tacacs.bats ("golden output", "content
// rules", "quoting", "refusals"); the corpus test covers the same ground
// against 0.1.16 byte for byte.

func TestRenderMinimalGolden(t *testing.T) {
	out, err := renderFile(t, loadStore(t, "store.minimal.yaml"), defaultView(t))
	if err != nil {
		t.Fatal(rendered.Report(err))
	}
	if st, _ := os.Stat(out); st.Mode().Perm() != 0o640 {
		t.Fatalf("mode %v, want 0640", st.Mode().Perm())
	}
	diffText(t, readFile(t, out), readFile(t, filepath.Join(goldenDir, "tacquito.minimal.rendered.yaml")), "minimal")
}

func TestRenderMultiscopeGolden(t *testing.T) {
	out, err := renderFile(t, loadStore(t, "store.multiscope.yaml"), defaultView(t))
	if err != nil {
		t.Fatal(rendered.Report(err))
	}
	diffText(t, readFile(t, out), readFile(t, filepath.Join(goldenDir, "tacquito.multiscope.rendered.yaml")), "multiscope")
	// The pure renderer says the same.
	diffText(t, render(t, loadStore(t, "store.multiscope.yaml"), defaultView(t)),
		readFile(t, filepath.Join(goldenDir, "tacquito.multiscope.rendered.yaml")), "Render")
}

func TestRenderLeavesNoTempFileAndReplacesAtomically(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "rendered.yaml")
	writeFile(t, out, "previous content\n")
	if _, err := RenderToFile(loadStore(t, "store.multiscope.yaml"), defaultView(t), out, testLoad, nil); err != nil {
		t.Fatal(err)
	}
	if m, _ := filepath.Glob(filepath.Join(dir, ".tacquito.*")); len(m) > 0 {
		t.Fatalf("temp files left: %v", m)
	}
	if !strings.HasPrefix(string(readFile(t, out)), "# GENERATED by tacctl") {
		t.Fatal("target not replaced")
	}
}

func TestRenderSecretsOnePerScopePrefixMostSpecificFirst(t *testing.T) {
	d := decoded(t, render(t, loadStore(t, "store.multiscope.yaml"), defaultView(t)))
	var got []string
	for _, s := range d["secrets"].([]any) {
		m := s.(map[string]any)
		block := m["options"].(map[string]any)["prefixes"].(string)
		var prefixes []string
		for _, l := range strings.Split(block, "\n") {
			if l = strings.TrimSpace(l); strings.HasPrefix(l, `"`) {
				prefixes = append(prefixes, strings.Trim(l, `"`))
			}
		}
		if len(prefixes) != 1 {
			t.Fatalf("entry with %d prefixes", len(prefixes))
		}
		got = append(got, m["name"].(string)+"="+prefixes[0])
	}
	want := "prod-inner=10.10.99.0/24 prod=10.0.0.0/8 lab=172.16.0.0/12 lab=192.168.0.0/16 dmz=203.0.113.0/24"
	if strings.Join(got, " ") != want {
		t.Fatalf("got %s", strings.Join(got, " "))
	}
}

func TestRenderEveryUserHasItsAuthenticatorAndTheFileAccounter(t *testing.T) {
	users := usersOf(decoded(t, render(t, loadStore(t, "store.multiscope.yaml"), defaultView(t))))
	for name, u := range users {
		if !reflect.DeepEqual(u["accounter"], map[string]any{"name": "tacquito_accounter", "type": 3}) {
			t.Fatalf("%s: accounter %v", name, u["accounter"])
		}
		if u["authenticator"].(map[string]any)["type"] != 1 || len(u["groups"].([]any)) != 1 {
			t.Fatalf("%s: %v", name, u)
		}
	}
	alice := users["alice"]
	if g := alice["groups"].([]any)[0].(map[string]any)["name"]; g != "superuser" ||
		!reflect.DeepEqual(alice["scopes"], []any{"prod", "lab"}) {
		t.Fatalf("alice: %v %v", g, alice["scopes"])
	}
}

func TestRenderDisabledUsersAndTheSinkGetTheMarker(t *testing.T) {
	st := loadStore(t, "store.multiscope.yaml")
	entry(st, "users", "alice").Set("disabled", true)
	entry(st, "users", "bob").Set("hash", nil)
	entry(st, "users", "bob").Set("disabled", true)
	section(st, "users").Set("root", yamlpy.NewMap("group", "readonly", "scopes", []any{"lab"}, "hash", nil,
		"disabled", true, "password_changed", nil, "accounting_sink", true))
	text := render(t, st, defaultView(t))
	var marked []string
	for name, u := range usersOf(decoded(t, text)) {
		if u["authenticator"].(map[string]any)["options"].(map[string]any)["hash"] == hash.DisabledMarkerHex {
			marked = append(marked, name)
		}
	}
	if fmt.Sprint(sortedStrings(marked)) != "[alice bob root]" {
		t.Fatalf("marked: %v", marked)
	}
	// alice's real hash stays in the store only.
	if n := strings.Count(string(text), "646f6e7463617265"); n != 1 {
		t.Fatalf("the real hash appears %d times", n)
	}
}

func sortedStrings(s []string) []string {
	out := append([]string(nil), s...)
	for i := range out {
		for j := i + 1; j < len(out); j++ {
			if out[j] < out[i] {
				out[i], out[j] = out[j], out[i]
			}
		}
	}
	return out
}

func TestRenderScopeOfAnotherProtocolIsLeftOut(t *testing.T) {
	st := loadStore(t, "store.multiscope.yaml")
	entry(st, "scopes", "dmz").Set("protocols", []any{"radius"})
	entry(st, "scopes", "lab").Set("protocols", []any{"tacacs", "radius"})
	d := decoded(t, render(t, st, defaultView(t)))
	names := map[string]bool{}
	for _, s := range d["secrets"].([]any) {
		names[s.(map[string]any)["name"].(string)] = true
	}
	if !reflect.DeepEqual(names, map[string]bool{"lab": true, "prod": true, "prod-inner": true}) {
		t.Fatalf("scopes %v", names)
	}
	if got := usersOf(d)["carol"]["scopes"]; !reflect.DeepEqual(got, []any{"lab"}) {
		t.Fatalf("carol's scopes %v", got)
	}
}

func TestRenderCustomGroupsFollowTheBuiltins(t *testing.T) {
	st := loadStore(t, "store.multiscope.yaml")
	section(st, "groups").Set("helpdesk", yamlpy.NewMap("priv_lvl", 5, "juniper_class", "HELPDESK-CLASS", "builtin", false))
	section(st, "groups").Set("auditor", yamlpy.NewMap("priv_lvl", 2, "juniper_class", "AUDIT", "builtin", false))
	entry(st, "users", "bob").Set("group", "helpdesk")
	text := render(t, st, defaultView(t))
	keys := regexp.MustCompile(`(?m)^[a-z_]+: &[a-z]+$`).FindAllString(string(text), -1)
	if strings.Join(keys, "|") != "readonly: &readonly|operator: &operator|superuser: &superuser|auditor: &auditor|helpdesk: &helpdesk" {
		t.Fatalf("group keys %v", keys)
	}
	g := usersOf(decoded(t, text))["bob"]["groups"].([]any)[0].(map[string]any)
	var svc []string
	for _, s := range g["services"].([]any) {
		m := s.(map[string]any)
		sv := m["set_values"].([]any)[0].(map[string]any)
		svc = append(svc, fmt.Sprint(m["name"], " ", sv["name"], " ", sv["values"]))
	}
	if g["name"] != "helpdesk" || strings.Join(svc, ", ") != "shell priv-lvl [5], junos-exec local-user-name [HELPDESK-CLASS]" {
		t.Fatalf("%v %v", g["name"], svc)
	}
	if _, has := g["commands"]; has {
		t.Fatal("helpdesk has command rules")
	}
}

func TestRenderCommandRulesReachTheDaemonCharacterForCharacter(t *testing.T) {
	c := viewOf(t, "commands:\n  operator:\n"+
		`    - {name: show, action: permit, match: ['^running-config\s*$', 'say "hi"', 'back\\slash']}`+"\n"+
		`    - {name: "*", action: deny}`+"\n  superuser: []\n")
	st := loadStore(t, "store.multiscope.yaml")
	out, err := renderFile(t, st, c.Merged())
	if err != nil {
		t.Fatal(rendered.Report(err))
	}
	users := usersOf(decoded(t, readFile(t, out)))
	op := users["bob"]["groups"].([]any)[0].(map[string]any)["commands"]
	want := []any{
		map[string]any{"name": "show", "match": []any{`^running-config\s*$`, `say "hi"`, `back\\slash`}, "action": 2},
		map[string]any{"name": "*", "action": 1},
	}
	if !reflect.DeepEqual(op, want) {
		t.Fatalf("operator rules %#v", op)
	}
	if _, has := users["alice"]["groups"].([]any)[0].(map[string]any)["commands"]; has {
		t.Fatal("superuser: [] still renders rules")
	}
	var names []string
	for _, r := range users["carol"]["groups"].([]any)[0].(map[string]any)["commands"].([]any) {
		names = append(names, r.(map[string]any)["name"].(string))
	}
	if strings.Join(names, " ") != "show ping traceroute *" {
		t.Fatalf("readonly rules %v", names)
	}
}

func TestRenderPrefixFiltersSortedAndOmittedWhenEmpty(t *testing.T) {
	st := loadStore(t, "store.multiscope.yaml")
	if strings.Contains(string(render(t, st, defaultView(t))), "\nprefix_") {
		t.Fatal("empty filters rendered")
	}
	section(st, "filters").Set("allow", []any{"10.0.0.0/8", "10.9.0.0/16"})
	section(st, "filters").Set("deny", []any{"10.9.9.0/24"})
	got := regexp.MustCompile(`(?m)^prefix_.*$`).FindAllString(string(render(t, st, defaultView(t))), -1)
	if strings.Join(got, "\n") != "prefix_allow: [\"10.9.0.0/16\", \"10.0.0.0/8\"]\nprefix_deny: [\"10.9.9.0/24\"]" {
		t.Fatalf("filters %q", got)
	}
}

func TestRenderSecretsWithQuotesBackslashesAndNonASCII(t *testing.T) {
	secret := "a\"b\\c: #d \u00e9\u2028\U0001f511 {e}"
	st := loadStore(t, "store.multiscope.yaml")
	entry(st, "scopes", "lab").Set("secret", secret)
	out, err := renderFile(t, st, defaultView(t))
	if err != nil {
		t.Fatal(rendered.Report(err))
	}
	text := readFile(t, out)
	for _, s := range decoded(t, text)["secrets"].([]any) {
		m := s.(map[string]any)
		if m["name"] == "lab" && m["secret"].(map[string]any)["key"] != secret {
			t.Fatalf("key %q", m["secret"].(map[string]any)["key"])
		}
	}
	// The file itself stays ASCII there.
	if n := strings.Count(string(text), `key: "a\"b\\c: #d \xe9\u2028\U0001f511 {e}"`); n != 2 {
		t.Fatalf("escaped key appears %d times", n)
	}
}

func TestRenderNamesQuotedAndCollidingGroupKeys(t *testing.T) {
	st := loadStore(t, "store.multiscope.yaml")
	for _, n := range []string{"no", "users", "exec_operator"} {
		section(st, "groups").Set(n, yamlpy.NewMap("priv_lvl", 3, "juniper_class", "C", "builtin", false))
	}
	section(st, "scopes").Set("on", yamlpy.NewMap("prefixes", []any{"198.51.100.0/24"}, "secret", "on-secret-0123456789abcdef", "protocols", nil))
	alice := func(group string, scopes []any) *yamlpy.Map {
		a := entry(st, "users", "alice")
		h, _ := a.Get("hash")
		return yamlpy.NewMap("group", group, "scopes", scopes, "hash", h, "disabled", false)
	}
	section(st, "users").Set("123", alice("no", []any{"on"}))
	section(st, "users").Set("null", alice("users", []any{"prod", "lab"}))
	section(st, "users").Set("Yes", alice("exec_operator", []any{"prod", "lab"}))
	out, err := renderFile(t, st, defaultView(t))
	if err != nil {
		t.Fatal(rendered.Report(err))
	}
	d := decoded(t, readFile(t, out))
	users := usersOf(d)
	if len(d["users"].([]any)) != 6 {
		t.Fatalf("%d users", len(d["users"].([]any)))
	}
	grp := func(u string) any { return users[u]["groups"].([]any)[0].(map[string]any)["name"] }
	if grp("123") != "no" || !reflect.DeepEqual(users["123"]["scopes"], []any{"on"}) || grp("null") != "users" || grp("Yes") != "exec_operator" {
		t.Fatalf("%v %v %v %v", grp("123"), users["123"]["scopes"], grp("null"), grp("Yes"))
	}
	var gk []string
	for k := range d {
		if strings.HasPrefix(k, "group_") {
			gk = append(gk, k)
		}
	}
	if fmt.Sprint(sortedStrings(gk)) != "[group_exec_operator group_users]" {
		t.Fatalf("group keys %v", gk)
	}
	eo := d["exec_operator"].(map[string]any)["set_values"].([]any)[0].(map[string]any)["values"]
	if !reflect.DeepEqual(eo, []any{7}) || d["group_exec_operator"].(map[string]any)["name"] != "exec_operator" {
		t.Fatalf("%v %v", eo, d["group_exec_operator"])
	}
}

func TestRenderAllDigitHashIsQuoted(t *testing.T) {
	digits := "24326224313224" + strings.Repeat("31", 53)
	st := loadStore(t, "store.multiscope.yaml")
	entry(st, "users", "bob").Set("hash", digits)
	out, err := renderFile(t, st, defaultView(t))
	if err != nil {
		t.Fatal(rendered.Report(err))
	}
	text := readFile(t, out)
	if strings.Count(string(text), `hash: "`+digits+`"`) != 1 {
		t.Fatal("the all-digit hash is not quoted once")
	}
	if h := usersOf(decoded(t, text))["bob"]["authenticator"].(map[string]any)["options"].(map[string]any)["hash"]; h != digits {
		t.Fatalf("hash reads back as %v", h)
	}
}

func TestRenderInvalidModelIsRefusedAndNothingWritten(t *testing.T) {
	st := loadStore(t, "store.multiscope.yaml")
	entry(st, "users", "bob").Set("group", "nosuch")
	out, err := renderFile(t, st, defaultView(t))
	if err == nil {
		t.Fatal("rendered an invalid model")
	}
	msg := rendered.Report(err)
	if !strings.Contains(msg, "cannot render an invalid model") || !strings.Contains(msg, "user 'bob': group 'nosuch' does not exist") {
		t.Fatalf("message %q", msg)
	}
	if _, err := os.Stat(out); err == nil {
		t.Fatal("something was written")
	}
}

func TestRenderUnparsableTacctlYAMLIsRefused(t *testing.T) {
	c := viewOf(t, "commands:\n  operator: [oops\n")
	err := CheckOverrides(c.Path)
	if err == nil || !strings.Contains(rendered.Report(err), "fix it before rendering") {
		t.Fatalf("got %v", err)
	}
	want := "tacctl render: " + c.Path + ": expected ',' or ']', but got '<stream end>' (line 3, column 1) -- fix it before rendering"
	if rendered.Report(err) != want {
		t.Fatalf("got  %q\nwant %q", rendered.Report(err), want)
	}
	// A file that is not a mapping, and one that is fine.
	if err := CheckOverrides(viewOf(t, "- a\n").Path); err == nil || !strings.HasSuffix(err.Error(), ": not a YAML mapping -- fix it before rendering") {
		t.Fatalf("got %v", err)
	}
	for _, ok := range []string{"", "# only a comment\n", "commands: {}\n"} {
		if err := CheckOverrides(viewOf(t, ok).Path); err != nil {
			t.Fatalf("%q: %v", ok, err)
		}
	}
	if err := CheckOverrides(""); err != nil {
		t.Fatal(err)
	}
	// 0.2.0 refuses YAML 0.1.16 read (§3.9 item 15) the same way.
	if err := CheckOverrides(viewOf(t, "a: &x 1\nb: *x\n").Path); err == nil || !strings.Contains(err.Error(), "is not supported in this file -- fix it before rendering") {
		t.Fatalf("got %v", err)
	}
}

func TestRenderUnknownActionIsRefused(t *testing.T) {
	c := viewOf(t, "commands:\n  operator:\n  - {name: show, action: allow}\n")
	_, err := Render(loadStore(t, "store.multiscope.yaml"), c.Merged())
	if err == nil || !strings.Contains(err.Error(), "neither permit nor deny") {
		t.Fatalf("got %v", err)
	}
}

func TestRenderCommandsNotAMappingIsRefused(t *testing.T) {
	// 0.1.16 died with a traceback here; 0.2.0 says what is wrong.
	c := viewOf(t, "commands: [1]\n")
	_, err := Render(loadStore(t, "store.multiscope.yaml"), c.Merged())
	if err == nil || rendered.Report(err) != "tacctl render: tacctl.yaml: commands is not a mapping of groups" {
		t.Fatalf("got %v", err)
	}
}

// The read-back catches a file that does not say what the model says: a
// secret whose backslashes lost their escapes reads back as another
// secret. (The bats test sabotaged the quoting helper; here the rendered
// file is damaged the same way.)
func TestReadbackCatchesAFileThatDoesNotSayWhatTheModelSays(t *testing.T) {
	st := loadStore(t, "store.multiscope.yaml")
	entry(st, "scopes", "lab").Set("secret", `tricky\\secret-0123456789`)
	text := render(t, st, defaultView(t))
	bad := strings.ReplaceAll(string(text), `tricky\\\\secret`, `tricky\\secret`)
	if bad == string(text) {
		t.Fatal("sabotage did not apply")
	}
	p := filepath.Join(t.TempDir(), "bad.yaml")
	writeFile(t, p, bad)
	err := Readback(p, model.FromStore(st), defaultView(t), testLoad)
	if err == nil {
		t.Fatal("the damaged file read back as the model")
	}
	msg := rendered.Report(err)
	if !strings.Contains(msg, "does not read back as the model") || !strings.Contains(msg, "scopes differ") || strings.Contains(msg, "tricky") {
		t.Fatalf("message %q", msg)
	}
	if !strings.HasSuffix(msg, "). Nothing was written.") {
		t.Fatalf("message %q", msg)
	}
}

// RenderToFile writes nothing when the read-back fails, and says what
// the importer reported.
func TestRenderToFileWritesNothingWhenTheReadbackFails(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "tacquito.yaml")
	lying := func(path string) (*LegacyResult, error) {
		r, err := testLoad(path)
		if err != nil {
			return nil, err
		}
		r.Errors = []string{"users[0]: not a mapping"}
		r.Dropped = []string{"unknown top-level key 'x'"}
		return r, nil
	}
	_, err := RenderToFile(loadStore(t, "store.multiscope.yaml"), defaultView(t), out, lying, nil)
	want := "tacctl render: internal error: the rendered config does not read back as the model (" +
		"importer reports: users[0]: not a mapping; importer reports: unknown top-level key 'x'). Nothing was written."
	if err == nil || rendered.Report(err) != want {
		t.Fatalf("got %v", err)
	}
	if entries, _ := os.ReadDir(dir); len(entries) != 0 {
		t.Fatalf("left behind: %v", entries)
	}
	// A loader that refuses the file outright fails the render with its words.
	refusing := func(string) (*LegacyResult, error) {
		return nil, &store.Error{Msg: "x.yaml: top level is not a YAML mapping"}
	}
	if _, err := RenderToFile(loadStore(t, "store.multiscope.yaml"), defaultView(t), out, refusing, nil); err == nil ||
		rendered.Report(err) != "tacctl render: x.yaml: top level is not a YAML mapping" {
		t.Fatalf("got %v", err)
	}
	// No loader at all is an internal error, never an unchecked file.
	if _, err := RenderToFile(loadStore(t, "store.multiscope.yaml"), defaultView(t), out, nil, nil); err == nil {
		t.Fatal("rendered without a read-back")
	}
	if _, err := os.Stat(out); !errors.Is(err, os.ErrNotExist) {
		t.Fatal("something was written")
	}
}

// Each difference the read-back looks for is named.
func TestReadbackProblemsNamesEachDifference(t *testing.T) {
	st := loadStore(t, "store.multiscope.yaml")
	m := model.FromStore(st)
	p := filepath.Join(t.TempDir(), "t.yaml")
	writeFile(t, p, string(render(t, st, defaultView(t))))
	if probs, err := ReadbackProblems(p, m, testLoad); err != nil || len(probs) != 0 {
		t.Fatalf("%v %v", probs, err)
	}
	for _, tc := range []struct {
		edit func(st *store.Store)
		want string
	}{
		{func(st *store.Store) { entry(st, "groups", "operator").Set("priv_lvl", 6) }, "groups differ"},
		{func(st *store.Store) { entry(st, "groups", "operator").Set("juniper_class", "X") }, "groups differ"},
		{func(st *store.Store) { entry(st, "users", "bob").Set("scopes", []any{"prod"}) }, "users differ"},
		{func(st *store.Store) { entry(st, "users", "bob").Set("disabled", true) }, "users differ"},
		{func(st *store.Store) { entry(st, "scopes", "dmz").Set("prefixes", []any{"203.0.113.0/25"}) }, "scopes differ"},
		{func(st *store.Store) { entry(st, "scopes", "dmz").Set("protocols", []any{"radius"}) }, "users differ; scopes differ"},
		{func(st *store.Store) { section(st, "filters").Set("allow", []any{"10.0.0.0/8"}) }, "filters.allow differs"},
		{func(st *store.Store) { section(st, "filters").Set("deny", []any{"10.0.0.0/8"}) }, "filters.deny differs"},
	} {
		other := loadStore(t, "store.multiscope.yaml")
		tc.edit(other)
		probs, err := ReadbackProblems(p, model.FromStore(other), testLoad)
		if err != nil || strings.Join(probs, "; ") != tc.want {
			t.Fatalf("want %q, got %v %v", tc.want, probs, err)
		}
		if MatchesModel(p, model.FromStore(other), testLoad) {
			t.Fatal("matches")
		}
	}
	if !MatchesModel(p, m, testLoad) {
		t.Fatal("the render does not match its own model")
	}
	// Prefixes and filters compare canonicalised, deduplicated and sorted.
	if got := canonList([]string{"10.1.0.0/16", "10.0.0.0/8", " 10.1.0.0/16", "10.0.0.1/8"}); fmt.Sprint(got) != "[10.1.0.0/16 10.0.0.0/8]" {
		t.Fatalf("canonList %v", got)
	}
	if got := canonList([]string{"10.0.0.0/8", "bogus"}); fmt.Sprint(got) != "[10.0.0.0/8 bogus]" {
		t.Fatalf("canonList %v", got)
	}
	// A file whose command rules differ from tacctl.yaml.
	err := Readback(p, m, viewOf(t, "commands:\n  operator: []\n").Merged(), testLoad)
	if err == nil || !strings.Contains(err.Error(), "(command rules of group 'operator' differ)") {
		t.Fatalf("got %v", err)
	}
}

func TestQuotingHelpers(t *testing.T) {
	for in, want := range map[string]string{
		`plain`: `"plain"`, `a"b\c`: `"a\"b\\c"`,
		"\u00e9\u0100\u2028": `"\xe9\u0100\u2028"`, "\U0001f511": `"\U0001f511"`, "tab\t": `"tab\x09"`, "": `""`,
	} {
		if got := YQ(in); got != want {
			t.Fatalf("YQ(%q) = %s, want %s", in, got, want)
		}
	}
	if got := YQ("\x7f\u0080\u00ff"); got != `"\x7f\x80\xff"` {
		t.Fatalf("YQ: %s", got)
	}
	for in, want := range map[string]string{
		"lab": "lab", "_x": "_x", "a-b_9": "a-b_9", "No": `"No"`, "NULL": `"NULL"`, "y": `"y"`, "123": `"123"`,
		"-dash": `"-dash"`, "a.b": `"a.b"`, "": `""`, "yes1": "yes1", "Off": `"Off"`, "tRuE": `"tRuE"`,
	} {
		if got := YName(in); got != want {
			t.Fatalf("YName(%q) = %s, want %s", in, got, want)
		}
	}
	for in, want := range map[string]string{
		"users": "group_users", "secrets": "group_secrets", "prefix_allow": "group_prefix_allow",
		"action_deny": "group_action_deny", "file_accounter": "group_file_accounter", "exec_x": "group_exec_x",
		"junos_exec_x": "group_junos_exec_x", "bcrypt_x": "group_bcrypt_x", "group_x": "group_group_x",
		"operator": "operator", "execs": "execs", "user": "user",
	} {
		if got := GroupKey(in); got != want {
			t.Fatalf("GroupKey(%q) = %s, want %s", in, got, want)
		}
	}
	if got := GroupOrder([]string{"zz", "superuser", "aa", "readonly"}); fmt.Sprint(got) != "[readonly superuser aa zz]" {
		t.Fatalf("GroupOrder %v", got)
	}
}

func TestRenderedHash(t *testing.T) {
	for _, tc := range []struct {
		u    model.User
		want string
	}{
		{model.User{Hash: "abc"}, "abc"},
		{model.User{Hash: "abc", Disabled: true}, hash.DisabledMarkerHex},
		{model.User{Hash: "abc", AccountingSink: true}, hash.DisabledMarkerHex},
		{model.User{}, hash.DisabledMarkerHex},
	} {
		if got := RenderedHash(&tc.u); got != tc.want {
			t.Fatalf("%+v: %s", tc.u, got)
		}
	}
}

func TestGroupCommandsShapes(t *testing.T) {
	for text, want := range map[string]string{
		"":                                 "[{* permit []}]",
		"commands: {}\n":                   "[{* permit []}]", // a mapping merges into the defaults
		"commands:\n  superuser: ''\n":     "[]",
		"commands:\n  superuser: {}\n":     "[]",
		"commands:\n  superuser: {a: 1}\n": "tacctl.yaml: commands.superuser is not a list of rules",
		"commands:\n  superuser:\n  - {name: x, match: ''}\n":                   "[{x permit []}]",
		"commands:\n  superuser:\n  - {name: x, match: {}}\n":                   "[{x permit []}]",
		"commands:\n  superuser:\n  - {name: x, match: {a: 1}}\n":               "tacctl.yaml: commands.superuser: rule 'x' has a match that is not a list of strings",
		"commands:\n  superuser:\n  - {name: x, action: [permit]}\n":            "tacctl.yaml: commands.superuser: rule 'x' has an action that is neither permit nor deny",
		"commands:\n  superuser:\n  - {name: x, action: deny, match: [a, b]}\n": "[{x deny [a b]}]",
		"commands:\n  superuser:\n  - [x]\n":                                    "tacctl.yaml: commands.superuser has a rule without a name",
		"commands: ''\n":                                                        "[]",
		"commands: 5\n":                                                         "tacctl.yaml: commands is not a mapping of groups",
	} {
		rules, err := GroupCommands(viewOf(t, text).Merged(), "superuser")
		got := fmt.Sprint(rules)
		if err != nil {
			got = err.Error()
		}
		if rules == nil && err == nil {
			got = "[]"
		}
		if got != want {
			t.Fatalf("%q: got %s, want %s", text, got, want)
		}
	}
}
