package tacacs

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/rett/tacctl/internal/paths"
	"github.com/rett/tacctl/internal/rendered"
)

func productionPaths() Paths {
	return PathsFrom(paths.Resolve(paths.NewEnv(nil), "", func(string) bool { return false }))
}

func unitsOf(t *testing.T, tacctlYAML, logDir string) map[string]string {
	t.Helper()
	units, err := Units(viewOf(t, tacctlYAML).Merged(), logDir)
	if err != nil {
		t.Fatal(rendered.Report(err))
	}
	out := map[string]string{}
	for _, u := range units {
		out[u.Listener] = u.Text
	}
	return out
}

// The drop-ins with the production log directory, against 0.1.16's
// output (testdata/gen.py wrote the goldens from its corpus).
func TestDropInGoldens(t *testing.T) {
	logDir := productionPaths().LogDir
	def := unitsOf(t, "", logDir)
	if len(def) != 1 {
		t.Fatalf("listeners %v", def)
	}
	diffText(t, []byte(def["default"]), readFile(t, filepath.Join(goldenDir, "dropin.default.conf")), "dropin.default.conf")

	units, err := Units(viewOf(t, "backends:\n  tacacs:\n    level: 30\nlisteners:\n  tacacs:\n"+
		"    default:\n      network: tcp\n      address: 10.1.0.1:49\n"+
		"    mgmt:\n      network: tcp\n      address: 127.0.0.1:4949\n"+
		"    alt6:\n      network: tcp6\n      address: '[::1]:4950'\n      metrics_address: '[::1]:9100'\n").Merged(), logDir)
	if err != nil {
		t.Fatal(err)
	}
	var order []string
	for _, u := range units {
		order = append(order, u.Listener)
		golden := map[string]string{"default": "dropin.default-override.conf", "mgmt": "dropin.mgmt.conf", "alt6": "dropin.alt6.conf"}[u.Listener]
		diffText(t, []byte(u.Text), readFile(t, filepath.Join(goldenDir, golden)), golden)
	}
	// The default listener first, then the others by name.
	if strings.Join(order, " ") != "default alt6 mgmt" {
		t.Fatalf("order %v", order)
	}
}

// listeners.bats "drop-in: one settings change renders every flag of the
// default listener", at the renderer.
func TestDropInRendersEveryFlagOfTheDefaultListener(t *testing.T) {
	d := unitsOf(t, "listeners:\n  tacacs:\n    default: {network: tcp, address: '10.1.0.1:49'}\n", "/tmp/log")["default"]
	lines := strings.Split(d, "\n")
	if !strings.Contains(lines[0], "GENERATED by tacctl from tacctl.yaml") {
		t.Fatalf("first line %q", lines[0])
	}
	for _, want := range []string{"[Service]", `Environment="TACQUITO_NETWORK=tcp"`, `Environment="TACQUITO_ADDRESS=10.1.0.1:49"`,
		`Environment="TACQUITO_LEVEL=20"`, `Environment="TACQUITO_METRICS_ADDRESS=127.0.0.1:8080"`,
		`Environment="TACQUITO_ACCT_LOG=/tmp/log/accounting.log"`} {
		if !containsLine(lines, want) {
			t.Fatalf("no line %q in\n%s", want, d)
		}
	}
}

func containsLine(lines []string, want string) bool {
	for _, l := range lines {
		if l == want {
			return true
		}
	}
	return false
}

// "drop-in: an instance gets its own address, accounting log and no
// reachable metrics".
func TestDropInOfAnInstance(t *testing.T) {
	u := unitsOf(t, "backends:\n  tacacs:\n    level: 30\nlisteners:\n  tacacs:\n    mgmt: {network: tcp, address: '127.0.0.1:4949'}\n", "/l")
	mgmt := strings.Split(u["mgmt"], "\n")
	for _, want := range []string{`Environment="TACQUITO_NETWORK=tcp"`, `Environment="TACQUITO_ADDRESS=127.0.0.1:4949"`,
		`Environment="TACQUITO_LEVEL=30"`, `Environment="TACQUITO_METRICS_ADDRESS=127.0.0.1:0"`,
		`Environment="TACQUITO_ACCT_LOG=/l/accounting-mgmt.log"`} {
		if !containsLine(mgmt, want) {
			t.Fatalf("no line %q in\n%s", want, u["mgmt"])
		}
	}
	def := strings.Split(u["default"], "\n")
	if !containsLine(def, `Environment="TACQUITO_ADDRESS=:49"`) || !containsLine(def, `Environment="TACQUITO_ACCT_LOG=/l/accounting.log"`) {
		t.Fatalf("default:\n%s", u["default"])
	}
}

// "drop-in: a listener's own metrics_address is rendered; the default
// listener's is refused for it".
func TestDropInMetricsAddressOfAnInstance(t *testing.T) {
	u := unitsOf(t, "listeners:\n  tacacs:\n    mgmt: {network: tcp, address: '127.0.0.1:4949', metrics_address: '127.0.0.1:9100'}\n", "/l")
	if !containsLine(strings.Split(u["mgmt"], "\n"), `Environment="TACQUITO_METRICS_ADDRESS=127.0.0.1:9100"`) {
		t.Fatalf("mgmt:\n%s", u["mgmt"])
	}
	_, err := Units(viewOf(t, "listeners:\n  tacacs:\n    mgmt: {network: tcp, address: '127.0.0.1:4949', metrics_address: '127.0.0.1:8080'}\n").Merged(), "/l")
	if err == nil || !strings.Contains(err.Error(), "metrics_address 127.0.0.1:8080 is the default listener's") {
		t.Fatalf("got %v", err)
	}
	// The sink may be shared: it is not reachable.
	if _, err := Units(viewOf(t, "backends:\n  tacacs:\n    metrics_address: 127.0.0.1:0\nlisteners:\n  tacacs:\n    mgmt: {network: tcp, address: '127.0.0.1:4949'}\n").Merged(), "/l"); err != nil {
		t.Fatal(err)
	}
}

// "render: a listener model that cannot be served fails the render".
func TestDropInRefusals(t *testing.T) {
	for text, want := range map[string]string{
		"listeners:\n  tacacs:\n    tls: {network: tcp, address: ':300', tls: {enabled: true}}\n": "tacctl.yaml: listeners.tacacs.tls: tls.enabled: true is reserved for a future release (TLS listeners are not implemented)",
		"backends:\n  tacacs: [1]\n":                        "tacctl.yaml: backends.tacacs is not a mapping",
		"backends:\n  tacacs:\n    level: debug\n":          "tacctl.yaml: backends.tacacs.level is not a log level (10, 20 or 30)",
		"backends:\n  tacacs:\n    level: -1\n":             "tacctl.yaml: backends.tacacs.level is not a log level (10, 20 or 30)",
		"backends:\n  tacacs:\n    metrics_address: 80\n":   "tacctl.yaml: backends.tacacs.metrics_address must be a string host:port",
		"backends:\n  tacacs:\n    metrics_address: ':x'\n": "tacctl.yaml: backends.tacacs.metrics_address must be host:port (e.g. '127.0.0.1:8080' or ':8080')",
	} {
		_, err := Units(viewOf(t, text).Merged(), "/l")
		if err == nil || err.Error() != want {
			t.Fatalf("%q: got %v", text, err)
		}
	}
}

// '%' starts a specifier in a unit file, so it is doubled.
func TestDropInDoublesPercent(t *testing.T) {
	d := unitsOf(t, "", "/var/log/ta%cquito")["default"]
	if !strings.Contains(d, `Environment="TACQUITO_ACCT_LOG=/var/log/ta%%cquito/accounting.log"`+"\n") {
		t.Fatalf("got\n%s", d)
	}
}

// "units: the paths tacctl derives for a listener" (tests/unit/listeners.bats).
func TestUnitPaths(t *testing.T) {
	p := Paths{OverrideDir: "/o/tacquito.service.d", UnitDir: "/u", LogDir: "/log", AcctLog: "/log/accounting.log"}
	for _, tc := range [][2]string{
		{Unit("default"), "tacquito.service"}, {Unit(""), "tacquito.service"}, {Unit("mgmt"), "tacquito@mgmt.service"},
		{DropIn(p, "default"), "/o/tacquito.service.d/tacctl.conf"}, {DropIn(p, "mgmt"), "/u/tacquito@mgmt.service.d/tacctl.conf"},
		{AcctLog(p, "default"), "/log/accounting.log"}, {AcctLog(p, "mgmt"), "/log/accounting-mgmt.log"},
	} {
		if tc[0] != tc[1] {
			t.Fatalf("got %s, want %s", tc[0], tc[1])
		}
	}
	// Production paths, when nothing is overridden.
	prod := productionPaths()
	got := strings.Join([]string{"/etc/systemd/system/" + UnitName, DropIn(prod, "default"), DropIn(prod, "mgmt"),
		prod.OverrideDir + "/" + LegacyDropInName, prod.AcctLog, AcctLog(prod, "mgmt")}, " ")
	want := "/etc/systemd/system/tacquito.service /etc/systemd/system/tacquito.service.d/tacctl.conf " +
		"/etc/systemd/system/tacquito@mgmt.service.d/tacctl.conf /etc/systemd/system/tacquito.service.d/tacctl-overrides.conf " +
		"/var/log/tacquito/accounting.log /var/log/tacquito/accounting-mgmt.log"
	if got != want || prod.UnitDir != "/etc/systemd/system" {
		t.Fatalf("got  %s\nwant %s", got, want)
	}
	// TACCTL_SYSTEMD_DIR moves the instances, TACCTL_OVERRIDE_DIR the default.
	q := PathsFrom(paths.Resolve(paths.NewEnv([]string{"TACCTL_OVERRIDE_DIR=/x/d"}), "", func(string) bool { return false }))
	if DropIn(q, "mgmt") != "/x/tacquito@mgmt.service.d/tacctl.conf" || DropIn(q, "default") != "/x/d/tacctl.conf" {
		t.Fatalf("%s %s", DropIn(q, "mgmt"), DropIn(q, "default"))
	}
}

// "units: both take every per-listener flag from the environment", and
// the drop-in sets exactly those flags; the defaults the units carry are
// the renderer's ("the shell constants are the python renderer's and the
// unit's defaults", unit half).
func TestUnitsTakeEveryFlagTheDropInSets(t *testing.T) {
	d := unitsOf(t, "", "/l")["default"]
	var vars []string
	for _, m := range regexp.MustCompile(`(?m)^Environment="(TACQUITO_[A-Z_]+)=`).FindAllStringSubmatch(d, -1) {
		vars = append(vars, m[1])
	}
	if strings.Join(vars, " ") != "TACQUITO_NETWORK TACQUITO_ADDRESS TACQUITO_LEVEL TACQUITO_METRICS_ADDRESS TACQUITO_ACCT_LOG" {
		t.Fatalf("drop-in sets %v", vars)
	}
	for _, f := range []string{"tacquito.service", "tacquito@.service"} {
		unit := string(readFile(t, filepath.Join(unitsDir, f)))
		for _, v := range vars {
			if !strings.Contains(unit, "${"+v+"}") {
				t.Fatalf("%s does not use ${%s}", f, v)
			}
		}
	}
	unit := strings.Split(string(readFile(t, filepath.Join(unitsDir, "tacquito.service"))), "\n")
	for _, want := range []string{`Environment="TACQUITO_LEVEL=20"`, `Environment="TACQUITO_METRICS_ADDRESS=` + MetricsDefault + `"`,
		`Environment="TACQUITO_NETWORK=tcp"`, `Environment="TACQUITO_ADDRESS=:49"`} {
		if !containsLine(unit, want) {
			t.Fatalf("tacquito.service has no %s", want)
		}
	}
	if LevelDefault != 20 {
		t.Fatal("LevelDefault")
	}
}

// "units: an instance belongs to tacquito.service and needs its rendered
// drop-in": the template asserts the drop-in this package renders, and
// its accounting log default is the one AcctLog names.
func TestInstanceTemplateNeedsTheRenderedDropIn(t *testing.T) {
	tmpl := strings.Split(string(readFile(t, filepath.Join(unitsDir, "tacquito@.service"))), "\n")
	prod := productionPaths()
	for _, want := range []string{"PartOf=tacquito.service", "WantedBy=tacquito.service",
		"AssertPathExists=" + DropIn(prod, "%i"),
		`Environment="TACQUITO_ACCT_LOG=` + AcctLog(prod, "%i") + `"`,
		`Environment="TACQUITO_METRICS_ADDRESS=` + MetricsSink + `"`} {
		if !containsLine(tmpl, want) {
			t.Fatalf("tacquito@.service has no line %q", want)
		}
	}
	for _, l := range tmpl {
		if strings.HasPrefix(l, `Environment="TACQUITO_NETWORK=`) || strings.HasPrefix(l, `Environment="TACQUITO_ADDRESS=`) || strings.HasPrefix(l, "Alias=") {
			t.Fatalf("tacquito@.service has %q", l)
		}
	}
}

func TestStageUnitsIndexAndReadIndex(t *testing.T) {
	w := t.TempDir()
	p := Paths{OverrideDir: filepath.Join(w, "sd", "tacquito.service.d"), UnitDir: filepath.Join(w, "sd"),
		LogDir: "/l", Rendered: filepath.Join(w, "rendered.json")}
	view := viewOf(t, "listeners:\n  tacacs:\n    mgmt: {network: tcp, address: '127.0.0.1:4949'}\n").Merged()
	units, err := Units(view, "/l")
	if err != nil {
		t.Fatal(err)
	}
	// The default drop-in is live and as rendered, mgmt's is not there.
	writeFile(t, DropIn(p, "default"), units[0].Text)
	out := filepath.Join(w, "stage", "units")
	idx, err := StageUnits(view, out, p)
	if err != nil {
		t.Fatal(err)
	}
	want := "default\tsame\t" + DropIn(p, "default") + "\nmgmt\tmissing\t" + DropIn(p, "mgmt") + "\n"
	if got := string(readFile(t, filepath.Join(out, IndexName))); got != want {
		t.Fatalf("index\n%q\nwant\n%q", got, want)
	}
	back, err := ReadIndex(out)
	if err != nil || len(back) != 2 || back[0] != idx[0] || back[1] != idx[1] || back[1].Status != rendered.Missing {
		t.Fatalf("%v %v %v", back, idx, err)
	}
	if string(readFile(t, filepath.Join(out, "mgmt.conf"))) != units[1].Text {
		t.Fatal("mgmt.conf")
	}
	// Recorded: current.
	if err := rendered.Record(p.Rendered, DropIn(p, "default")); err != nil {
		t.Fatal(err)
	}
	idx, _ = StageUnits(view, out, p)
	if idx[0].Status != rendered.Current {
		t.Fatalf("%v", idx)
	}
	// No index: no units.
	if l, err := ReadIndex(filepath.Join(w, "nothing")); l != nil || err != nil {
		t.Fatalf("%v %v", l, err)
	}
	// A listener model that cannot be served stages nothing.
	if _, err := StageUnits(viewOf(t, "backends:\n  tacacs:\n    level: x\n").Merged(), filepath.Join(w, "s2"), p); err == nil {
		t.Fatal("staged")
	}
	if _, err := os.Stat(filepath.Join(w, "s2")); err == nil {
		t.Fatal("the stage dir was created")
	}
}
