package tacacs

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/rett/tacctl/internal/conf"
	"github.com/rett/tacctl/internal/py"
	"github.com/rett/tacctl/internal/rendered"
	"github.com/rett/tacctl/internal/yamlpy"
)

// The unit names and the flag defaults of config/backends/tacacs (the
// TACACS_* constants of lib/backends/tacacs.sh).
const (
	// UnitName is the unit of the default listener, and the name operators
	// and tacctl use for the service as a whole.
	UnitName = "tacquito.service"
	// DropInName is the drop-in tacctl renders into a unit's .d directory.
	DropInName = "tacctl.conf"
	// LegacyDropInName is the hand-managed drop-in of installs from before
	// the listener model (OVERRIDE_FILE's base name).
	LegacyDropInName = "tacctl-overrides.conf"
	// LevelDefault is TACACS_LEVEL_DEFAULT.
	LevelDefault = 20
	// MetricsDefault is TACACS_METRICS_DEFAULT.
	MetricsDefault = "127.0.0.1:8080"
	// MetricsSink is TACACS_METRICS_SINK: "no exporter", a loopback port
	// nobody can know; also what keeps two processes off one metrics port.
	MetricsSink = "127.0.0.1:0"
)

// DropInHeader is DROPIN_HEADER.
const DropInHeader = "# GENERATED by tacctl from tacctl.yaml (listeners.tacacs and backends.tacacs). Edits here are overwritten.\n" +
	"# Change these with 'tacctl config listen', 'tacctl config loglevel' and 'tacctl config metrics';\n" +
	"# unit settings of your own belong in another .conf file of this directory.\n"

// isDefault: "" and "default" both name the default listener, as the
// bash helpers' ${1:-default}.
func isDefault(listener string) bool { return listener == "" || listener == "default" }

// Unit is _tacacs_unit: the systemd unit that serves a listener.
func Unit(listener string) string {
	if isDefault(listener) {
		return UnitName
	}
	return "tacquito@" + listener + ".service"
}

// DropIn is _tacacs_dropin: the drop-in tacctl renders for a listener.
func DropIn(p Paths, listener string) string {
	if isDefault(listener) {
		return p.OverrideDir + "/" + DropInName
	}
	return p.UnitDir + "/tacquito@" + listener + ".service.d/" + DropInName
}

// AcctLog is _tacacs_acct_log: a listener's accounting log.
func AcctLog(p Paths, listener string) string {
	if isDefault(listener) {
		return p.AcctLog
	}
	return p.LogDir + "/accounting-" + listener + ".log"
}

// pyJoin is os.path.join(a, b) for a relative b.
func pyJoin(a, b string) string {
	if a == "" || strings.HasSuffix(a, "/") {
		return a + b
	}
	return a + "/" + b
}

// Unit drop-in text for one listener.
type DropInText struct {
	Listener string // its name in listeners.tacacs
	Text     string
}

// Units is tacacs_units: the drop-in text of every listener of
// listeners.tacacs in the merged view, the default listener first.
// logDir is where the accounting logs go (LOG_DIR). A listener model that
// cannot be served is refused: an invalid entry, two listeners on one
// address, reserved TLS, a bad backends.tacacs.level or metrics_address,
// or an instance on the default listener's metrics address.
func Units(view *yamlpy.Map, logDir string) ([]DropInText, error) {
	if problems := conf.ListenersProblems(view, "", false); len(problems) > 0 {
		return nil, &rendered.Error{Msg: "tacctl.yaml: " + strings.Join(problems, "; ")}
	}
	backends, _ := view.Get("backends")
	var settings any
	if bm, ok := backends.(*yamlpy.Map); ok {
		settings, _ = bm.Get("tacacs")
	}
	if !truthy(settings) {
		settings = yamlpy.NewMap()
	}
	sm, ok := settings.(*yamlpy.Map)
	if !ok {
		return nil, &rendered.Error{Msg: "tacctl.yaml: backends.tacacs is not a mapping"}
	}
	level, has := sm.Get("level")
	if !has {
		level = LevelDefault
	}
	if !isLevel(level) {
		return nil, &rendered.Error{Msg: "tacctl.yaml: backends.tacacs.level is not a log level (10, 20 or 30)"}
	}
	metricsV, has := sm.Get("metrics_address")
	if !has {
		metricsV = MetricsDefault
	}
	if why := conf.HostPortProblem(metricsV); why != "" {
		return nil, &rendered.Error{Msg: "tacctl.yaml: backends.tacacs.metrics_address " + why}
	}
	metrics := metricsV.(string) // HostPortProblem accepts strings only
	var out []DropInText
	for _, l := range conf.ListenersEffective(view, Protocol) {
		mine, log := metrics, "accounting.log"
		if l.Name != "default" {
			mine, log = l.MetricsAddress, "accounting-"+l.Name+".log"
			if mine == "" {
				mine = MetricsSink
			}
			if mine == metrics && !strings.HasSuffix(mine, ":0") {
				return nil, &rendered.Error{Msg: fmt.Sprintf(
					"tacctl.yaml: listeners.tacacs.%s: metrics_address %s is the default listener's (backends.tacacs.metrics_address)", l.Name, mine)}
			}
		}
		env := [][2]string{
			{"TACQUITO_NETWORK", l.Network},
			{"TACQUITO_ADDRESS", l.Address},
			{"TACQUITO_LEVEL", py.Str(level)},
			{"TACQUITO_METRICS_ADDRESS", mine},
			{"TACQUITO_ACCT_LOG", pyJoin(logDir, log)},
		}
		var b strings.Builder
		b.WriteString(DropInHeader + "[Service]\n")
		for _, kv := range env {
			// '%' starts a specifier in a unit file.
			fmt.Fprintf(&b, "Environment=\"%s=%s\"\n", kv[0], strings.ReplaceAll(kv[1], "%", "%%"))
		}
		out = append(out, DropInText{Listener: l.Name, Text: b.String()})
	}
	return out, nil
}

// UnitState is one line of a staged units index: a listener, how its live
// drop-in stands against the render (rendered.LiveStatus's words), and
// that drop-in's absolute path.
type UnitState struct {
	Listener string
	Status   string
	Live     string
}

// IndexName is the index file of a staged units directory.
const IndexName = "index"

// StageUnits is render_units: write every listener's drop-in to
// <outDir>/<name>.conf and the index, one '<name>\t<status>\t<live path>'
// line each, and return the index. The live drop-in of the default
// listener is p's DropIn; an instance's is its tacquito@<name>.service.d
// directory under p.UnitDir. Records that are not usable JSON make every
// word same or unreadable.
func StageUnits(view *yamlpy.Map, outDir string, p Paths) ([]UnitState, error) {
	units, err := Units(view, p.LogDir)
	if err != nil {
		return nil, err
	}
	records, err := rendered.LoadOrNil(p.Rendered)
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(outDir, 0o777); err != nil {
		return nil, err
	}
	defaultDropIn := DropIn(p, "default")
	var index []UnitState
	var lines strings.Builder
	for _, u := range units {
		live := defaultDropIn
		if u.Listener != "default" {
			live = pyJoin(pyJoin(p.UnitDir, "tacquito@"+u.Listener+".service.d"), filepath.Base(defaultDropIn))
		}
		live = rendered.Abs(live)
		if err := os.WriteFile(filepath.Join(outDir, u.Listener+".conf"), []byte(u.Text), 0o666); err != nil {
			return nil, err
		}
		status, err := rendered.UnitStatus(records, live, []byte(u.Text))
		if err != nil {
			return nil, err
		}
		index = append(index, UnitState{u.Listener, status, live})
		lines.WriteString(u.Listener + "\t" + status + "\t" + live + "\n")
	}
	if err := os.WriteFile(filepath.Join(outDir, IndexName), []byte(lines.String()), 0o666); err != nil {
		return nil, err
	}
	return index, nil
}

// ReadIndex reads a units index StageUnits wrote ('read -r name status
// live' per line; empty names are skipped). A missing index is no units.
func ReadIndex(dir string) ([]UnitState, error) {
	data, err := os.ReadFile(filepath.Join(dir, IndexName))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var out []UnitState
	for _, line := range strings.Split(strings.TrimSuffix(string(data), "\n"), "\n") {
		f := strings.SplitN(line, "\t", 3)
		if f[0] == "" {
			continue
		}
		for len(f) < 3 {
			f = append(f, "")
		}
		out = append(out, UnitState{f[0], f[1], f[2]})
	}
	return out, nil
}
