package tacacs

import (
	"context"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"

	"github.com/rett/tacctl/internal/backend"
)

// The listeners verb and 'tacctl config listen' below its argument parsing
// (tests/integration/listeners.bats, tests/unit/backend.bats "tacacs
// listeners", tests/integration/config_setters.bats "config listen"), with
// systemctl scripted as the bats stub does. The flag parsing, the usage
// block and the backend/listener-name checks are internal/cli's (WP2.4c).

func lines(ls []backend.Listener) []string {
	var out []string
	for _, l := range ls {
		out = append(out, l.Name+" "+l.Network+" "+l.Address)
	}
	return out
}

func list(t *testing.T, e *tenv) []string {
	t.Helper()
	ls, err := e.b.Listeners().List()
	if err != nil {
		t.Fatal(err)
	}
	return lines(ls)
}

func show(t *testing.T, e *tenv, name string) string {
	t.Helper()
	s, err := e.b.Listeners().Show(context.Background(), name)
	if err != nil {
		t.Fatalf("show %s: %v\n%s", name, err, e.stderr)
	}
	return s
}

// "tacacs listeners list: the built-in default, then what tacctl.yaml says".
func TestListenersList(t *testing.T) {
	e := newTenv(t)
	if got := list(t, e); !slices.Equal(got, []string{"default tcp :49"}) {
		t.Fatal(got)
	}
	// A tacctl.yaml that names no listener is not parsed (an unparsable one
	// warns nothing here).
	e.writeOverrides("password: [unterminated\n")
	if got := list(t, e); !slices.Equal(got, []string{"default tcp :49"}) || e.stderr.Len() != 0 {
		t.Fatal(got, e.stderr)
	}
	e.writeOverrides("listeners:\n  tacacs:\n    default: {network: tcp6, address: '[::]:4949'}\n    zeta: {address: '127.0.0.1:4951'}\n    alpha: {address: '127.0.0.1:4950'}\n")
	if got := list(t, e); !slices.Equal(got, []string{"default tcp6 [::]:4949", "alpha tcp 127.0.0.1:4950", "zeta tcp 127.0.0.1:4951"}) {
		t.Fatal(got)
	}
}

// "tacacs listeners list: an install that is not converted shows its
// hand-managed drop-in".
func TestListenersListNotConverted(t *testing.T) {
	e := newTenv(t)
	e.legacyDropIn("TACQUITO_NETWORK=tcp6", "TACQUITO_ADDRESS=[::]:4949")
	e.writeOverrides("listeners:\n  tacacs:\n    default: {network: tcp, address: '10.1.0.1:49'}\n")
	if got := list(t, e); !slices.Equal(got, []string{"default tcp6 [::]:4949"}) {
		t.Fatal(got)
	}
	// units_convert.bats "not converted: readers show the drop-in".
	s := show(t, e, "")
	mustLine(t, s, "  Current listener: tcp6 [::]:4949")
	mustLine(t, s, "  (override in "+e.b.overrideFile()+")")
}

// "config listen: show prints what it always printed for the default
// listener" (the backend's part: the lines between the blank line and the
// usage).
func TestListenersShowDefault(t *testing.T) {
	e := newTenv(t)
	if got := show(t, e, ""); got != "  Current listener: tcp :49\n  (template default)" {
		t.Fatalf("%q", got)
	}
	if got := show(t, e, "default"); !strings.HasPrefix(got, "  Current listener: tcp :49") {
		t.Fatalf("%q", got)
	}
}

// "config listen: a change restarts tacquito after a reload, and show
// names tacctl.yaml"; "drop-in: one settings change renders every flag of
// the default listener".
func TestListenerSetDefault(t *testing.T) {
	e := newTenv(t).withStore("store.multiscope.yaml")
	ctx := context.Background()
	if err := e.b.Listeners().Set(ctx, "default", "tcp", "10.1.0.1:49"); err != nil {
		t.Fatalf("%v\n%s", err, e.stderr)
	}
	mustContain(t, e.stdout.String(), "Listener changed to tcp 10.1.0.1:49. Service restarted.")
	var order []string
	for _, a := range e.run.Argvs() {
		if regexp.MustCompile(`^systemctl (daemon-reload|restart tacquito|is-active --quiet tacquito)$`).MatchString(a) {
			order = append(order, a)
		}
	}
	if !slices.Equal(order, []string{"systemctl daemon-reload", "systemctl restart tacquito", "systemctl is-active --quiet tacquito"}) {
		t.Fatal(e.run.Argvs())
	}
	dropin := e.dropIn("default")
	text := readFile(t, dropin)
	if !strings.HasPrefix(text, "# GENERATED by tacctl from tacctl.yaml") {
		t.Fatal(text)
	}
	for _, l := range []string{"[Service]", `Environment="TACQUITO_NETWORK=tcp"`, `Environment="TACQUITO_ADDRESS=10.1.0.1:49"`,
		`Environment="TACQUITO_LEVEL=20"`, `Environment="TACQUITO_METRICS_ADDRESS=127.0.0.1:8080"`,
		`Environment="TACQUITO_ACCT_LOG=` + e.p.Log + `/accounting.log"`} {
		mustLine(t, text, l)
	}
	if st, _ := os.Stat(dropin); st.Mode().Perm() != 0o644 {
		t.Fatalf("mode %v", st.Mode())
	}
	mustContain(t, readFile(t, e.p.Overrides), "address: 10.1.0.1:49")
	if exists(e.b.overrideFile()) || !e.recorded(dropin) {
		t.Fatal("hand-managed drop-in written, or the rendered one not recorded")
	}
	s := show(t, e, "")
	mustLine(t, s, "  Current listener: tcp 10.1.0.1:49")
	mustLine(t, s, "  (override in "+e.p.Overrides+")")
	// "config listen: with a store the change is snapshotted first".
	mustContain(t, e.stdout.String(), "Config snapshot saved to")
	if len(e.snapshots()) != 1 {
		t.Fatal(e.snapshots())
	}
	e.reset()
	if err := e.b.Listeners().Set(ctx, "", "tcp", "10.1.0.1:49"); err != nil {
		t.Fatal(err)
	}
	mustContain(t, e.stdout.String(), "Already listening on tcp 10.1.0.1:49.")
	if len(e.run.Calls()) != 0 {
		t.Fatal(e.run.Argvs())
	}
	e.noKeep()
}

// "config listen: a bad address is refused before anything is written",
// "config listen: rejects unknown subcommand", and the listeners verb
// growing no 'list' (tests/unit/backend.bats).
func TestListenerSetRefusesBadInput(t *testing.T) {
	e := newTenv(t).withStore("store.multiscope.yaml")
	ctx := context.Background()
	for _, c := range []struct{ net, addr, msg string }{
		{"tcp", "10.1.0.1", "Invalid tcp address: '10.1.0.1'"},
		{"tcp", "[::1]:49", "Invalid tcp address"},
		{"tcp6", "10.1.0.1:49", "Invalid tcp6 address"},
		{"tcp", ":0", "Invalid tcp address"},
		{"tcp", "example.net:49", "Invalid tcp address"},
		{"tcp", "", "Missing address. Example: tacctl config listen tcp :49"},
		{"udp", ":49", "Invalid subcommand: 'udp'. Use: show, tcp, tcp6, or reset"},
		{"list", "", "Invalid subcommand: 'list'. Use: show, tcp, tcp6, or reset"},
		{"bogus", "", "Invalid subcommand: 'bogus'"},
	} {
		e.reset()
		err := e.b.Listeners().Set(ctx, "default", c.net, c.addr)
		wantCode(t, err, 1)
		mustContain(t, e.stderr.String(), c.msg)
	}
	if exists(e.p.Overrides) || exists(e.dropIn("default")) || len(e.run.Calls()) != 0 || len(e.snapshots()) != 0 {
		t.Fatal("something was written")
	}
}

// "config listen: tcp6 asks first, and 'n' changes nothing".
func TestListenerSetTCP6Asks(t *testing.T) {
	e := newTenv(t).withStore("store.multiscope.yaml")
	ctx := context.Background()
	e.stdin("n\n")
	if err := e.b.Listeners().Set(ctx, "default", "tcp6", "[::]:49"); err != nil {
		t.Fatal(err)
	}
	mustContain(t, e.stdout.String(), "tcp6 enables dual-stack sockets")
	mustContain(t, e.stdout.String(), "Aborted.")
	if exists(e.p.Overrides) || exists(e.dropIn("default")) {
		t.Fatal("written")
	}
	e.reset()
	e.stdin("y\n")
	if err := e.b.Listeners().Set(ctx, "default", "tcp6", "[::]:49"); err != nil {
		t.Fatal(err)
	}
	mustContain(t, e.stdout.String(), "Listener changed to tcp6 [::]:49.")
	if envOf(t, e.dropIn("default"), "TACQUITO_NETWORK") != "tcp6" || envOf(t, e.dropIn("default"), "TACQUITO_ADDRESS") != "[::]:49" {
		t.Fatal(readFile(t, e.dropIn("default")))
	}
	// Already tcp6: no question.
	e.reset()
	e.stdin("")
	if err := e.b.Listeners().Set(ctx, "default", "tcp6", "[::]:4949"); err != nil {
		t.Fatal(err)
	}
	mustNotContain(t, e.stdout.String(), "dual-stack")
}

// "config listen: reset says what it always said, and goes back to the
// default"; config_setters.bats "config listen reset: clears override".
func TestListenerResetDefault(t *testing.T) {
	e := newTenv(t).withStore("store.multiscope.yaml")
	ctx := context.Background()
	if err := e.b.Listeners().Reset(ctx, ""); err != nil {
		t.Fatal(err)
	}
	mustContain(t, e.stdout.String(), "No listener override set. Already on template default (tcp :49).")
	if err := e.b.Listeners().Set(ctx, "default", "tcp", "10.1.0.1:49"); err != nil {
		t.Fatal(err)
	}
	e.reset()
	if err := e.b.Listeners().Reset(ctx, "default"); err != nil {
		t.Fatal(err)
	}
	mustContain(t, e.stdout.String(), "Listener override removed. Using template default. Service restarted.")
	mustLine(t, readFile(t, e.dropIn("default")), `Environment="TACQUITO_ADDRESS=:49"`)
	if exists(e.p.Overrides) && strings.Contains(readFile(t, e.p.Overrides), "listeners") {
		t.Fatal("listeners left in tacctl.yaml")
	}
	// A reset whose unit does not come up.
	if err := e.b.Listeners().Set(ctx, "default", "tcp", "10.1.0.1:49"); err != nil {
		t.Fatal(err)
	}
	e.reset()
	e.failActive(`tacquito$`)
	err := e.b.Listeners().Reset(ctx, "default")
	wantCode(t, err, 1)
	mustContain(t, e.stderr.String(), "tacquito failed to start after reset.")
}

// "config listen: a unit that does not come up gets the previous settings
// back".
func TestListenerSetUnitThatDoesNotComeUpIsPutBack(t *testing.T) {
	e := newTenv(t).withStore("store.multiscope.yaml")
	ctx := context.Background()
	if err := e.b.Listeners().Set(ctx, "default", "tcp", "10.1.0.1:49"); err != nil {
		t.Fatal(err)
	}
	before := state(e.dropIn("default"), e.p.Overrides, e.p.Rendered)
	e.reset()
	e.failActive(`tacquito$`)
	err := e.b.Listeners().Set(ctx, "default", "tcp", "10.9.9.9:49")
	wantCode(t, err, 1)
	mustContain(t, e.stderr.String(), "tacquito failed to start. Restoring previous override.")
	if state(e.dropIn("default"), e.p.Overrides, e.p.Rendered) != before {
		t.Fatal("not put back")
	}
	// Reload and restart twice: with the new address, then the old one.
	if n := e.countCalls(`^systemctl restart tacquito$`); n != 2 {
		t.Fatalf("restarts %d: %v", n, e.run.Argvs())
	}
	if n := e.countCalls(`^systemctl daemon-reload$`); n != 2 {
		t.Fatalf("reloads %d", n)
	}
	if v, _ := e.env.Conf.Get("listeners.tacacs.default.address", ""); v != "10.1.0.1:49" {
		t.Fatalf("the view was not reloaded: %q", v)
	}
	e.noKeep()
}

// "config listen: the first failure leaves no tacctl.yaml and no drop-in
// behind".
func TestListenerSetFirstFailureLeavesNothing(t *testing.T) {
	e := newTenv(t).withStore("store.multiscope.yaml")
	e.failActive(`tacquito$`)
	err := e.b.Listeners().Set(context.Background(), "default", "tcp", "10.9.9.9:49")
	wantCode(t, err, 1)
	if exists(e.p.Overrides) || exists(e.dropIn("default")) || exists(e.p.OverrideDir) {
		t.Fatal("left behind")
	}
	if exists(e.p.Rendered) && strings.Contains(readFile(t, e.p.Rendered), "tacctl.conf") {
		t.Fatal("still recorded")
	}
}

// "config listen: works without a store (legacy mode), as it always did".
func TestListenerSetWithoutStore(t *testing.T) {
	e := newTenv(t)
	ctx := context.Background()
	if err := e.b.Listeners().Set(ctx, "default", "tcp", "10.1.0.1:49"); err != nil {
		t.Fatalf("%v\n%s", err, e.stderr)
	}
	mustContain(t, e.stdout.String(), "Listener changed to tcp 10.1.0.1:49. Service restarted.")
	mustNotContain(t, e.stdout.String(), "snapshot")
	if err := e.b.LogLevel(ctx, "debug"); err != nil {
		t.Fatal(err)
	}
	if err := e.b.Metrics(ctx, "disable", ""); err != nil {
		t.Fatal(err)
	}
	d := e.dropIn("default")
	if envOf(t, d, "TACQUITO_ADDRESS") != "10.1.0.1:49" || envOf(t, d, "TACQUITO_LEVEL") != "30" ||
		envOf(t, d, "TACQUITO_METRICS_ADDRESS") != "127.0.0.1:0" {
		t.Fatal(readFile(t, d))
	}
	if exists(e.p.StoreFile) {
		t.Fatal("a store appeared")
	}
}

// "config listen: a hand-edited tacquito.yaml does not stand in the way".
func TestListenerSetIgnoresAHandEditedConfig(t *testing.T) {
	e := newTenv(t).withStore("store.multiscope.yaml")
	e.render(true)
	f, _ := os.OpenFile(e.p.Config, os.O_APPEND|os.O_WRONLY, 0)
	_, _ = f.WriteString("# edited\n")
	_ = f.Close()
	ctx := context.Background()
	if err := e.b.Listeners().Set(ctx, "default", "tcp", "10.1.0.1:49"); err != nil {
		t.Fatal(err)
	}
	if err := e.b.LogLevel(ctx, "debug"); err != nil {
		t.Fatal(err)
	}
	mustContain(t, readFile(t, e.p.Config), "# edited")
}

// "config listen --listener: adds a listener as its own instance,
// restarting nothing else"; "drop-in: an instance gets its own address,
// accounting log and no reachable metrics".
func TestListenerAddInstance(t *testing.T) {
	e := newTenv(t).withStore("store.multiscope.yaml")
	ctx := context.Background()
	if err := e.b.LogLevel(ctx, "debug"); err != nil {
		t.Fatal(err)
	}
	e.reset()
	if err := e.b.Listeners().Set(ctx, "mgmt", "tcp", "127.0.0.1:4949"); err != nil {
		t.Fatalf("%v\n%s", err, e.stderr)
	}
	mustContain(t, e.stdout.String(), "Listener 'mgmt' added on tcp 127.0.0.1:4949. tacquito@mgmt.service enabled and started.")
	mustContain(t, e.stdout.String(), e.p.Log+"/accounting-mgmt.log")
	for _, re := range []string{`^systemctl daemon-reload$`, `^systemctl enable --quiet tacquito@mgmt\.service$`,
		`^systemctl restart tacquito@mgmt\.service$`, `^systemctl is-active --quiet tacquito@mgmt\.service$`} {
		if !e.called(re) {
			t.Fatalf("no %s: %v", re, e.run.Argvs())
		}
	}
	if e.called(`^systemctl restart tacquito$`) {
		t.Fatal(e.run.Argvs())
	}
	mustContain(t, readFile(t, e.p.Overrides), "mgmt:")
	m := e.dropIn("mgmt")
	for k, v := range map[string]string{"TACQUITO_NETWORK": "tcp", "TACQUITO_ADDRESS": "127.0.0.1:4949", "TACQUITO_LEVEL": "30",
		"TACQUITO_METRICS_ADDRESS": "127.0.0.1:0", "TACQUITO_ACCT_LOG": e.p.Log + "/accounting-mgmt.log"} {
		if got := envOf(t, m, k); got != v {
			t.Fatalf("%s=%q, want %q", k, got, v)
		}
	}
	d := e.dropIn("default")
	if envOf(t, d, "TACQUITO_ADDRESS") != ":49" || envOf(t, d, "TACQUITO_ACCT_LOG") != e.p.Log+"/accounting.log" {
		t.Fatal(readFile(t, d))
	}

	// "config listen --listener: show, change and the flag forms".
	s := show(t, e, "mgmt")
	if s != "  Listener 'mgmt': tcp 127.0.0.1:4949\n  (tacquito@mgmt.service; set in "+e.p.Overrides+")" {
		t.Fatalf("%q", s)
	}
	s = show(t, e, "")
	mustLine(t, s, "  Current listener: tcp :49")
	mustLine(t, s, "  Listener 'mgmt': tcp 127.0.0.1:4949 (tacquito@mgmt.service)")
	e.reset()
	if err := e.b.Listeners().Set(ctx, "mgmt", "tcp", "127.0.0.1:4950"); err != nil {
		t.Fatal(err)
	}
	mustContain(t, e.stdout.String(), "Listener 'mgmt' changed to tcp 127.0.0.1:4950. tacquito@mgmt.service restarted.")
	if e.called(`^systemctl restart tacquito$`) || envOf(t, m, "TACQUITO_ADDRESS") != "127.0.0.1:4950" {
		t.Fatal(e.run.Argvs())
	}
	e.reset()
	_ = e.b.Listeners().Set(ctx, "mgmt", "tcp", "127.0.0.1:4950")
	mustContain(t, e.stdout.String(), "Already listening on tcp 127.0.0.1:4950.")
}

// "config listen --listener: an address another listener has is refused
// before anything is written".
func TestListenerCollisionsAreRefused(t *testing.T) {
	e := newTenv(t).withStore("store.multiscope.yaml")
	ctx := context.Background()
	err := e.b.Listeners().Set(ctx, "mgmt", "tcp", "10.1.0.1:49")
	wantCode(t, err, 1)
	mustContain(t, e.stderr.String(), "Cannot listen on tcp 10.1.0.1:49")
	mustContain(t, e.stderr.String(), "already used by listeners.tacacs.default (tcp :49)")
	if exists(e.p.Overrides) || exists(e.dropIn("mgmt")) || len(e.run.Calls()) != 0 {
		t.Fatal("written")
	}
	if err := e.b.Listeners().Set(ctx, "mgmt", "tcp", "127.0.0.1:4949"); err != nil {
		t.Fatal(err)
	}
	e.reset()
	wantCode(t, e.b.Listeners().Set(ctx, "other", "tcp", "127.0.0.1:4949"), 1)
	mustContain(t, e.stderr.String(), "already used by listeners.tacacs.mgmt")
	e.reset()
	wantCode(t, e.b.Listeners().Set(ctx, "default", "tcp", "127.0.0.1:4949"), 1)
	mustContain(t, e.stderr.String(), "already used by listeners.tacacs.mgmt")
}

// "config listen --listener: reset removes the listener, its drop-in and
// its instance".
func TestListenerResetInstance(t *testing.T) {
	e := newTenv(t).withStore("store.multiscope.yaml")
	ctx := context.Background()
	if err := e.b.Listeners().Set(ctx, "mgmt", "tcp", "127.0.0.1:4949"); err != nil {
		t.Fatal(err)
	}
	e.reset()
	if err := e.b.Listeners().Reset(ctx, "mgmt"); err != nil {
		t.Fatal(err)
	}
	mustContain(t, e.stdout.String(), "Listener 'mgmt' removed. tacquito@mgmt.service stopped and disabled.")
	if exists(e.dropIn("mgmt")) || !e.called(`^systemctl disable --quiet --now tacquito@mgmt\.service$`) || e.called(`^systemctl restart`) {
		t.Fatal(e.run.Argvs())
	}
	for _, f := range []string{e.p.Overrides, e.p.Rendered} {
		if exists(f) && strings.Contains(readFile(t, f), "mgmt") {
			t.Fatalf("%s names mgmt", f)
		}
	}
	e.reset()
	wantCode(t, e.b.Listeners().Reset(ctx, "mgmt"), 1)
	mustContain(t, e.stderr.String(), "No listener 'mgmt'.")
	e.reset()
	_, err := e.b.Listeners().Show(ctx, "mgmt")
	wantCode(t, err, 1)
	mustContain(t, e.stderr.String(), "No listener 'mgmt'. Create it: tacctl config listen --listener mgmt tcp <address>")
}

// "config listen --listener: an instance that does not come up is taken
// back out".
func TestListenerInstanceThatDoesNotComeUp(t *testing.T) {
	e := newTenv(t).withStore("store.multiscope.yaml")
	e.failActive(`tacquito@mgmt`)
	err := e.b.Listeners().Set(context.Background(), "mgmt", "tcp", "127.0.0.1:4949")
	wantCode(t, err, 1)
	mustContain(t, e.stderr.String(), "tacquito@mgmt failed to start. Restoring previous override.")
	if exists(e.p.Overrides) || exists(e.dropIn("mgmt")) || exists(filepath.Dir(e.dropIn("mgmt"))) {
		t.Fatal("left behind")
	}
	if !e.called(`^systemctl disable --quiet --now tacquito@mgmt\.service$`) {
		t.Fatal(e.run.Argvs())
	}
	mustNotContain(t, show(t, e, ""), "mgmt")
}

// "listeners verb: list, show, set and reset".
func TestListenersVerb(t *testing.T) {
	e := newTenv(t).withStore("store.multiscope.yaml")
	ctx := context.Background()
	ops := e.b.Listeners()
	if err := ops.Set(ctx, "mgmt", "tcp", "127.0.0.1:4949"); err != nil {
		t.Fatal(err)
	}
	if err := ops.Set(ctx, "default", "tcp", "10.1.0.1:49"); err != nil {
		t.Fatal(err)
	}
	if got := list(t, e); !slices.Equal(got, []string{"default tcp 10.1.0.1:49", "mgmt tcp 127.0.0.1:4949"}) {
		t.Fatal(got)
	}
	mustLine(t, show(t, e, ""), "  Current listener: tcp 10.1.0.1:49")
	mustLine(t, show(t, e, "mgmt"), "  Listener 'mgmt': tcp 127.0.0.1:4949")
	if err := ops.Reset(ctx, "mgmt"); err != nil {
		t.Fatal(err)
	}
	if err := ops.Reset(ctx, ""); err != nil {
		t.Fatal(err)
	}
	if got := list(t, e); !slices.Equal(got, []string{"default tcp :49"}) {
		t.Fatal(got)
	}
	if got := e.b.Describe().Units; !slices.Equal(got, []string{"tacquito.service"}) {
		t.Fatal(got)
	}
}

// "a user mutation still restarts tacquito once and touches no instance or
// drop-in".
func TestUserMutationRestartsTacquitoOnce(t *testing.T) {
	e := newTenv(t).withStore("store.multiscope.yaml")
	e.render(true)
	before := state(e.dropIn("default"))
	data := readFile(t, e.p.StoreFile)
	if _, err := e.set.StoreApply(context.Background(), backend.ApplyOptions{}, func() error {
		return os.WriteFile(e.p.StoreFile, []byte(strings.Replace(data, "juniper_class: OP-CLASS", "juniper_class: OPS", 1)), 0o600)
	}); err != nil {
		t.Fatalf("%v\n%s", err, e.stderr)
	}
	var sys []string
	for _, a := range e.run.Argvs() {
		if strings.HasPrefix(a, "systemctl") {
			sys = append(sys, a)
		}
	}
	if !slices.Equal(sys, []string{"systemctl reset-failed tacquito tacquito@*.service", "systemctl restart tacquito"}) || state(e.dropIn("default")) != before {
		t.Fatal(sys)
	}
}
