#!/usr/bin/env bats
# Unit tests for the TACACS+ renderer (lib/render_tacacs.sh): golden output,
# read-back safety, quoting, rendered.json bookkeeping, the daemon load-smoke,
# and the equivalence verdict of 'store import --check' for every
# tests/fixtures/tacquito.*.yaml.

load ../helpers/setup
load ../helpers/tmpenv
load ../helpers/fixtures

FIX="${BATS_TEST_DIRNAME}/../fixtures"

setup() {
    tacctl_tmpenv_init
    tacctl_source_lib
    OUT="${BATS_TEST_TMPDIR}/rendered.yaml"
    MODEL="${BATS_TEST_TMPDIR}/model.json"
}

# Load a store fixture and dump its model to $MODEL.
use_store() {
    cp "${FIX}/$1" "$STORE_FILE"
    _model_invalidate
    model_dump > "$MODEL"
}

# Write a model given as python-literal edits on top of the multiscope store.
#   edit_model '<python statements mutating m>'
edit_model() {
    use_store store.multiscope.yaml
    python3 - "$MODEL" "$1" <<'PY'
import json, sys
m = json.load(open(sys.argv[1]))
exec(sys.argv[2])
json.dump(m, open(sys.argv[1], 'w'))
PY
}

# yaml.safe_load the rendered file and evaluate a python expression on `d`.
rendered_py() {
    python3 - "$OUT" "$1" <<'PY'
import sys, yaml
d = yaml.safe_load(open(sys.argv[1]))
users = {u['name']: u for u in d.get('users') or []}
exec(sys.argv[2])
PY
}

# The migrations every 'tacctl upgrade' already runs on a tacquito.yaml.
upgrade_migrations() {
    chown() { :; }
    conf_migrate_exec_service_name > /dev/null
    conf_migrate_command_rules > /dev/null
    regenerate_tacquito_commands
}

HASH_X="24326224313224$(printf '58%.0s' {1..53})"

# --- golden output -----------------------------------------------------------

@test "render: store.minimal renders to the golden tacquito.yaml (0640)" {
    use_store store.minimal.yaml
    run render_tacacs_config "$MODEL" "$OUT"
    assert_success
    assert_output ""
    [[ "$(stat -c %a "$OUT")" == "640" ]]
    golden_diff "$OUT" tacquito.minimal.rendered.yaml
}

@test "render: store.multiscope renders to the golden tacquito.yaml" {
    use_store store.multiscope.yaml
    run render_tacacs_config "$MODEL" "$OUT"
    assert_success
    golden_diff "$OUT" tacquito.multiscope.rendered.yaml
}

@test "render: a rendered file imports back to the same model and re-renders byte-identically" {
    local name
    for name in minimal multiscope; do
        rm -f "$STORE_FILE"
        cp "${FIX}/golden/tacquito.${name}.rendered.yaml" "$CONFIG"
        run store_import
        assert_success
        refute_output --partial "Cannot be represented"
        diff -u "${FIX}/store.${name}.yaml" "$STORE_FILE"
        _model_invalidate
        model_dump > "$MODEL"
        render_tacacs_config "$MODEL" "$OUT"
        cmp "$OUT" "${FIX}/golden/tacquito.${name}.rendered.yaml"
    done
}

@test "render: leaves no temp file behind and replaces the target atomically" {
    use_store store.multiscope.yaml
    echo "previous content" > "$OUT"
    render_tacacs_config "$MODEL" "$OUT"
    run find "$BATS_TEST_TMPDIR" -maxdepth 1 -name '.tacquito.*'
    assert_output ""
    run head -1 "$OUT"
    assert_output --partial "GENERATED by tacctl"
}

# --- content rules -----------------------------------------------------------

@test "render: secrets are one entry per (scope, prefix), most specific first across scopes" {
    use_store store.multiscope.yaml
    render_tacacs_config "$MODEL" "$OUT"
    run rendered_py '
import json
print(" ".join(s["name"] + "=" + json.loads(s["options"]["prefixes"])[0] for s in d["secrets"]))
assert all(len(json.loads(s["options"]["prefixes"])) == 1 for s in d["secrets"])'
    assert_success
    assert_output "prod-inner=10.10.99.0/24 prod=10.0.0.0/8 lab=172.16.0.0/12 lab=192.168.0.0/16 dmz=203.0.113.0/24"
}

@test "render: every user carries its own authenticator and the file accounter" {
    use_store store.multiscope.yaml
    render_tacacs_config "$MODEL" "$OUT"
    run rendered_py '
for u in users.values():
    assert u["accounter"] == {"name": "tacquito_accounter", "type": 3}, u
    assert u["authenticator"]["type"] == 1
    assert len(u["groups"]) == 1
print(users["alice"]["groups"][0]["name"], users["alice"]["scopes"])'
    assert_success
    assert_output "superuser ['prod', 'lab']"
}

@test "render: disabled users, users without a hash and the root sink get the disabled marker" {
    edit_model "
m['users']['alice']['disabled'] = True
m['users']['bob']['hash'] = None
m['users']['bob']['disabled'] = True
m['users']['root'] = {'group': 'readonly', 'scopes': ['lab'], 'hash': None, 'disabled': True,
                      'password_changed': None, 'accounting_sink': True}"
    run render_tacacs_config "$MODEL" "$OUT"
    assert_success
    run rendered_py "
print(' '.join(n for n, u in sorted(users.items()) if u['authenticator']['options']['hash'] == '${DISABLED_MARKER_HEX}'))"
    assert_output "alice bob root"
    # alice's real hash stays in the store only.
    run grep -c "646f6e7463617265" "$OUT"
    assert_output "1"
}

@test "render: a scope limited to another protocol is left out, with its users' references" {
    edit_model "
m['scopes']['dmz']['protocols'] = ['radius']
m['scopes']['lab']['protocols'] = ['tacacs', 'radius']"
    run render_tacacs_config "$MODEL" "$OUT"
    assert_success
    run rendered_py "
print(sorted({s['name'] for s in d['secrets']}), users['carol']['scopes'])"
    assert_output "['lab', 'prod', 'prod-inner'] ['lab']"
}

@test "render: custom groups follow the built-ins; group services carry priv-lvl and class" {
    edit_model "
m['groups']['helpdesk'] = {'priv_lvl': 5, 'juniper_class': 'HELPDESK-CLASS', 'builtin': False}
m['groups']['auditor'] = {'priv_lvl': 2, 'juniper_class': 'AUDIT', 'builtin': False}
m['users']['bob']['group'] = 'helpdesk'"
    run render_tacacs_config "$MODEL" "$OUT"
    assert_success
    run grep -E '^[a-z_]+: &[a-z]+$' "$OUT"
    assert_output "readonly: &readonly
operator: &operator
superuser: &superuser
auditor: &auditor
helpdesk: &helpdesk"
    run rendered_py "
g = users['bob']['groups'][0]
print(g['name'], [(s['name'], s['set_values'][0]['name'], s['set_values'][0]['values']) for s in g['services']], 'commands' in g)"
    assert_output "helpdesk [('shell', 'priv-lvl', [5]), ('junos-exec', 'local-user-name', ['HELPDESK-CLASS'])] False"
}

@test "render: command rules come from tacctl.yaml and reach the daemon character for character" {
    cat > "$TACCTL_OVERRIDES_FILE" <<'YAML'
commands:
  operator:
    - {name: show, action: permit, match: ['^running-config\s*$', 'say "hi"', 'back\\slash']}
    - {name: "*", action: deny}
  superuser: []
YAML
    _conf_invalidate
    use_store store.multiscope.yaml
    run render_tacacs_config "$MODEL" "$OUT"
    assert_success
    run rendered_py '
op = users["bob"]["groups"][0]["commands"]
assert op == [{"name": "show", "match": ["^running-config\\s*$", "say \"hi\"", "back\\\\slash"], "action": 2},
              {"name": "*", "action": 1}], op
assert "commands" not in users["alice"]["groups"][0]
print([c["name"] for c in users["carol"]["groups"][0]["commands"]])'
    assert_success
    assert_output "['show', 'ping', 'traceroute', '*']"
}

@test "render: prefix filters are emitted sorted, and omitted when empty" {
    use_store store.multiscope.yaml
    render_tacacs_config "$MODEL" "$OUT"
    run grep -c '^prefix_' "$OUT"
    assert_output "0"
    edit_model "
m['filters']['allow'] = ['10.0.0.0/8', '10.9.0.0/16']
m['filters']['deny'] = ['10.9.9.0/24']"
    render_tacacs_config "$MODEL" "$OUT"
    run grep '^prefix_' "$OUT"
    assert_output 'prefix_allow: ["10.9.0.0/16", "10.0.0.0/8"]
prefix_deny: ["10.9.9.0/24"]'
}

# --- quoting -----------------------------------------------------------------

@test "render: secrets with quotes, backslashes and non-ASCII reach the daemon unchanged" {
    edit_model "
m['scopes']['lab']['secret'] = 'a\"b\\\\c: #d \\u00e9\\u2028\\U0001f511 {e}'"
    run render_tacacs_config "$MODEL" "$OUT"
    assert_success
    run rendered_py "
key = next(s['secret']['key'] for s in d['secrets'] if s['name'] == 'lab')
assert key == 'a\"b\\\\c: #d \\u00e9\\u2028\\U0001f511 {e}', repr(key)
print('ok')"
    assert_output "ok"
    # The file itself stays ASCII there, so no parser can fold or re-code it.
    run grep -c 'key: "a\\"b\\\\c: #d \\xe9\\u2028\\U0001f511 {e}"' "$OUT"
    assert_output "2"
}

@test "render: names YAML could misread are quoted; names that collide with layout keys get their own key" {
    edit_model "
g = {'priv_lvl': 3, 'juniper_class': 'C', 'builtin': False}
m['groups']['no'] = dict(g)
m['groups']['users'] = dict(g)
m['groups']['exec_operator'] = dict(g)
m['scopes']['on'] = {'prefixes': ['198.51.100.0/24'], 'secret': 'on-secret-0123456789abcdef', 'protocols': None}
u = m['users']['alice']
m['users']['123'] = dict(u, group='no', scopes=['on'])
m['users']['null'] = dict(u, group='users')
m['users']['Yes'] = dict(u, group='exec_operator')"
    run render_tacacs_config "$MODEL" "$OUT"
    assert_success
    run rendered_py "
assert isinstance(d['users'], list) and len(d['users']) == 6
assert all(isinstance(k, str) for k in d), list(d)
print(users['123']['groups'][0]['name'], users['123']['scopes'],
      users['null']['groups'][0]['name'], users['Yes']['groups'][0]['name'])
print(sorted(k for k in d if k.startswith('group_')))
print(d['exec_operator']['set_values'][0]['values'], d['group_exec_operator']['name'])"
    assert_success
    assert_output "no ['on'] users exec_operator
['group_exec_operator', 'group_users']
[7] exec_operator"
}

@test "render: an all-digit hash is quoted so it stays a string" {
    local digits="24326224313224$(printf '31%.0s' {1..53})"
    edit_model "m['users']['bob']['hash'] = '${digits}'"
    run render_tacacs_config "$MODEL" "$OUT"
    assert_success
    run grep -c "hash: \"${digits}\"" "$OUT"
    assert_output "1"
    run rendered_py "assert users['bob']['authenticator']['options']['hash'] == '${digits}'"
    assert_success
}

# --- refusals ----------------------------------------------------------------

@test "render: an invalid model is refused and nothing is written" {
    edit_model "m['users']['bob']['group'] = 'nosuch'"
    run render_tacacs_config "$MODEL" "$OUT"
    assert_failure 1
    assert_output --partial "cannot render an invalid model"
    assert_output --partial "user 'bob': group 'nosuch' does not exist"
    [[ ! -e "$OUT" ]]
}

@test "render: a tacctl.yaml that does not parse is refused instead of rendering default command rules" {
    use_store store.multiscope.yaml
    printf 'commands:\n  operator: [oops\n' > "$TACCTL_OVERRIDES_FILE"
    _conf_invalidate
    run render_tacacs_config "$MODEL" "$OUT"
    assert_failure 1
    assert_output --partial "fix it before rendering"
    [[ ! -e "$OUT" ]]
}

@test "render: a command rule with an unknown action is refused" {
    use_store store.multiscope.yaml
    _TACCTL_CFG_CACHE='{"commands": {"operator": [{"name": "show", "action": "allow"}]}}'
    run render_tacacs_config "$MODEL" "$OUT"
    assert_failure 1
    assert_output --partial "neither permit nor deny"
    [[ ! -e "$OUT" ]]
}

@test "render: the read-back check catches a file that does not say what the model says" {
    use_store store.multiscope.yaml
    # Sabotage the quoting helper: secrets now render without their escapes.
    _render_tacacs_py_orig=$(declare -f _render_tacacs_py)
    eval "${_render_tacacs_py_orig/_render_tacacs_py/_render_tacacs_py_real}"
    _render_tacacs_py() {
        _render_tacacs_py_real | sed "s/out.append('\\\\\\\\' + ch)/out.append(ch)/"
    }
    python3 - "$MODEL" <<'PY'
import json, sys
m = json.load(open(sys.argv[1]))
m['scopes']['lab']['secret'] = 'tricky\\\\secret-0123456789'
json.dump(m, open(sys.argv[1], 'w'))
PY
    run render_tacacs_config "$MODEL" "$OUT"
    assert_failure 1
    assert_output --partial "does not read back as the model"
    assert_output --partial "scopes differ"
    refute_output --partial "tricky"
    [[ ! -e "$OUT" ]]
}

# --- rendered.json bookkeeping -----------------------------------------------

@test "rendered_check: unrecorded, ok, drift, missing" {
    echo "one" > "$OUT"
    run rendered_check "$OUT"
    assert_failure 3
    assert_output "unrecorded"
    rendered_record "$OUT"
    [[ "$(stat -c %a "$RENDERED_FILE")" == "600" ]]
    run rendered_check "$OUT"
    assert_success
    assert_output "ok"
    echo "two" >> "$OUT"
    run rendered_check "$OUT"
    assert_failure 1
    assert_output "drift"
    rm "$OUT"
    run rendered_check "$OUT"
    assert_failure 2
    assert_output "missing"
}

@test "rendered.json: maps absolute path to sha256; record and forget keep other entries" {
    echo "one" > "$OUT"
    echo "other" > "${OUT}.2"
    rendered_record "$OUT"
    rendered_record "${OUT}.2"
    run python3 -c "
import hashlib, json, sys
d = json.load(open(sys.argv[1]))
assert d == {p: hashlib.sha256(open(p, 'rb').read()).hexdigest() for p in sys.argv[2:]}, d
print(len(d))" "$RENDERED_FILE" "$OUT" "${OUT}.2"
    assert_output "2"
    rendered_forget "$OUT"
    run rendered_check "$OUT"
    assert_output "unrecorded"
    run rendered_check "${OUT}.2"
    assert_output "ok"
}

@test "rendered_check: a corrupt rendered.json is a failure, never 'ok'" {
    echo "one" > "$OUT"
    echo "{not json" > "$RENDERED_FILE"
    run rendered_check "$OUT"
    assert_failure 4
    refute_output --partial "ok"
}

@test "backends_check_drift: silent before any render; lists drifted and missing artifacts" {
    run backends_check_drift
    assert_success
    assert_output ""
    echo "one" > "$OUT"
    echo "other" > "${OUT}.2"
    rendered_record "$OUT"
    rendered_record "${OUT}.2"
    run backends_check_drift
    assert_success
    assert_output ""
    echo "edit" >> "$OUT"
    rm "${OUT}.2"
    run backends_check_drift
    assert_failure 1
    assert_line "drift	${OUT}"
    assert_line "missing	${OUT}.2"
    echo "{not json" > "$RENDERED_FILE"
    run backends_check_drift
    assert_failure 1
    assert_output "unreadable	${RENDERED_FILE}"
}

@test "tier: config render is superuser-only" {
    run tier_permits superuser config render
    assert_success
    run tier_permits operator config render
    assert_failure
    run tier_permits readonly config render
    assert_failure
}

# --- daemon load-smoke -------------------------------------------------------

# A stand-in for the tacquito binary that records its argv and pid, then
# behaves as told: 'serve' logs like a healthy daemon and stays up, 'fatal'
# logs a loader failure and exits 0 (as tacquito does), 'hang' says nothing.
fake_tacquito() {
    cat > "${TACCTL_BIN}/tacquito" <<SH
#!/usr/bin/env bash
printf '%s\n' "\$@" > "${BATS_TEST_TMPDIR}/smoke.argv"
echo \$\$ > "${BATS_TEST_TMPDIR}/smoke.pid"
case "$1" in
    serve)
        echo "INFO: main.go:135: serve on 127.0.0.1:40001" >&2
        echo "INFO: loader.go:241: updated all providers from config source" >&2
        exec sleep 30 ;;
    fatal)
        echo "FATAL: main.go:98: error fetching config; loader failed: no users were unmarshalled from config, cannot serve" >&2
        exit 0 ;;
    hang)
        exec sleep 30 ;;
esac
SH
    chmod +x "${TACCTL_BIN}/tacquito"
}

smoke_arg() {   # value following flag $1 in the recorded argv
    grep -x -A1 -- "$1" "${BATS_TEST_TMPDIR}/smoke.argv" | tail -1
}

@test "smoke: skipped (2) when the daemon binary is absent" {
    echo "x" > "$OUT"
    run tacacs_load_smoke "$OUT"
    assert_failure 2
    assert_output ""
}

@test "smoke: passes when the daemon serves; runs isolated; the daemon is gone afterwards" {
    fake_tacquito serve
    echo "users: []" > "$OUT"
    run tacacs_load_smoke "$OUT"
    assert_success
    # Loopback, kernel-chosen ports: never the production listener.
    [[ "$(smoke_arg -network)" == "tcp" ]]
    [[ "$(smoke_arg -address)" == "127.0.0.1:0" ]]
    [[ "$(smoke_arg -metrics-address)" == "127.0.0.1:0" ]]
    # Private copy of the config and a private accounting log, both removed.
    local cfg acct
    cfg=$(smoke_arg -config)
    acct=$(smoke_arg -acct-log-path)
    [[ "$cfg" != "$OUT" && "$cfg" != "$CONFIG" ]]
    [[ "$acct" != "$ACCT_LOG" && "$acct" != /var/log/* ]]
    [[ "$(dirname "$cfg")" != "$(dirname "$acct")" ]]
    [[ ! -e "$cfg" && ! -e "$acct" ]]
    [[ ! -e "$ACCT_LOG" ]]
    run kill -0 "$(cat "${BATS_TEST_TMPDIR}/smoke.pid")"
    assert_failure
}

@test "smoke: a config the daemon rejects fails, with the reason and without its log" {
    fake_tacquito fatal
    echo "users: []" > "$OUT"
    run tacacs_load_smoke "$OUT"
    assert_failure 1
    assert_output --partial "tacquito refuses a config with no users"
    refute_output --partial "main.go"
}

@test "smoke: a daemon that never serves fails after the time limit and is killed" {
    fake_tacquito hang
    TACACS_SMOKE_SECONDS=1
    echo "users: []" > "$OUT"
    run tacacs_load_smoke "$OUT"
    assert_failure 1
    assert_output --partial "did not start serving within 1s"
    run kill -0 "$(cat "${BATS_TEST_TMPDIR}/smoke.pid")"
    assert_failure
}

# --- 'store import --check' verdict for every tacquito.* fixture -------------
#
# The fixtures are hand-built and predate two things the product did to
# real files: it wrote each group's command rules from tacctl.yaml
# (regenerate_tacquito_commands, on install and every upgrade) and it kept
# secrets[] flat and sorted by specificity (on install and on every scope
# mutation -- never on upgrade, and the code that did it is gone now that
# both render from the store). So the honest verdict on a raw fixture is NOT
# EQUIVALENT, and EQUIVALENT once upgrade's migrations have run on it --
# except for multiscope, whose secrets[] order no pre-store release would
# have left on disk and which upgrade does not sort.

@test "check: tacquito.minimal raw differs only latently (groups have no command rules yet)" {
    place_fixture tacquito.minimal.yaml
    run store_import --check
    assert_failure 1
    assert_output --partial "render:              OK"
    assert_output --partial "differ only in groups without users or scopes without users"
    assert_output --partial "NOT EQUIVALENT"
    assert_output --partial '+      "commands": ['
    [[ ! -e "$STORE_FILE" && ! -e "$RENDERED_FILE" ]]
}

@test "check: tacquito.legacy-exec raw is NOT equivalent (service 'exec' is not 'shell')" {
    place_fixture tacquito.legacy-exec.yaml
    run store_import --check
    assert_failure 1
    assert_output --partial '-          "name": "exec",'
    assert_output --partial '+          "name": "shell",'
    assert_output --partial "NOT EQUIVALENT"
}

@test "check: tacquito.dead-matches raw is NOT equivalent (rendering drops the dead match regexes)" {
    place_fixture tacquito.dead-matches.yaml
    run store_import --check
    assert_failure 1
    assert_output --partial '-          "match": ['
    assert_output --partial '^show .*$'
    assert_output --partial "NOT EQUIVALENT"
}

@test "check: tacquito.multiscope raw is NOT equivalent: its users gain command rules" {
    place_fixture tacquito.multiscope.yaml
    run store_import --check
    assert_failure 1
    assert_output --partial "NOT EQUIVALENT"
    # A difference clients would feel today, not a latent one.
    refute_output --partial "differ only in groups without users"
    assert_output --partial '+          "commands": ['
    # The user-level accounter the renderer adds is NOT a difference: the
    # daemon already hands these users their group's file accounter.
    refute_output --partial '"accounter"'
    # prod-inner has no users, so the daemon loads neither copy of it; the
    # reordering shows up only in the every-scope-had-users view.
    assert_output --partial "scope 'prod-inner' has no users; tacquito does not load it"
    assert_output --partial "10.10.99.0/24 never matches a client (an earlier entry already covers it with 10.0.0.0/8) once every scope has a user"
    run bash -c 'grep -c "\"prefix\": \"10.10.99.0/24\"" <<< "$1"' _ "$output"
    assert_output "1"
}

@test "check: a fixture with secrets[] in product order is EQUIVALENT once upgrade's migrations have run on it" {
    local f
    for f in minimal legacy-exec dead-matches; do
        place_fixture "tacquito.${f}.yaml"
        _conf_invalidate
        rm -f "$TACCTL_OVERRIDES_FILE"
        upgrade_migrations
        run store_import --check
        assert_success
        assert_output --partial "    EQUIVALENT"
        assert_output --partial "daemon load-smoke:   SKIPPED"
        assert_output --partial "Check passed. Nothing was written."
        [[ ! -e "$STORE_FILE" && ! -e "$RENDERED_FILE" ]]
    done
}

@test "check: upgrade's migrations alone leave tacquito.multiscope latently different (prod before prod-inner)" {
    place_fixture tacquito.multiscope.yaml
    upgrade_migrations
    run store_import --check
    assert_failure 1
    assert_output --partial "differ only in groups without users or scopes without users"
    assert_output --partial "NOT EQUIVALENT"
    refute_output --partial '"commands"'
}

@test "check: operator command overrides in tacctl.yaml are part of the proof" {
    place_fixture tacquito.minimal.yaml
    upgrade_migrations
    conf_set_json commands.operator '[{"name": "show", "action": "permit"}, {"name": "*", "action": "deny"}]'
    run store_import --check
    assert_failure 1
    assert_output --partial '"name": "terminal"'
    regenerate_tacquito_commands
    run store_import --check
    assert_success
}

@test "check: a rendered file checks EQUIVALENT against itself" {
    cp "${FIX}/golden/tacquito.multiscope.rendered.yaml" "$CONFIG"
    run store_import --check
    assert_success
    assert_output --partial "    EQUIVALENT"
}

@test "check: exit 3 only when no renderer is loaded" {
    cp "${FIX}/golden/tacquito.multiscope.rendered.yaml" "$CONFIG"
    unset -f render_tacacs_config
    run store_import --check
    assert_failure 3
    assert_output --partial "render:              SKIPPED (no renderer available)"
}

@test "check: the real load-smoke result decides the check" {
    cp "${FIX}/golden/tacquito.multiscope.rendered.yaml" "$CONFIG"
    fake_tacquito serve
    run store_import --check
    assert_success
    assert_output --partial "daemon load-smoke:   OK"
    fake_tacquito fatal
    run store_import --check
    assert_failure 1
    assert_output --partial "daemon load-smoke:   FAILED"
}
